apiVersion: v1
kind: Secret
metadata:
    name: restic-config-sonarr
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:qd+eendrpBk1q7obzLxqZTD3LHtVpA5gmCiqL46/0SxSBtRiSCojoLO8,iv:QNhlBfBkwpfCsf0dONkBGRtsEy+SGz5/zxfosOxCFc4=,tag:qGmTXQIw2qUb9tb6zi4hlw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:55dIlq5fYwIrPCW2BArBTGf9,iv:Lw+3s3cBmqM526oaZWG9LM9RVWLo6x/daZTeY5RGWfc=,tag:o3W2fqySDdGISzApetZD+w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zGFc5Vto,iv:SNeU/YXaxhe7UMn1ZHKPtGGMT5ntzj9WGa0Y3fTgXcE=,tag:soPSRmBkoA/glGho43gQ+A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mRaqw3Od9E1ExhbL,iv:C9+Z/1aj738HiG9A/9KOa24olrEpuwYhRMZ15f5hnSw=,tag:2o6S8TmThSlX11N7jnvIJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:47:20Z"
    mac: ENC[AES256_GCM,data:qneZlqc5syQL7YIgiwyMcKHQJmMCxwPGjD8vo11ZVSivS7Kq5PNWi+NZ8r+8elrTv950Ag2DAfO8jk/H/LxE90Igyz83IojdLUfiB0U4H5Izn0kZfjFjADT7zr6+gA0zjND1WXBxO+pFnbcAl8fxd7kMRPe4qlKEmsCDMbzPW4A=,iv:mqN7HpKAOw4qcJLGb4rLXe/R/NOFAzCZbuLjpA/Wbr8=,tag:ybWw3ABJ3Ea/zBzecs5X9A==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
    name: sonarr
spec:
    sourcePVC: sonarr
    trigger:
        schedule: 0 22 * * *
    restic:
        pruneIntervalDays: 7
        repository: restic-config-sonarr
        cleanupTempPVC: true
        cleanupCachePVC: true
        retain:
            hourly: 1
            daily: 1
            weekly: 1
            monthly: 1
            yearly: 1
        copyMethod: Direct
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:47:20Z"
    mac: ENC[AES256_GCM,data:qneZlqc5syQL7YIgiwyMcKHQJmMCxwPGjD8vo11ZVSivS7Kq5PNWi+NZ8r+8elrTv950Ag2DAfO8jk/H/LxE90Igyz83IojdLUfiB0U4H5Izn0kZfjFjADT7zr6+gA0zjND1WXBxO+pFnbcAl8fxd7kMRPe4qlKEmsCDMbzPW4A=,iv:mqN7HpKAOw4qcJLGb4rLXe/R/NOFAzCZbuLjpA/Wbr8=,tag:ybWw3ABJ3Ea/zBzecs5X9A==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
    name: sonarr
spec:
    trigger:
        manual: restore-once
    restic:
        repository: restic-config-sonarr
        destinationPVC: sonarr
        copyMethod: Direct
        cleanupCachePVC: true
        cleanupTempPVC: true
        moverSecurityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:47:20Z"
    mac: ENC[AES256_GCM,data:qneZlqc5syQL7YIgiwyMcKHQJmMCxwPGjD8vo11ZVSivS7Kq5PNWi+NZ8r+8elrTv950Ag2DAfO8jk/H/LxE90Igyz83IojdLUfiB0U4H5Izn0kZfjFjADT7zr6+gA0zjND1WXBxO+pFnbcAl8fxd7kMRPe4qlKEmsCDMbzPW4A=,iv:mqN7HpKAOw4qcJLGb4rLXe/R/NOFAzCZbuLjpA/Wbr8=,tag:ybWw3ABJ3Ea/zBzecs5X9A==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
