apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dynamo-platform
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: dynamo-platform
      version: '1.4.2'
      sourceRef:
        kind: HelmRepository
        name: dynamo-platform
      interval: 24h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    global:
      # Kubernetes-native discovery does not require bundled etcd or NATS.
      etcd:
        install: false
      nats:
        install: false
      # install grove and Kai Scheduler bundled with this helm chart. Not recommended for production.
      grove:
        install: true
      kai-scheduler:
        install: true

    dynamo-operator:
      discoveryBackend: kubernetes
      controllerManager:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                        - amd64
      dynamo:
        metrics:
          prometheusEndpoint: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          podMonitors:
            enabled: true
      metricsService:
        enabled: true

    grove:
      nodeSelector:
        kubernetes.io/arch: amd64
      webhookServerSecret:
        enabled: false
      config:
        server:
          healthProbes:
            enable: true

    kai-scheduler:
      global:
        nodeSelector:
          kubernetes.io/arch: amd64
