---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: qwen-38-27b-fp8
  name: qwen-38-27b-fp8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
