apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 5m
  chart:
    spec:
      chart: reflector
      version: '9.1.7'
      sourceRef:
        kind: HelmRepository
        name: emberstack
      interval: 5m