apiVersion: v1
kind: Secret
metadata:
    name: cliparr
type: Opaque
stringData:
    app-key: ENC[AES256_GCM,data:5LHcXJ+Y1AiGixLWSjoD89JhKegYWeHprtt1VzGI4MM=,iv:gvuG5Opkype2JfkTcpxGj3On8rEEDG5yNKeenpRNK84=,tag:yAcpZIyqFcNJ9FQZauZ7oQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SVYraUhzY2t6YTBqL3Qy
            ckZFWnFhOG5hQVdLVGsvdjhIQjhOcnB6MURnCkV4Mmg1enU2Z0xuMWNlZ28rK28y
            aXpzeWFQRit4MEI1QVFJVHJiaFpjYWcKLS0tIEY0b2hHRS8zU0xSYThnYjArSFRU
            dVlVb2g4dDVqOERCV05ubFgrNG9NL3MKoOMHPd3fc3bG6ZTL7ZBhz81nj2cKHEr8
            pJzt0JP5uOoT/gCvqhRSfHv0CAS5teyhow0g2ra7vpzkwdjE0iN8ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T15:41:32Z"
    mac: ENC[AES256_GCM,data:5MAFRK4/hhKI0j5EF3ChYj7p8GYHWeVkvpTjY2rgbNq2UUoYvqJSMR4zRagfukUiJzXULStsPTruPsAzrE1HD2W9rH6soTs9O1HBL3eVee3ccsUjRBFucrHegl61xjzRGf7gSszEZbTi6GbpSN/6InuG+85GcqvvcZ+8Adgy2J8=,iv:tq2CYRQ5trYhjiIDqJPMOiBxyjxtKUoBnkl/zQFEfiE=,tag:NW9mz/4fTDTS6r+uqBviAQ==,type:str]
    pgp: []
    encrypted_regex: app-key
    version: 3.9.1
