apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 5m
  chart:
    spec:
      chart: plex-media-server
      version: '1.1.2'
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: plex
      interval: 5m
  values: 
    ingress:
      enabled: true
      ingressClassName: nginx
      url: "plex.almothana.xyz"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
    pms:
      configStorage: 10Gi
      resources:
        limits:
          cpu: 3500m
          memory: 3Gi
        requests:
          cpu: 1000m
          memory: 512Mi
    extraEnv:
      TZ: "Asia/Riyadh"
      PLEX_CLAIM: "claim-sufL9x_UfUbbzbk3GquU"
    extraVolumeMounts:
      - name: plex-library
        mountPath: /library
    extraVolumes:
      - name: plex-library
        persistentVolumeClaim:
          claimName: plex-library