apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-library
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  storageClassName: nfs
  nfs:
    server: 192.168.0.109
    path: "/volume1/library"