apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-library
  namespace: plex
spec:
  storageClassName: synology-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi