apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-library
  namespace: plex
spec:
  volumeName: nfs-library
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
