apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: '6.49.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  values: 
    deploymentMode: SimpleScalable
    loki:
      auth_enabled: false 
      schemaConfig:
        configs:
          - from: "2025-01-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ingester:
        chunk_encoding: snappy
      querier:
        # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
        max_concurrent: 4
      pattern_ingester:
        enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 336h # 14 days retention
      storage:
        type: s3
        bucketNames:
            chunks: loki-chunks
            ruler: loki-ruler
        s3:
          s3: s3://LB25dfzbb51zPfPM:BpdveGM83ZBwPdgg3DUKf5YNWopMucKw@minio.almothana.xyz:9000/loki
          s3ForcePathStyle: true
    backend:
      replicas: 2
    read:
      replicas: 2
    write:
      replicas: 3 # To ensure data durability with replication
