apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 24h
  chart:
    spec:
      chart: pihole
      version: "2.29.1"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
      interval: 24h
  values: 
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: 
        - pi-hole.almothana.xyz
      tls:
        - secretName: almothana-xyz-tls
          hosts:
          - pi-hole.almothana.xyz
    serviceDns:
      mixedService: true
      externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.0.252
      type: LoadBalancer
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    persistentVolumeClaim:
      enabled: true
    extraEnvVars:
      TZ: "Asia/Riyadh"
    admin:
      enabled: true
      existingSecret: "admin"
      passwordKey: "pihole_password"