kind: Secret
apiVersion: v1
metadata:
    name: admin
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: external-dns
stringData:
    pihole_password: ENC[AES256_GCM,data:SEa3f8t6RIhukyc=,iv:0J+B5WLDT72opXKpxPJMCqtD9mvNdzpBOmnqvmj30DY=,tag:n6IPC5JJ0Rcb5a8f9l+zFA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOEw3b3daTy9WNGVwRkk0
            ZTZheDgrcU9WTlVSQjIydGdSZWxFaERlR244CkhFWlN5S3FSS1BrdUVFT0NkbGh0
            WWJvcXBJeHczc3RXcG1UVzNkWmNINncKLS0tIHRGa20xN0lEZXFabld2YjBlc0gx
            djd0TUF0N3ZsUWdpZ1BMb0xYRXc5a3MKlOjPnLg7JbvGUZupRI3Djdq8fUf68cTs
            eTrb/TuvMAgYwu1mJ/Y5c/JYYClBzE4cOYQSNapZrH3RiuPerW+3Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T12:13:23Z"
    mac: ENC[AES256_GCM,data:e65d9yUR0BvN5+Gh/rViAxsxjjCdl1Maq5GCVHAdi7LZfkFYUVhYshLarMzKYekBEmUTEjjcsYlX1vmUNV3SpFVghzY6rOoDwI7CsFpTp3ykgE+ubzVE1F9nJN3ufqn/+2pC1vlNGiXlrMhW4JgPxVkSG5W5HoXQsWvMBbvAto0=,iv:lnjpmXEtMHbmOj0YGM6TMz9C4S11XO9gaqiGyjMhyNU=,tag:HznZV471qjs5r8XJSPzusw==,type:str]
    pgp: []
    encrypted_regex: password
    version: 3.9.1
