kind: Secret
apiVersion: v1
metadata:
    name: admin
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: external-dns
stringData:
    password: ENC[AES256_GCM,data:ojCmdSPSHx57YmQ=,iv:qN2njwCkuDKV+T5bAOwHgLEc6SZzOWgjQND3i5uwM0s=,tag:1cOcv1XwiPDqXNnKRnnX+A==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOEw3b3daTy9WNGVwRkk0
            ZTZheDgrcU9WTlVSQjIydGdSZWxFaERlR244CkhFWlN5S3FSS1BrdUVFT0NkbGh0
            WWJvcXBJeHczc3RXcG1UVzNkWmNINncKLS0tIHRGa20xN0lEZXFabld2YjBlc0gx
            djd0TUF0N3ZsUWdpZ1BMb0xYRXc5a3MKlOjPnLg7JbvGUZupRI3Djdq8fUf68cTs
            eTrb/TuvMAgYwu1mJ/Y5c/JYYClBzE4cOYQSNapZrH3RiuPerW+3Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T11:43:53Z"
    mac: ENC[AES256_GCM,data:SpHDkJFVeljJj2633GyfBoYofRb/vUEBUzy0byRGmJgoaSpW/GkB/Ay4l6NFZNnN6x9/Xd5Rg/odQp+s6DUtiLJA4+04ixRvPSnRQwsoUWx1um5fUYDXosaBYRnvVvZyp/EImkmVowBOe9QNrR2W7rWmoxczDbADsEe9CiIkJOw=,iv:2hMEShnrbyCJConzQauzGXqUsp7jDvNJGn6TRO26jMQ=,tag:WKsbq/Zk8Yq/UtqS+Mjdxg==,type:str]
    pgp: []
    encrypted_regex: password
    version: 3.9.1
