apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
      interval: 5m
  values:
    # Disable volume snapshots as we are using MinIO.
    snapshotsEnabled: false
    # use 1.33.4 tag to fix error: docker.io/bitnamilegacy/kubectl:1.34: not found
    kubectl:
      image:
        repository: docker.io/bitnamilegacy/kubectl
        tag: 1.33.4
    configuration:
      backupStorageLocation:
      - name: "minio"
        provider: "aws"
        bucket: "velero"
        # default indicates this location is the default backup storage location. Optional.
        default: true
        credential:
          name: minio-credentials
          key: credentials-velero
        config: 
         region: minio
         s3ForcePathStyle: true
         s3Url: "http://nas:9001"