apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
      interval: 5m
  values: 
    configuration:
      backupStorageLocation:
      - name: "minio"
        provider: "aws"
        bucket: "velero"
        # default indicates this location is the default backup storage location. Optional.
        default: true
        credential:
          # name of the secret used by this backupStorageLocation.
          name: minio-credentials
          # name of key that contains the secret data to be used.
          key:
        # Additional provider-specific configuration. See link above
        # for details of required/optional fields for your provider.
        config: 
         region: minio
         s3ForcePathStyle: true
         s3Url: "http://nas:9001"


        # annotations allows adding arbitrary annotations to this BackupStorageLocation resource. Optional.
        annotations: {}

      # Parameters for the VolumeSnapshotLocation(s). Configure multiple by adding other element(s) to the volumeSnapshotLocation slice.
      # See https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
      volumeSnapshotLocation:
        # name is the name of the volume snapshot location where snapshots are being taken. If a name is not provided,
        # a volume snapshot location will be created with the name "default". Optional.
      - name:
        # provider is the name for the volume snapshot provider.
        provider: ""
        credential:
          # name of the secret used by this volumeSnapshotLocation.
          name:
          # name of key that contains the secret data to be used.
          key:
        # Additional provider-specific configuration. See link above
        # for details of required/optional fields for your provider.
        config: {}
      #    region:
      #    apiTimeout:
      #    resourceGroup:
      #    The ID of the subscription where volume snapshots should be stored, if different from the cluster’s subscription. If specified, also requires `configuration.volumeSnapshotLocation.config.resourceGroup`to be set. (Azure only)
      #    subscriptionId:
      #    incremental:
      #    snapshotLocation:
      #    project:

        # annotations allows adding arbitrary annotations to this VolumeSnapshotLocation resource. Optional.
        annotations: {}

      # These are server-level settings passed as CLI flags to the `velero server` command. Velero
      # uses default values if they're not passed in, so they only need to be explicitly specified
      # here if using a non-default value. The `velero server` default values are shown in the
      # comments below.
      # --------------------
      # `velero server` default: kopia
      uploaderType:
      # `velero server` default: 1m
      backupSyncPeriod:
      # `velero server` default: 4h
      fsBackupTimeout:
      # `velero server` default: 30
      clientBurst:
      # `velero server` default: 500
      clientPageSize:
      # `velero server` default: 20.0
      clientQPS:
      # Name of the default backup storage location. Default: default
      defaultBackupStorageLocation:
      # The default duration any single item operation can take before timing out, especially important for large volume schedules. Default 4h
      defaultItemOperationTimeout:
      # How long to wait by default before backups can be garbage collected. Default: 72h
      defaultBackupTTL:
      # Name of the default volume snapshot location.
      defaultVolumeSnapshotLocations:
      # `velero server` default: empty
      disableControllers:
      # `velero server` default: false
      disableInformerCache: false
      # `velero server` default: 1h
      garbageCollectionFrequency:
      # `velero server` default: 1
      itemBlockWorkerCount:
      # Set log-format for Velero pod. Default: text. Other option: json.
      logFormat:
      # Set log-level for Velero pod. Default: info. Other options: debug, warning, error, fatal, panic.
      logLevel:
      # The address to expose prometheus metrics. Default: :8085
      metricsAddress:
      # Directory containing Velero plugins. Default: /plugins
      pluginDir:
      # The address to expose the pprof profiler. Default: localhost:6060
      profilerAddress:
      # `velero server` default: false
      restoreOnlyMode:
      # `velero server` default: customresourcedefinitions,namespaces,storageclasses,volumesnapshotclass.snapshot.storage.k8s.io,volumesnapshotcontents.snapshot.storage.k8s.io,volumesnapshots.snapshot.storage.k8s.io,persistentvolumes,persistentvolumeclaims,secrets,configmaps,serviceaccounts,limitranges,pods,replicasets.apps,clusterclasses.cluster.x-k8s.io,clusters.cluster.x-k8s.io,clusterresourcesets.addons.cluster.x-k8s.io
      restoreResourcePriorities:
      # `velero server` default: 1m
      storeValidationFrequency:
      # How long to wait on persistent volumes and namespaces to terminate during a restore before timing out. Default: 10m
      terminatingResourceTimeout:
      # Bool flag to configure Velero server to move data by default for all snapshots supporting data movement. Default: false
      defaultSnapshotMoveData:
      # Comma separated list of velero feature flags. default: empty
      # features: EnableCSI
      features:
      # Configures the timeout for provisioning the volume created from the CSI snapshot. Default: 30m
      dataMoverPrepareTimeout:
      # Resource requests/limits to specify for the repository-maintenance job. Optional.
      # https://velero.io/docs/v1.14/repository-maintenance/#resource-limitation
      repositoryMaintenanceJob:
        # Per-repository resource settings ConfigMap
        # This ConfigMap allows specifying different settings for different repositories
        # See: https://velero.io/docs/main/repository-maintenance/
        repositoryConfigData:
          # Name of the ConfigMap to create. If not provided, will use "velero-repo-maintenance"
          name: "velero-repo-maintenance"
          # Global configuration applied to all repositories
          # This configuration is used when no specific repository configuration is found
          # global:
          #   podResources:
          #     cpuRequest: "100m"
          #     cpuLimit: "200m"
          #     memoryRequest: "100Mi"
          #     memoryLimit: "200Mi"
          #   keepLatestMaintenanceJobs: 1
          #   loadAffinity:
          #     - nodeSelector:
          #         matchExpressions:
          #           - key: "cloud.google.com/machine-family"
          #             operator: "In"
          #             values: ["e2"]
          #     - nodeSelector:
          #         matchExpressions:
          #           - key: "topology.kubernetes.io/zone"
          #             operator: "In"
          #             values: ["us-central1-a", "us-central1-b", "us-central1-c"]
          #   priorityClassName: "low-priority"  # Note: priorityClassName is only supported in global configuration
          global:
            keepLatestMaintenanceJobs: 3
          # Repository-specific configurations
          # Repository keys are formed as: "{namespace}-{storageLocation}-{repositoryType}"
          # For example: "default-default-kopia" or "prod-s3-backup-kopia"
          # Note: priorityClassName is NOT supported in repository-specific configurations
          # repositories:
          #   "kibishii-default-kopia":
          #     podResources:
          #       cpuRequest: "200m"
          #       cpuLimit: "400m"
          #       memoryRequest: "200Mi"
          #       memoryLimit: "400Mi"
          #     keepLatestMaintenanceJobs: 2
          repositories: {}
      # `velero server` default: velero
      namespace:
      # additional command-line arguments that will be passed to the `velero server`
      # e.g.: extraArgs: ["--foo=bar"]
      extraArgs: []

      # Additional values to be used as environment variables. Optional.
      extraEnvVars: []
        # Simple value
        # - name: SIMPLE_VAR
        #   value: "simple-value"

        # FieldRef example
        # - name: MY_POD_LABEL
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: metadata.labels['my_label']

      # Set true for backup all pod volumes without having to apply annotation on the pod when used file system backup Default: false.
      defaultVolumesToFsBackup:

      # How often repository maintain is run for repositories by default.
      defaultRepoMaintainFrequency:

    ##
    ## End of backup/snapshot location settings.
    ##


    ##
    ## Settings for additional Velero resources.
    ##

    rbac:
      # Whether to create the Velero role and role binding to give all permissions to the namespace to Velero.
      create: true
      # Whether to create the cluster role binding to give administrator permissions to Velero
      clusterAdministrator: true
      # Name of the ClusterRole.
      clusterAdministratorName: cluster-admin

    # Information about the Kubernetes service account Velero uses.
    serviceAccount:
      server:
        create: true
        name:
        annotations:
        labels:
        imagePullSecrets: []
        # - registrySecretName
        # Configure if API credential for Service Account is automounted.
        automountServiceAccountToken: true

    # Info about the secret to be used by the Velero deployment, which
    # should contain credentials for the cloud provider IAM account you've
    # set up for Velero.
    credentials:
      # Whether a secret should be used. Set to false if, for examples:
      # - using kube2iam or kiam to provide AWS IAM credentials instead of providing the key file. (AWS only)
      # - using workload identity instead of providing the key file. (Azure/GCP only)
      useSecret: true
      # Name of the secret to create if `useSecret` is true and `existingSecret` is empty
      name:
      # Name of a pre-existing secret (if any) in the Velero namespace
      # that should be used to get IAM account credentials. Optional.
      existingSecret:
      # Data to be stored in the Velero secret, if `useSecret` is true and `existingSecret` is empty.
      # As of the current Velero release, Velero only uses one secret key/value at a time.
      # The key must be named `cloud`, and the value corresponds to the entire content of your IAM credentials file.
      # Note that the format will be different for different providers, please check their documentation.
      # Here is a list of documentation for plugins maintained by the Velero team:
      # [AWS] https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/main/README.md
      # [GCP] https://github.com/vmware-tanzu/velero-plugin-for-gcp/blob/main/README.md
      # [Azure] https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/blob/main/README.md
      secretContents: {}
      #  cloud: |
      #    [default]
      #    aws_access_key_id=<REDACTED>
      #    aws_secret_access_key=<REDACTED>
      # additional key/value pairs to be used as environment variables such as "DIGITALOCEAN_TOKEN: <your-key>". Values will be stored in the secret.
      extraEnvVars: {}
      # Name of a pre-existing secret (if any) in the Velero namespace
      # that will be used to load environment variables into velero and node-agent.
      # Secret should be in format - https://kubernetes.io/docs/concepts/configuration/secret/#use-case-as-container-environment-variables
      extraSecretRef: ""

    # Whether to create backupstoragelocation crd, if false => do not create a default backup location
    backupsEnabled: true
    # Whether to create volumesnapshotlocation crd, if false => disable snapshot feature
    snapshotsEnabled: true

    # Whether to deploy the node-agent daemonset.
    deployNodeAgent: false