apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
      interval: 5m
  values:
    
    configuration:
      backupStorageLocation:
      - name: "minio"
        provider: "aws"
        bucket: "velero"
        # default indicates this location is the default backup storage location. Optional.
        default: true
        credential:
          # name of the secret used by this backupStorageLocation.
          name: minio-credentials
          # name of key that contains the secret data to be used.
          key:
        # Additional provider-specific configuration. See link above
        # for details of required/optional fields for your provider.
        config: 
         region: minio
         s3ForcePathStyle: true
         s3Url: "http://nas:9001"