repositories:
- name: plex
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages

- name: plex
  namespace: plex
  chart: plex/plex-media-server
  values: 
    - ingress:
        enabled: true
        ingressClassName: nginx
        url: "plex.almothana.xyz"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
      pms:
        configStorage: 10Gi
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      extraEnv:
        TZ: "Asia/Riyadh"