repositories:
- name: longhorn 
  url: https://charts.longhorn.io
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx 
- name: mojo2600
  url: https://mojo2600.github.io/pihole-kubernetes/
- name: plex
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
- name: bitnami 
  url:  https://charts.bitnami.com/bitnami
- name: nextcloud 
  url:  https://nextcloud.github.io/helm/
- name: jetstack
  url: https://charts.jetstack.io
- name: emberstack 
  url: https://emberstack.github.io/helm-charts
- name: kubecost 
  url: https://kubecost.github.io/cost-analyzer

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx 
# make default class ingressclass.kubernetes.io/is-default-class: "true"

- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  createNamespace: False
  version: "1.7.2"
  values:
    - longhornUI: 
        replicas: 1
      ingress:
        enabled: true
        tls: true
        tlsSecret: almothana-xyz-tls
        ingressClassName: nginx
        host: longhorn.almothana.xyz

- name: prometheus
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: "68.2.1"
  values:
    - grafana:
        defaultDashboardsTimezone: Asia/Riyadh
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - grafana.almothana.xyz
          tls:
            - secretName: almothana-xyz-tls
              hosts:
              - grafana.almothana.xyz
        persistence:
          enabled: true
          type: sts
          accessModes:
            - ReadWriteOnce
          size: 5Gi
          finalizers:
            - kubernetes.io/pvc-protection
      prometheus:
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - prometheus.almothana.xyz
          tls:
            - secretName: almothana-xyz-tls
              hosts:
              - prometheus.almothana.xyz
        prometheusSpec:
            storageSpec: 
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi

- name: pihole
  namespace: pihole
  chart: mojo2600/pihole
  version: "2.27.0"
  values: 
    - ingress:
        enabled: true
        ingressClassName: nginx
        hosts: 
          - pi-hole.almothana.xyz
        tls:
          - secretName: almothana-xyz-tls
            hosts:
            - pi-hole.almothana.xyz
      serviceDns:
        mixedService: true
        externalTrafficPolicy: Cluster
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.8.252
        type: LoadBalancer
      resources:
        limits:
          cpu: 300m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      persistentVolumeClaim:
        enabled: true
      extraEnvVars:
        TZ: "Asia/Riyadh"

- name: plex
  namespace: plex
  chart: plex/plex-media-server
  values: 
    - ingress:
        enabled: true
        ingressClassName: nginx
        url: "plex.almothana.xyz"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
      pms:
        configStorage: 10Gi
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      extraEnv:
        TZ: "Asia/Riyadh"

- name: external-dns
  namespace: external-dns
  chart: bitnami/external-dns
  version: "8.6.1"
  values: 
    - provider: pihole
      pihole:
        server: "http://pihole-web.pihole.svc.cluster.local"
        secretName: "external-dns"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 50Mi
        limits:
          cpu: 150m
          memory: 192Mi
          ephemeral-storage: 2Gi

- name: nextcloud
  namespace: nextcloud
  chart: nextcloud/nextcloud
  version: "6.6.3"
  values:
    - ingress:
        enabled: true
        className: nginx
        tls:
          - secretName: almothana-xyz-tls
            hosts:
            - nextcloud.almothana.xyz
      nextcloud:
        host:  nextcloud.almothana.xyz
        trustedDomains: 
        - "nextcloud.almothana.xyz"
        - "nextcloud.cloudforest-sargas.ts.net"
        - "nextcloud"
      persistence:
        enabled: true
        accessMode: ReadWriteMany
        size: 8Gi
        nextcloudData:
          enabled: true
          accessMode: ReadWriteMany
          size: 8Gi  
      livenessProbe:
        initialDelaySeconds: 1800
      resources:
        limits:
         cpu: 1
         memory: 1Gi
        requests:
         cpu: 100m
         memory: 256Mi

- name: cert-manager 
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: "v1.16.2"
  values:
    - crds:
        enabled: true
      extraArgs:
        - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
        - --dns01-recursive-nameservers-only
      podDnsPolicy: None
      podDnsConfig:
        nameservers:
          - 1.1.1.1
          - 9.9.9.9

- name: reflector
  chart: emberstack/reflector
  namespace: kube-system

- name: kubecost
  chart: kubecost/cost-analyzer
  namespace: kubecost
  values:
    - kubecostToken: "aGVsbUBrdWJlY29zdC5jb20=xm343yadf98"
      ingress:
        enabled: true
        className: nginx
        hosts: 
          - cost-analyzer.almothana.xyz
        tls:
          - secretName: almothana-xyz-tls
            hosts:
            - cost-analyzer.almothana.xyz