repositories:
- name: longhorn 
  url: https://charts.longhorn.io
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx 
- name: mojo2600
  url: https://mojo2600.github.io/pihole-kubernetes/
- name: plex
  url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
- name: bitnami 
  url:  https://charts.bitnami.com/bitnami
- name: nextcloud 
  url:  https://nextcloud.github.io/helm/

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx 

- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  createNamespace: False
  version: "1.7.2"
  values:
    - longhornUI: 
        replicas: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        host: longhorn.home.lab

- name: prometheus
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: "66.3.0"
  values:
    - grafana:
        defaultDashboardsTimezone: Asia/Riyadh
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts: 
            - grafana.home.lab
        persistence:
          enabled: true
          type: sts
          accessModes:
            - ReadWriteOnce
          size: 5Gi
          finalizers:
            - kubernetes.io/pvc-protection
      prometheus:
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - prometheus.home.lab
        prometheusSpec:
            storageSpec: 
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi

- name: pihole
  namespace: pihole
  chart: mojo2600/pihole
  values: 
    - ingress:
        enabled: true
        ingressClassName: nginx
        hosts: 
          - pi-hole.home.lab
      serviceDns:
        loadBalancerIP: 192.168.8.252
        annotations:
          metallb.universe.tf/allow-shared-ip: pihole-svc
        type: LoadBalancer
      resources:
        limits:
          cpu: 300m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      persistentVolumeClaim:
        enabled: true
      extraEnvVars:
        TZ: "Asia/Riyadh"

- name: plex
  namespace: plex
  chart: plex/plex-media-server
  values: 
    - ingress:
        enabled: true
        ingressClassName: nginx
        url: "plex.home.lab"
      pms:
        configStorage: 10Gi
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      extraEnv:
        TZ: "Asia/Riyadh"

- name: external-dns
  namespace: external-dns
  chart: bitnami/external-dns
  version: "8.6.1"
  values: 
    - provider: pihole
      pihole:
        server: "http://pihole-web.pihole.svc.cluster.local"
        secretName: "external-dns"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 50Mi
        limits:
          cpu: 150m
          memory: 192Mi
          ephemeral-storage: 2Gi

- name: nextcloud
  namespace: nextcloud
  chart: nextcloud/nextcloud
  version: "6.3.0"
  values:
    - ingress:
        enabled: true
        className: nginx
      nextcloud:
        host:  nextcloud.home.lab
        trustedDomains: ["nextcloud.home.lab"]
      persistence:
        enabled: true
        accessMode: ReadWriteMany
        size: 8Gi
        nextcloudData:
          enabled: true
          accessMode: ReadWriteMany
          size: 8Gi  
      resources:
        limits:
         cpu: 1
         memory: 1Gi
        requests:
         cpu: 100m
         memory: 256Mi