apiVersion: v1
kind: Secret
metadata:
    name: homelable
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:a/isY2B9NO+5zfZ68jec+p04xniscTo/u6ygLeMLrmF0Ya5XtBvwyJRl85zLzG0FgIr/9DvJYm1YIMU8a61EtA==,iv:+TKcUkt7HHEGsgBiymRe7BhuE13OpIvGIsUdxBz3XOM=,tag:8/QLzxqx68C89rcV5EvhiQ==,type:str]
    OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:DalEyaKHz36k0xTd8JavrjXdC/hSi3xBA48qOkpX4fMHtd1pHiDNFmaLRMiJoJqNozftKwTPz2O9+lk5tih9WyMH+qT3I6m1k5X3rEAJOSMy,iv:KzBEtElQlaQI+ooD8TYSKIgodP2E56LaRZBpmS7peXA=,tag:UcMKTb+XEdvpP1BMfF8v5A==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:65kDJUYsKbhVC8s8YHTaqpmdOuZZqeDDMp3vFxDRNv3c1LJVuzqXtg==,iv:JuhUMX7j/ZWT1GaorM8Eb9QHtHPjqOxvDXqxTY5C6MM=,tag:4yBP0iTTqLSDePQFdaIAZQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ynUJ+nwQAUPv7l+xsuc1IdxIr9IO1x8Lq5TGmfeO22rfuEMxB3LVxndce+VcOTFYT0aQH7xpOPGCaIpl/slvye96UaaMkUUp3IFN8BYEJj51TcAmiQds0DwodFtgGzFT2tItfRMzOtNPCV0rSX1ocpbJtfMYULFu5ERY3cK23Co=,iv:P8VQbSSjEL3kBdPkz8W+oPPrexyyfz7UXBrSKh6+76g=,tag:NDxuoS51IMyh6KbeRo4fhA==,type:str]
    OIDC_REDIRECT_URI: ENC[AES256_GCM,data:OJJt0m91Lbro6vQP+JR4Nblqi9QSlth/JIoGvOfH5YyJoSEQD8ABOPHKe1kwDA2oDNm5UMcc7PdD,iv:IEozrrv15q+OAv3/XYl4hzfpYaGznsKmVFOpKty2PzQ=,tag:r4K8S43iWJ5tJS9uBv6uFg==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:Ivf19QZ+mTxQvsYw346NheY+BBo=,iv:QvBG0N1M8UxpSZZgmsZpdyU/wzP4iSiRx50JHA3keOI=,tag:OpWL2Tu7iBDDxvOeD5+1gg==,type:str]
    OIDC_COOKIE_SECURE: ENC[AES256_GCM,data:8jaTTA==,iv:flFH+lCtjqjkiHbSWISYjTcnM/aZliZSv38J/f5Upd0=,tag:PIo2jgllIRUOwZDUn/h/VQ==,type:str]
    OIDC_SESSION_EXPIRE_MINUTES: ENC[AES256_GCM,data:Hzj/,iv:SJVtI4e/BCr+7pjdS8LpTVbSb9YxD/qQ8eAbaqmzZlI=,tag:FlCvjclNClAMsEoRf29VWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWFllamRXbnNzRlZYUTkx
            ZmpNakdudjBFZisxVE0rTTBTeml5Y0ZMKzNFCmZMOFVremE1ak5oZ1A2YUR1TW83
            c25IdXBiRThpOEVaRllTRld4c2NNUnMKLS0tIGw5c2lYelpJWVl3YWo3T3BSeVlq
            WVBBZ2xHL0hSZS8vTFNTMkVGV3gxWDAK+puIQrb/X+jJ2qEtL8BoFZWMdo7obPaO
            W1U9OYLJnuBwW4YwoozxtHZ9G1JFE2FAyLNroGGz3RUPCKIjh5emtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T16:31:31Z"
    mac: ENC[AES256_GCM,data:nPWO3a4jeIrovSTAEuPO7DnWHgZr+9yRp7/f8lnghiKhKVLN8Sf39MuQBAOnwtFeFFmXLeZq9+GicyQJU4PKjPVhspX8isV0huJG6eZk2vyYs/iWyLeIiRAczyWMEcPS5YlfBjueo/9L7kgQPQHMhDZpVQTZHtIo/OYEu8PvrEo=,iv:IpLwKXXmUgrSrRJ1t5sdocXc2g1vjbpV9KIqre0MtzA=,tag:LpXFnsVZIpP75f8Jdn7TFQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
