apiVersion: v1
kind: Secret
metadata:
    name: llm-credentials-opencode
stringData:
    provider-config: ENC[AES256_GCM,data:X9vPH7eheJymEi34j+jA8pv1aVv+zPI2OLMKi+aal/e3evlnNF5lmyEK3t5VBZAO+nlEGMOP76O6B/w1h1/jw4PvhHBdGyie+fkDOZnGIVZ/OXSbuwq3BBVZa0/bV+yN6hfpLAXf7TK6XzoYX0blEHC/HgDqc2du+cvOj5g4RIjvEt4exFGOuORGeBhPxVPIISGkxHC9yys7+d+WlDYZx/vYueUPcL4NipJDHzJ3U7hSvPJd1AZxlOVOzpqBpOY1rPYdj53urLy0e3xySiEGn/xv6oYNy+7wE2y0hEzy4jNJ6BmyTzUzQj/OC8G/ALQJpLKebrWvhy8SkWQT9L3N8t53agejg1W6Bvxr4gAOdfIjEfT50LoIKkxrjyxg7Y2dsn+0APxhkkhGokKj+4Fw3K974afpSy76tshVtv/yRzKatjAWfcgORWhCkj6tRHlnLFaX1DYl+x8NaUI6FNdEBFskKX1SkZLmW6+i8FGDlpvDKk/dqUcdf9h/jvF/FnUtYQL1erMpznqJEcev4oIKhxLkUDxCID6yKfs7P4FcN2Q7TSAWg6eSY6xm96fKkXY8HhKMgw==,iv:1J7+wcsTstTXBYFNdSemcsMzRHAyOvQGRISCOk+Qqhw=,tag:4nIKjSRFmKb1Qp3TxWng3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdytPVFRkSURtWU5GZitY
            aEh4VEMzTjAwZTJSV0NRb25KSjU1b0pMQzEwCklhZ3ZvVm10SVlrVElrdHR1ZEdU
            VnN6bC9zOGdxK2ZtdE9zckVBa3VHVTQKLS0tIHhzV1VNaHFLQnlyQXN4UGZtOFhD
            L3B4SmMyemJsNXFNRU1uRUhSODN2VlkKBiPVBSrYdJ9eUllqCouBc/tI3xt60TEH
            5uU9qMwmhRHtXIe6+KA4re7rbkBKhB3FQ+27pn3L0w2I09RYdAL5yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T12:10:18Z"
    mac: ENC[AES256_GCM,data:xSqJfpCHfXeesXarngrBgyd5Bk/eZvRAdEHDs74PMpvAes/nu0fI37rgqT6hgepkWPqNjLGTlLmpcVtwV+bohXotps/23BQ1ZTjdCHHBO17OJtNj4NzVc0x+i/dE24PNCnJQZJ1aH7cp5dt/871IZ5I1IIQTgcTXzlYiTTV4lmk=,iv:yBVb9UJVUv+npkiWd5kQ9DS0PCYN68rweghqsSsQIMw=,tag:2ey6xr2c5O0+kVsQAiy+XQ==,type:str]
    pgp: []
    encrypted_regex: provider-config
    version: 3.9.1
