apiVersion: v1
kind: Secret
metadata:
    name: llm-credentials-opencode
stringData:
    provider-config: ENC[AES256_GCM,data:JwACrM3RXLEh3Q6fZHHrsIqsWapzU4WZYsiUC/mMsm8VVrEN9Qt0hLAcH9HU3UCC/1QtYPBQ6jopTXXUxvjd/Nv1+PK0YOydaOo9aRjzzRKi6j5GEWhh4vuThR2199TZRxx8uvaU9UZB8o7tWWXCMH5e21L/jOm3/D71UU3FXefynNs1b2Ob9qg1gxb9CW0g76MRp1sPN7QxvWHmG6HB14Zd991WjeCserXpfbjaXxHj1n7xPKe76ubB8DP5ZcgKC2X3Z4bBiNCShCHAWuE4HWfZWneZ8bJF15wSEEi0GqJImETNmd5XihRxrVb8o1udbiyUE2FGsR77G6l0mGQc3GZ/vzAv5I7eAz+v28GAicWmmw6SRIgC8EZUzPRlV+YEhkMjivQmEvUETBjoD0IFG2HJgDZx5HzBi48lheTz11LMsELDncH5PyfPSadE6WjyPjHwEeN3AEZIsr1mF9zJM046VVTczg/jweKk3/aMbws1LU4/L6kJMV8SZVzKRUoAbK6P/Jd3/Pn37yfZqmaxnk6PjzfwyqwE3kShFwgjJXjhyW9Xr+k9uAdDqfv3Lyl4Lcc8/xk=,iv:t8PDtSU9z5cZnOE952ZWAcc/swkzoFFUmUAyrTsAXIc=,tag:AZb/gHl2iOk6FR8cauP++w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdytPVFRkSURtWU5GZitY
            aEh4VEMzTjAwZTJSV0NRb25KSjU1b0pMQzEwCklhZ3ZvVm10SVlrVElrdHR1ZEdU
            VnN6bC9zOGdxK2ZtdE9zckVBa3VHVTQKLS0tIHhzV1VNaHFLQnlyQXN4UGZtOFhD
            L3B4SmMyemJsNXFNRU1uRUhSODN2VlkKBiPVBSrYdJ9eUllqCouBc/tI3xt60TEH
            5uU9qMwmhRHtXIe6+KA4re7rbkBKhB3FQ+27pn3L0w2I09RYdAL5yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T10:01:18Z"
    mac: ENC[AES256_GCM,data:oHoc3s7f8/AZg8cXYZYgnzqwOY9GgQB26oelZfZzNXDYjtGDmnaYidWanDHvEZ35BBB5EQJ+JfF9ohLwNiDF0qYq4dXb/GWYhgjLAs+DQ48y0SwvBIKO+Q5uZ2GYX540UqgkhU+MoGtiGB7SievJqfbdKG+7nFvy9+kx4I7KgyE=,iv:JNhWtPSBUb2O4srzlTyZR1Wq8x3kofoR3Osp85Q7zMk=,tag:I0lvAHy2yAQ5iXX6vaLWrw==,type:str]
    pgp: []
    encrypted_regex: provider-config
    version: 3.9.1
