apiVersion: v1
kind: Secret
metadata:
    name: llm-credentials-opencode
stringData:
    provider-config: ENC[AES256_GCM,data:LE1NJwv8xPuUP4y7bceEmJZAdA8S+budOlbkwfrBqlof7m70gTeWI/MV0qaUdHUF49jULmnK/f3sQKkliwJEKVdK5LyQBURBwZBEL5TjuJF7FAFP3MOCif7g4XSmopfSVLU1TbqOJQZRhQpAJ4UpR2ZAU+FGNeK0NPVRqbCGog4z0p8c6KIbkdQO8jAwHOnDRvRGKBEbGsS5kEU96rPcnug3Dh9PxakJsstR+J2rZg6A1duI7QSgdi6J7qcOKwbR+EthlgW3TXWGAFKIhxPjXGIM5jOhQI11nWAB5Kq50JgiuWJt333hW5qRSdyOVPbFFQk3UwYeG4FYaoUdUYBj8G7P3ww4dUU6OgZyU0AE4v6sTmqA1/ncz3sw0rklYAHoZmLXqatJCEqwlGy84ZsF5LZuXvivmsZC5Opcq0J7qCTr+v8re0hiUmueR7sTXWyehE3djVZUjjbNK6e4brGjPEjOjGBXo5wy/cO9eaoxO6Si5qouGLcdEl14BBCZHkyaP6blsgYdfeVm1yDlSaimLxuzLthBVS5On/59JJXKEBbZMWE=,iv:DEHUnhwM3y2SjRoENto9PaPFzBa+JgzMCzFYMti/HLk=,tag:eJnIgXWkP5Su6cGPXwUMOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdytPVFRkSURtWU5GZitY
            aEh4VEMzTjAwZTJSV0NRb25KSjU1b0pMQzEwCklhZ3ZvVm10SVlrVElrdHR1ZEdU
            VnN6bC9zOGdxK2ZtdE9zckVBa3VHVTQKLS0tIHhzV1VNaHFLQnlyQXN4UGZtOFhD
            L3B4SmMyemJsNXFNRU1uRUhSODN2VlkKBiPVBSrYdJ9eUllqCouBc/tI3xt60TEH
            5uU9qMwmhRHtXIe6+KA4re7rbkBKhB3FQ+27pn3L0w2I09RYdAL5yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T12:21:07Z"
    mac: ENC[AES256_GCM,data:osa8ZcoaX3LyUV793SBQDrsRKroaLg9bZj074FsLtpPAv4xwIURc/ZZ0eiEWlTou2hLlRfq82Avit4J/ky5ryi8JAmvaAIvuYWptOhN82K56EAmqplprukpUhx0yY9/g7w/G5Mnju50QA+98s1s6H6zltdFdG1tOEPWnPo0H2e8=,iv:0OO0irA1/3h1euTgZE0ZG81vddgnyTimW20PqI6+uJs=,tag:ILL6ptWt8/fPWtVg5x6azA==,type:str]
    pgp: []
    encrypted_regex: provider-config
    version: 3.9.1
