apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubetail
spec:
  interval: 5m
  chart:
    spec:
      chart: kubetail
      version: '0.26.0'
      sourceRef:
        kind: HelmRepository
        name: kubetail
      interval: 5m
  values: 
    kubetail:
      dashboard:
        enabled: true
        runtimeConfig:
          session:
            cookie:
              name: __Host-session
              secure: true
          allowedOrigins:
            - https://kubetail.almothana.xyz
        ingress:
          enabled: true
          className: cilium
          rules:
            - host: kubetail.almothana.xyz
              http:
                paths:
                  - backend:
                      service:
                        name: kubetail
                        port:
                          number: 8080
                    path: /
                    pathType: Prefix
          tls:
            - hosts:
                - kubetail.almothana.xyz
              secretName: almothana-xyz-tls