apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: newt
spec:
  endpointSelector: {}
  # explicit deny to be safe
  egressDeny:
    - toEntities:
        - ingress
        - host
        - remote-node
        - kube-apiserver
  egress:
    # To DNS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    # To Pangolin
    - toFQDNs:
        - matchName: pangolin.almothana.sa
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "51820"
              protocol: UDP
            - port: "21820"
              protocol: UDP
    # To FreshRSS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: freshrss
            k8s:app: freshrss
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    # To Authentik
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: authentik
            k8s:app.kubernetes.io/component: server
      toPorts:
        - ports:
            - port: "9000"
              protocol: TCP
    # To Audiobookshelf
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: plex
            k8s:app: audiobookshelf
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    # To oCIS
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: ocis
            k8s:app: proxy
      toPorts:
        - ports:
            - port: "9200"
              protocol: TCP
    # To XorMon
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: xormon
            k8s:app: xormon
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
    # To Grafana
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            k8s:app.kubernetes.io/name: grafana
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
    # To Open Web-UI
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: open-webui
            k8s:app.kubernetes.io/name: open-webui
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    # To RomM
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: emulation
            k8s:app: romm
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP