apiVersion: v1
kind: Secret
metadata:
    name: newt-main-tunnel-auth
stringData:
    NEWT_ID: ENC[AES256_GCM,data:mOfq0057RMy6qXuNXi4B,iv:NDlrd3FBAUsJeA1ON6+inTNg5/fpABbXVQsrfISv5g4=,tag:aZeC7rKOzQs6EB0C1pdWHw==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:iIWX4hEO1Q8o6PEPvdjuzVTaucjXpyj0bF4NubqAhEsvyOAxDicH3A1kXhipohV2,iv:bv5b/bSugs5FiEYL1aPCfGV4ciD9f66mmDa0EsppQMI=,tag:kpv2YRwHn3ob9Hk8gBYALQ==,type:str]
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:crJ/2E6CS9/8fyuUWuWgf0nlWk3UPLYQTp+dvvM=,iv:mmkdg9cjeZ3jIWcZ0XM1Rc09xy+pYicGt2NeEA0pfro=,tag:o6DUqBckZpbV46iDDroXpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSVE1b3NIaUZBa05YZitZ
            aEM2R2lVblh4T3pCVk5ZZnpDWU83VmNoZlZBCmtnOVNsSWxlTU9vQ3RoQUFEUHRM
            YmFSTjJ1a3hpaFhZYVZHTlh0WkRNdmMKLS0tIFNWUExFYWRUR1JJSnhlSmIxR2FN
            aUlTYTVnZ1B4ODA5WXBOZ3pOVGJsT0UKVsCBX28HXzH2uz7fKWbTaq/cEgiGbmo+
            ywUC9HZlgEaZ447HuhZN2CSmild6TXp4BwahEXe9qp3zyVPuQKejpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T14:56:40Z"
    mac: ENC[AES256_GCM,data:JDnCri9gLdPhK54JM6VjcdXGJBODsz8dZDuLOOGY6icvNlvvtcXtW94CbPc2LwnBowQ1WjO3hnsg9OZ9hgMf7bNmE8UZQRzTextOv69jEVVGKoyPkzvR2176wK0KjPhjKzr9hm0DpAdJYOfl9qBF9e4ICcTFjtfxLxvIs9G6U40=,iv:U0WStMmEQ9nKC0FZYRAtLZkeMVj9rChM0dMbuzsegkk=,tag:2UHqV4sDXInvWSDeRiGiCg==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
