apiVersion: v1
kind: Secret
metadata:
    name: newt-main-tunnel-auth
stringData:
    NEWT_ID: ENC[AES256_GCM,data:eP1FlJHoffX5AJgfWpD+,iv:zOPQa8FkyxMm185MaKZhIWiSJEp23zty1oYY9CxvQps=,tag:vcbmq+wZGdYsUvh3936lrg==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:oN2XNwRx5/wl8CPEg3jXLhIo2BN7gtYr8qLAzRJE8V6efU2O2+4BoO00A7AXSJC4,iv:RjLFpArJiehkb1xc22pigaTQEhP3+R/B6iLr1+EkOJ4=,tag:s6sHdfw9XBrPqb6sd1DqvQ==,type:str]
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:crJ/2E6CS9/8fyuUWuWgf0nlWk3UPLYQTp+dvvM=,iv:mmkdg9cjeZ3jIWcZ0XM1Rc09xy+pYicGt2NeEA0pfro=,tag:o6DUqBckZpbV46iDDroXpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSVE1b3NIaUZBa05YZitZ
            aEM2R2lVblh4T3pCVk5ZZnpDWU83VmNoZlZBCmtnOVNsSWxlTU9vQ3RoQUFEUHRM
            YmFSTjJ1a3hpaFhZYVZHTlh0WkRNdmMKLS0tIFNWUExFYWRUR1JJSnhlSmIxR2FN
            aUlTYTVnZ1B4ODA5WXBOZ3pOVGJsT0UKVsCBX28HXzH2uz7fKWbTaq/cEgiGbmo+
            ywUC9HZlgEaZ447HuhZN2CSmild6TXp4BwahEXe9qp3zyVPuQKejpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T14:53:07Z"
    mac: ENC[AES256_GCM,data:j5Xhl3B7EVm/bwq2OuMCUvet4dBkRhDF8adpk2oJ78mFNqKU21NQ4YHzCEeVUsZjasGh1ZTvPCKAZpwt7uN6B7238Xsu39Uc5kFjN00vQEBAxLEBKqztyTRTfHdHJgvH62M3/xrYu0EXuP68v2zxBsCFNSdAGK32Jd5peDlvYeM=,iv:foUHdGwBa57+sWTZwsSBmYweR8U02lqmo6rslbQKZA8=,tag:if4ofNmYyMhY4ViKXK1J+Q==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
