apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 24h
  chart:
    spec:
      chart: longhorn
      version: '1.7.2'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 24h
  values:
      longhornUI: 
        replicas: 1
      ingress:
        enabled: true
        tls: true
        tlsSecret: almothana-xyz-tls
        ingressClassName: nginx
        host: longhorn.almothana.xyz
      defaultSettings:
        backupTarget: 'nfs://192.168.8.109:/volume1/longhorn-backup'