apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '70.2.1'
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 5m
  values: 
    grafana:
      defaultDashboardsTimezone: Asia/Riyadh
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.almothana.xyz
        tls:
          - secretName: almothana-xyz-tls
            hosts:
            - grafana.almothana.xyz
      persistence:
        enabled: true
        type: sts
        accessModes:
          - ReadWriteOnce
        size: 5Gi
        finalizers:
          - kubernetes.io/pvc-protection
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.almothana.xyz
        tls:
          - secretName: almothana-xyz-tls
            hosts:
            - prometheus.almothana.xyz
      prometheusSpec:
        # set as false to use the rules in the PrometheusRule resources (https://github.com/onzack/grafana-dashboards/tree/main?tab=readme-ov-file#troubleshooting)
        ruleSelectorNilUsesHelmValues: false
        storageSpec: 
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi