apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '87.19.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 5m
  values: 
    crds:
      # enable installing and upgrading CRDs
      enabled: true
      upgradeJob:
        enabled: true
        forceConflicts: true
    grafana:
      defaultDashboardsTimezone: Asia/Riyadh
      envFromSecret: grafana-env
      env:
        # SSO
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email entitlements
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://sso.almothana.sa/application/o/authorize/
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://sso.almothana.sa/application/o/token/
        GF_AUTH_GENERIC_OAUTH_API_URL: https://sso.almothana.sa/application/o/userinfo/
        GF_AUTH_SIGNOUT_REDIRECT_URL: https://sso.almothana.sa/application/o/grafana/end-session/

        # Map Authentik groups to Grafana roles.
        GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: groups
        GF_AUTH_GENERIC_OAUTH_ALLOWED_GROUPS: "k8s-admins k8s-users"
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: >-
          contains(groups[*], 'k8s-admins') && 'GrafanaAdmin' ||
          contains(groups[*], 'k8s-users') && 'Editor' ||
          'Viewer'
        GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: "true"
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT: "true"
        # bypasses Grafana login screen
        GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: "true"
        # Required if Grafana is running behind a reverse proxy
        GF_SERVER_ROOT_URL: https://grafana.almothana.xyz
      # Use an existing secret for the admin user.
      admin:
        ## Name of the secret. Can be templated.
        existingSecret: "grafana-admin"
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: true
        ingressClassName: cilium
        hosts:
          - grafana.almothana.xyz
        tls:
          - secretName: almothana-xyz-tls
            hosts:
            - grafana.almothana.xyz
      persistence:
        enabled: true
        type: sts
        accessModes:
          - ReadWriteOnce
        size: 5Gi
        finalizers:
          - kubernetes.io/pvc-protection
    prometheus:
      ingress:
        enabled: false # using Authentik outpost
      prometheusSpec:
        # set as false to use the rules in the PrometheusRule resources (https://github.com/onzack/grafana-dashboards/tree/main?tab=readme-ov-file#troubleshooting)
        ruleSelectorNilUsesHelmValues: false
        # testing for CNPG issues: https://github.com/cloudnative-pg/charts/issues/279#issuecomment-2130308807
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        # configure remote write to the Openobserve instance
        # remoteWrite:
        #   - url: https://openobserve.almothana.xyz/api/default/prometheus/api/v1/write
        #     name: openobserve
        #     queueConfig:
        #       maxSamplesPerSend: 1000
        #     basicAuth:
        #       username:
        #         name: openobserve-remote-write
        #         key: username
        #       password:
        #         name: openobserve-remote-write
        #         key: password
        storageSpec: 
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
    alertmanager:
      alertmanagerSpec:
        secrets:
          - smtp-secret
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
      config:
        global:
          resolve_timeout: 5m
          smtp_smarthost: 'mail.almothana.sa:587'
          smtp_from: 'no-reply@almothana.sa'
          smtp_auth_username: 'no-reply@almothana.sa'
          smtp_auth_password_file: /etc/alertmanager/secrets/smtp-secret/password
          smtp_require_tls: true
        route:
          group_by: ['namespace', 'alertname']
          group_wait: 2m
          group_interval: 10m
          repeat_interval: 48h
          receiver: 'email'
          routes:
            - receiver: 'null'
              matchers:
                - alertname =~ "InfoInhibitor|Watchdog"
            - receiver: 'email'
              matchers:
                - severity = 'critical'
        receivers:
        - name: "null"
        - name: 'email'
          email_configs:
          - to: 'alerting@almothana.sa'
            send_resolved: true

