apiVersion: v1
kind: Secret
metadata:
    name: openobserve-remote-write
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:yQFjTTdNGxURtidL0xRXptKcqhIHlbw=,iv:03pxS8vFNs4xsP/bfoSVyafljLyzixgUOLe1mejjUkk=,tag:ZjLe+HeuuOZYW8ZTtVI+qA==,type:str]
    password: ENC[AES256_GCM,data:c2HgOZL4ZPNTlgmykh0YNw==,iv:3i0NmEV5gTsbPlYEaMBDGqfinB8IdSzScNG7lLsGces=,tag:ip1TPKHF+vaN2tQvdQDCLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bHRpaUV4ZElKZkt4b1VW
            Snh4eU1CRnhvYmlqR293TUxRUVBia2lXQXlZCkxxdGNSRjBLdGEydnQ4T2FGZ3hs
            QmJUYVRYME5PL2hNbnlzN3ppZDU5VjAKLS0tICtvVFl4bUxHTk1wTlArV0pLdmpI
            Q3lEamk4MGM5b0FtNzkvdEhzTGpSL00KUCCO5UURHpZvtq9rottG1WCt+Sb4Qeoc
            KpmXuN/oRA2vZNXb476097gJlTTgevZHslTTngRZEEvzvSLW2Uwvbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T17:02:25Z"
    mac: ENC[AES256_GCM,data:+xSObOd/cSUKipEPLVe6irxheZsmsLUjna1fJqJJyPdsPeo0qWWdPijfAQSuCU5WlUsuyCNdZNywZ12lRtpuGqBdbAtdqDUtZxfBkpXoS17TxcsAabloD7WQnBcOqtl+sAQduZl8obEUZB8vpdx0tQ7H1x7p/do6pOntEgZAIII=,iv:ukuqoH6GtHVW+F1Y/eD9DfkV3EMDuS9GVWJ73N+wJWs=,tag:MkhDKrAVkAYeINwkek1xJg==,type:str]
    pgp: []
    encrypted_regex: username|password
    version: 3.9.1
