apiVersion: v1
kind: Secret
metadata:
    name: smtp-secret
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:5W+RiAVhPhpDsYgKXXdI84415XbczewcLnwaC34JFuMe05K8GBzwRQ==,iv:GxfZhMEAermBxjtni/5YcUUGFhyTU/8aveeTqUdkvI4=,tag:KGANIsb2nIXayEmRvUpZrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VDJGUmN1dFYrMUlRZzhJ
            RUtXK1p0My81VGtYVEdvaUVJQW9Lam9zMFZRCm1QVXdhWk5yUU1nWEdNYTBpcHBn
            c3VJK1lIMzFaRitoWjVjVkU2b0c2SXcKLS0tIGM1UE4rNXdjVFFZb09GdkYzSWta
            SkowaVdRYmE3RjkzK0NtU3p5VTVUNkkKaM9yH8V2ksR8dJwvsrG+BVWUtLs4T6eU
            v+iDLupWaW3ZJIsp32qWyu4ualrBTIGD/SUXLtQreMho7Dw79en+Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T15:47:15Z"
    mac: ENC[AES256_GCM,data:JtHZWIab+CUHWbVK9RISpwqHP1ZtXlLiQApJjGDpUE6RlRoLb+698BHaR33xYf3vkwKcHUkda/bT1gr5O9BosV8SOvFGU6tNBLCQZFphinZKuinx24DlUWKlbN7CyfAgRPZa89SyiyRslGdEU9QCSu0166dg1mwc2Io2ApVqbnk=,iv:9fi1hHQ0bgRR/gRMh1pZX8JJv0D66uSVIX0AZcTdUXE=,tag:qqeAclJIj12scQ/tla2qaA==,type:str]
    pgp: []
    encrypted_regex: password
    version: 3.9.1
