apiVersion: v1
kind: Secret
metadata:
    name: slack-secret
type: Opaque
stringData:
    slack-api-url: ENC[AES256_GCM,data:RpwNlnI2+kJza4lK6e5CWVb1WMuAomnkXXgVPVQl8bi4BrN9XPCv/oz5wxxnl2SK3v8svtg1IW65JuCCKgehrYwjq5sGXm+O/OO9ayv+vS1M,iv:iU3kQAv7rXK05+mBQSSXZy1jJoQ4PZwptBycXylYltg=,tag:o1MaVUE02KTmAF8MvRl2VA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TksybWY4Q0VSZGFVNGZq
            dzByRVBvZU8wcE9aTkFIcWsvTWU3ek1WWGlBCjJaSXc5K0ZOd25Nb1FEd3Y4U1Np
            ZERsNGFXVlUwamRLNENHVXlZTm50MEkKLS0tIERaTWw4bk5XV3g0bHgvb3Z1ZkFG
            UXhjRFVVdktWMm1vZ01PZFQ1Sk4wVzAKFWIvbW8bRYe7q8mhCgH7WkdXnD6Jrpyz
            VseW3521QlLdcb+jur3Aor9MF6pyuLh0aI3KJzXNS3wA5DPelonNYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T15:55:34Z"
    mac: ENC[AES256_GCM,data:scuAbC9EqJrDbCtANoL4MJrxTKKngeM8XThjIqssUPfvpCV9YNtR8W4rcxaF8ZBWGANnnC9XEW8ww3cQajY6SzOpsmzOhPxPL9iNj/mbePHwvVnV18xy2gYSVUsEEwI5B6UHs93uH97LKajwLzI7cVMEnaV1+q1DJ5o/NXiPWKI=,iv:Vidg7LJuKFtGFBjp8fusY7edcySJ4A/1NvONbq7yQd0=,tag:BdJTUJgCfYMD5CCeYcF7xA==,type:str]
    pgp: []
    encrypted_regex: slack-api-url
    version: 3.9.1
