apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_ENABLED: ENC[AES256_GCM,data:rXO+Uw==,iv:viHZYjlQ2laRdwHwCyHc9YXmY8S3vZ50lBQ7L7AwhP4=,tag:KY1Z9MMzeEcwtRnH/6KIUw==,type:str]
    GF_AUTH_GENERIC_OAUTH_NAME: ENC[AES256_GCM,data:vjmlStEzUQcd,iv:a4xShePS6xXw4tR+hqDl3Nln2RSx5IbempAgkFz2SP8=,tag:D1PU/z/OCtF4HhklxC17Kw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:fbMSq9Y/nJUOF9CYVTqF5Tp52S4tcP5uLCgIvpPemsUJ/IxZ64I+Bw==,iv:+z/ozXigocNwSbMm9aLDVDEMf7tihAtTj02OvK3BdHo=,tag:VNvDWTzX2lzXhaX8+TN1xg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lDu5ajnc41wR5CFS3CUbFWKl3UeJ7HALLg+vPhmx7nXGIXCL4VKT+WqqEMRpGpa6bPXUdQtmKQPJTVJuAMBkcp6h3kjqT6sodN1bjFj8am493Q7TMmnSRYq24G6qkCCvwNvsrn20g0ND2CpdI7AC7U0HWrqad+LEKKN6UMG3JzM=,iv:cXUSJ3rO9TgDWd+PstVrGz+b2GA9WSsB/HuZFVUklHE=,tag:CGR7C2C/XtIz2Qzi0nPIAA==,type:str]
    GF_AUTH_GENERIC_OAUTH_SCOPES: ENC[AES256_GCM,data:/tnuhMUC16jLaJvx1zxsVjeoFSaplZws7WxQ/ce0ichm,iv:BfdVQaroWx+LzKoZxZ9BKKwtXRp1ut8X3EnCY0MYq0E=,tag:4vbtAi7OGIX2F5LLi0dbog==,type:str]
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:E3LW76BuVtcLLgLuWYPEpgutxhYHMJYgRGFNzJfsdilMs4aq5OWd5p2V4u7hD/9oCCRocLMfT5s=,iv:0xBEAOAJMJt8023gy8vygXOjWmUfJ020Qql9b2zeUBE=,tag:BzH5U3JpTYIxPET+QW3ygg==,type:str]
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:CWLtLm6SyEhOOWm8RgvWzs0A2GhajT2IzbiIby/Ndkzraham+SJndXywu0RyGicad72uBw==,iv:FJFiddSeXCTPQT5PRpdN1aoSx1CxrN1ERZKyZyYkEU0=,tag:u6QTGI5MaReEkKEfS+IGyQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:33I4ybm6n+PfOwDDdRUHXIFbwji5/wvp1ygPyWbcCR4SHRUQzKrAylc8OGLMh3HwNru7Fjxm0w==,iv:1qVjISdZEpEBbUoutyP7fMZ3kL66S/1CMJEed6zcdVU=,tag:GpCG1YdGZjBEAXeWkjB5GA==,type:str]
    GF_AUTH_SIGNOUT_REDIRECT_URL: ENC[AES256_GCM,data:zNqB6n7pcwAjodLWTBiihvYP5O3WuGUC17soYkGCToRY5tgp7HDP3eGH0mPKyo+oROXgFPZsDofeyVFWFnYb9XZD,iv:vACbpFIt72xi9dN++GtX6Ezpoj/aRj0vq1LYLch0MIY=,tag:Muh/B6uKOJ4sfWsqkXo47g==,type:str]
    # Optionally enable auto-login (bypasses Grafana login screen)
    GF_AUTH_OAUTH_AUTO_LOGIN: ENC[AES256_GCM,data:Q/xgAA==,iv:u2FDlKqkzQ6NwG4pqlmkUf+ODqbztVzen6g9P933Df4=,tag:Hc4o1IqNGQTC9EMbqCckOA==,type:str]
    # Optionally map user entitlements to Grafana roles
    GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: ENC[AES256_GCM,data:vlKQtUzTm1hC8Qnb75QiK5MzQ09sDq/oO6A8HihLDAXHc5OAn0v34XRm1crYRe9TAxsnaDB2Z0hZFhzb36sR9bt5+rw/Any46mdEbM0QKGg4Ls9Bb2eUzvOiwqycO0/RNBSuPj+jJk0esC8h14OciT7LMm1JAllvU4aC5CGE,iv:IIiIlIhxhnPzf43XJgl5Hna/7yfAxXTbiQ1bMU+V7+4=,tag:szlB2dLpJmRwEPZrgKDaNQ==,type:str]
    # Required if Grafana is running behind a reverse proxy
    GF_SERVER_ROOT_URL: ENC[AES256_GCM,data:ECyUjgEiBah+WrEX75/84RtvGiSQMacL+j6X9oU=,iv:81c2EvcW8lPK8NyLrAtkWldTdvIbDhEg7IrwaZ74rm0=,tag:kbrjOOfs3b7vlEgq3013gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbHVWVGZyU0lxSGpZQkZN
            Zk5SVm1IU2dac284QnorOGV5Q01SRW4vMkJrCnNtQ0tsQUc4Y3lQdFQzSXorQ0I3
            UXdvcWpNUU9sWXQ3d1NDUGpzVUZDRVkKLS0tIFAxaHNVNTJtMXlBWWZORlNZWHJJ
            K3lYT0R0RWxEc1NzWXRKWVJOdDBENHMKyXNGvaiaFjELoy3MhMQs/7MkQ2DA92FQ
            OHrV6fJXQA9fATsh+quY9re1pK+0Xy5EaLHY+uwSR0dTC8jBlVyCyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T16:30:25Z"
    mac: ENC[AES256_GCM,data:glh6ddFWWb/R5IzB0hz4Szp5+PkofiBAEVZIaMGTFwG/2U/MCIkNa9XNO8yVfnWxphiI7/c6SC2B3dyxi9irijRwMAeP44CDKsvUqJIMBL9W5X4+A674iv9xZhE8its5cHChVkeCs5Is3ev/laoPJc3tOyQ2wp7YHDwAE4doCpY=,iv:K079Vx6g/1x9qzRQ+V5TjfrjwSWAekHWNzgVUcR2PvQ=,tag:rrniZh4raLzj8DDsU/PeTA==,type:str]
    pgp: []
    encrypted_regex: GF_.*
    version: 3.9.1
