apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_ENABLED: ENC[AES256_GCM,data:rXO+Uw==,iv:viHZYjlQ2laRdwHwCyHc9YXmY8S3vZ50lBQ7L7AwhP4=,tag:KY1Z9MMzeEcwtRnH/6KIUw==,type:str]
    GF_AUTH_GENERIC_OAUTH_NAME: ENC[AES256_GCM,data:vjmlStEzUQcd,iv:a4xShePS6xXw4tR+hqDl3Nln2RSx5IbempAgkFz2SP8=,tag:D1PU/z/OCtF4HhklxC17Kw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:fbMSq9Y/nJUOF9CYVTqF5Tp52S4tcP5uLCgIvpPemsUJ/IxZ64I+Bw==,iv:+z/ozXigocNwSbMm9aLDVDEMf7tihAtTj02OvK3BdHo=,tag:VNvDWTzX2lzXhaX8+TN1xg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lDu5ajnc41wR5CFS3CUbFWKl3UeJ7HALLg+vPhmx7nXGIXCL4VKT+WqqEMRpGpa6bPXUdQtmKQPJTVJuAMBkcp6h3kjqT6sodN1bjFj8am493Q7TMmnSRYq24G6qkCCvwNvsrn20g0ND2CpdI7AC7U0HWrqad+LEKKN6UMG3JzM=,iv:cXUSJ3rO9TgDWd+PstVrGz+b2GA9WSsB/HuZFVUklHE=,tag:CGR7C2C/XtIz2Qzi0nPIAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbHVWVGZyU0lxSGpZQkZN
            Zk5SVm1IU2dac284QnorOGV5Q01SRW4vMkJrCnNtQ0tsQUc4Y3lQdFQzSXorQ0I3
            UXdvcWpNUU9sWXQ3d1NDUGpzVUZDRVkKLS0tIFAxaHNVNTJtMXlBWWZORlNZWHJJ
            K3lYT0R0RWxEc1NzWXRKWVJOdDBENHMKyXNGvaiaFjELoy3MhMQs/7MkQ2DA92FQ
            OHrV6fJXQA9fATsh+quY9re1pK+0Xy5EaLHY+uwSR0dTC8jBlVyCyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T11:01:53Z"
    mac: ENC[AES256_GCM,data:G0CBF7U5Bq4ipBlYR3m/gO91kdbPnZdluHPz7CAlRpV3I56F8Q0Q2JILg6IHzsNxKOCztEJ3dqcuqR8lUOQTANFheBpViJPWfxJ5J+RL3l3ndsgIryEUoR2TJQ3fRKdISn19t+1VIro5P1WZhdPgXfWf9KvJhd6UZhqXrPX5Mm0=,iv:zQTUq/S000rvJSP5jStmFdN9VtH2ricDEMizYspWtyM=,tag:Yvvu0YI2xIs/VTNrqSYoDg==,type:str]
    pgp: []
    encrypted_regex: GF_.*
    version: 3.9.1
