apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:9vdXBH0=,iv:BfIhmiLeVQbDIfcK2sDOQd74vlKFxUHo7VatzUUCJjc=,tag:iWRiHbdcZ5PpZ7VdJX3tPQ==,type:str]
    admin-password: ENC[AES256_GCM,data:3twd7Uwa298skTqe,iv:hw+8XM4SbeObhqxsrqBXgndfHCfNaV04PVaOWjrRf+c=,tag:Tw+KdYND6lxoKPfP2/odZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSWpIOUVmUzdjY2MxM25n
            RDFFdStLZmY4aDlGYnVVMGlNWHNHci8xRkVnCjhqdlluL2ZLbWFITHg3K29VTHBH
            OW9YWldOS3BuaDZWYkJRUEZKZVNLNkkKLS0tIGM1STM0ZkE3RHliVnRmL2c5eG1q
            a0ppV1RJWXpFM1BCRXhPVy9kMjhvZmsKNsiZKRt6I4yxQprFGzOFCskQXvgiySWD
            BOD38rpDZmENAuQp9Jwn8vuX2muHK22pMBHaBmbny7pWF0uW1npH5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T17:16:29Z"
    mac: ENC[AES256_GCM,data:16soXb6PAvH1pGvWd1knj3zqCyPvROn21msQmpSDv9EJ97Zuf//dbBZGmgiUlUlRf9W5Mx7n6VOEkWGXoC8CPTkaVdp4KYr/OBVkLDCU5QGbXxQNbWxVtM7f+1uM4f6gDVkBUnlmgaQ03qBj0+gj0UyJHPOXWoJOhtN5o7p3Uhs=,iv:VX2g8wM2YmgJ4EWyDy3URXluc4IYT2nVQhcSqoOV6uc=,tag:7mPVzVZlYc4SGLgMGlhh/w==,type:str]
    pgp: []
    encrypted_regex: admin-user|admin-password
    version: 3.9.1
