apiVersion: v1
kind: Secret
metadata:
    name: restic-config-radarr
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:OGb2T+m0azVbHJj2mdEUao6jsmXKR+MR2eexUEFbDtKQgxgG22BfkUtd,iv:qCAYIMnx+6BSHH/CtKjpwJIFoP5izTIKzUwlePlPG5w=,tag:s+Z92ni+4KAvyhvs35S/AQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:55dIlq5fYwIrPCW2BArBTGf9,iv:Lw+3s3cBmqM526oaZWG9LM9RVWLo6x/daZTeY5RGWfc=,tag:o3W2fqySDdGISzApetZD+w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zGFc5Vto,iv:SNeU/YXaxhe7UMn1ZHKPtGGMT5ntzj9WGa0Y3fTgXcE=,tag:soPSRmBkoA/glGho43gQ+A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mRaqw3Od9E1ExhbL,iv:C9+Z/1aj738HiG9A/9KOa24olrEpuwYhRMZ15f5hnSw=,tag:2o6S8TmThSlX11N7jnvIJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:47:05Z"
    mac: ENC[AES256_GCM,data:CkWb2bg4B+i2S8ciiRaiRErgq9B7CN/+KmuPCeu2BEmvFh90jRZ8roY1pk/a926v6Uj8gfZUnExDl0ynZq/82oDHBHeU02qu+0qLcl18khOTg6Zl4W4bMkL6KcjJmA4bY5Nbtjh7dZazDsbtO7reKf/UXdb9jAkgUpR56C393tw=,iv:u15LeKc2uJRnTY7/QWPMVnADbGL8tQD0yG2JrzMvlSs=,tag:ThCgjn4I/XJcm9A7jtK74Q==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
    name: radarr
spec:
    sourcePVC: radarr
    trigger:
        schedule: 0 22 * * *
    restic:
        pruneIntervalDays: 7
        repository: restic-config-radarr
        cleanupTempPVC: true
        cleanupCachePVC: true
        retain:
            hourly: 1
            daily: 1
            weekly: 1
            monthly: 1
            yearly: 1
        copyMethod: Direct
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:47:05Z"
    mac: ENC[AES256_GCM,data:CkWb2bg4B+i2S8ciiRaiRErgq9B7CN/+KmuPCeu2BEmvFh90jRZ8roY1pk/a926v6Uj8gfZUnExDl0ynZq/82oDHBHeU02qu+0qLcl18khOTg6Zl4W4bMkL6KcjJmA4bY5Nbtjh7dZazDsbtO7reKf/UXdb9jAkgUpR56C393tw=,iv:u15LeKc2uJRnTY7/QWPMVnADbGL8tQD0yG2JrzMvlSs=,tag:ThCgjn4I/XJcm9A7jtK74Q==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
    name: radarr
spec:
    trigger:
        manual: restore-once
    restic:
        repository: restic-config-radarr
        destinationPVC: radarr
        copyMethod: Direct
        cleanupCachePVC: true
        cleanupTempPVC: true
        moverSecurityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:47:05Z"
    mac: ENC[AES256_GCM,data:CkWb2bg4B+i2S8ciiRaiRErgq9B7CN/+KmuPCeu2BEmvFh90jRZ8roY1pk/a926v6Uj8gfZUnExDl0ynZq/82oDHBHeU02qu+0qLcl18khOTg6Zl4W4bMkL6KcjJmA4bY5Nbtjh7dZazDsbtO7reKf/UXdb9jAkgUpR56C393tw=,iv:u15LeKc2uJRnTY7/QWPMVnADbGL8tQD0yG2JrzMvlSs=,tag:ThCgjn4I/XJcm9A7jtK74Q==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
