apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: time-slicing-config-shared
    files:
      - shared=time-slicing-config.yaml
    options:
      disableNameSuffixHash: true