version: v1
flags:
  migStrategy: none
sharing:
  timeSlicing:
    renameByDefault: true # name will be nvidia.com/gpu.shared so I can specify it in the pod spec that I want to run on a shared GPU
    failRequestsGreaterThanOne: true # there is no point in requesting more than one GPU
    resources:
    - name: nvidia.com/gpu
      replicas: 4