apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-ai.yaml
  - secret-hf-token.yaml
  - llm-d
  - qwen-38-27b-fp8
  - qwen-38-27b-fp8-sglang
  - qwen-38-27b-nvfp4-sglang
  - qwen-38-27b-nvfp4-tp2
  - qwen-38-27b-unc-nvfp4-tp2
