apiVersion: v1
kind: Secret
metadata:
    name: hf-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Yi0rD9ma1+ANHTdMKIXIuwW+2BB4KhxKKrhByL1fcGZ6iDfn/Q==,iv:YyECLLsYtELnpK81pfgOtQQdwLXE4jcW97Tk9fAa9PQ=,tag:X5xzHc5l0Ag+pwqclOlr+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcjI5L2dKRkVUWEZHOU84
            emNSQU5XR2FyMExLZDh3aURnSWFnUE40VldRCkRoL0lYWUgwM0ZaSHJrdStvR21E
            eXRNbVN1TnhtMFhFMHVLVGhyR1J1dkkKLS0tIEpiY1JTUzZzSGFxemJUbklpZWJo
            QjdwcEJCajdoWU1GdHBtcm91UHp3Rk0KaPvij1izxMC/3PI9qFcOYplO4DADLB4g
            XwqrEMBXc5cX5UTHEH2fWeZVDfZGBgUnrWhGHkIboMmVz1I88iZxCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T08:14:45Z"
    mac: ENC[AES256_GCM,data:vnKYcdMndvfa2G6uaAjk9y9KoGsLhOZoXqpCvEXViTuIqXceEziSgGCkYjxE04AvbIANkPdoguTjyHk1fFTaeW/Pb8Fh+7hXapPbhDONDAeOV6hA3+s7cUDrFgrydSNE+9pX5sk9FxvtEy9Z635VdXU8ixDRG4+JLjk3XfZ75Cw=,iv:Lmn3iKwj4nHX2nKF3j7yniRnXfG9+rDAnmszdmN9Loo=,tag:3fVtNZZlecyt+G5Sf3I7Hw==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
