apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: llm-d-router
spec:
  interval: 5m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: llm-d-router-gateway
  values:
    provider:
      name: istio

    httpRoute:
      create: true
      inferenceGatewayName: llm-d-inference-gateway
      requestTimeout: 300s

    router:
      modelServers:
        type: vllm
        protocol: http
        matchLabels:
          app.kubernetes.io/name: vllm-tp
          app.kubernetes.io/component: leader
        targetPorts:
          - number: 8000

      inferencePool:
        failureMode: FailOpen # if EPP fails, continue the request without intelligent endpoint selection

      epp:
        replicas: 1
        parsers:
          - openai-parser
        flags:
          v: 2
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 2Gi
