apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - helmrelease-unc.yaml
  - ocirepository-ipp.yaml
  - helmrelease-ipp.yaml
  - configmap-ipp-model-mappings.yaml
  - httproute-model-discovery.yaml
  - gateway.yaml
  - authorizationpolicy-benchmark-maintenance.yaml
  - rbac-benchmark-gate.yaml
