---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: qwen-38-27b-fp8-sglang
  name: qwen-38-27b-fp8-sglang
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
