apiVersion: v1
kind: Service
metadata:
  labels:
    app: qwen-38-27b-fp8-sglang
  name: qwen-38-27b-fp8-sglang
spec:
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app: qwen-38-27b-fp8-sglang
