apiVersion: v1
kind: Secret
metadata:
    name: litellm-env
type: Opaque
stringData:
    #ENC[AES256_GCM,data:BXF32525FeLJiaN3etf50yeLlq5bgoDLtcO9mx/A8G8lVvcWYYV4N3e9ZL7YpjHHqzDZmIiaRmWUmP5neqEdXS5AW1NxaDF1oOM=,iv:+EAk86fdGHzY1/fGGv8TU2Iw75ExZqFytN+a5Nc8J8k=,tag:8T9UqvuUIb8Ye4HKUxc+eQ==,type:comment]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:MXf2uDN2u+gNwnOAt1lCbif2UrkfCP88xTz1fyI9my20jDc7oQ4QOpdDACwU/oQWKEw0,iv:DPHfkvYfYS6dejq3a8Fgmg8lxCS1FAJOXXTf0ssk+5M=,tag:v0lqCLmKGhm6xsugUnydaA==,type:str]
    #ENC[AES256_GCM,data:SBmJegk=,iv:V91O844Qi0yOhvWHUNvm9iOXWLcyYu2IK5eY99QBIL0=,tag:QkhOQM/J44aL1BvC2umuXQ==,type:comment]
    SMTP_HOST: ENC[AES256_GCM,data:yK9F2NvxyZGm0L6B0cFNWLo=,iv:ghOmw7xMbm7tTmusndGevFTftf63hmXTYW/3Megx8F0=,tag:KET8YzWfzZySNqcSbto87g==,type:str]
    SMTP_TLS: ENC[AES256_GCM,data:OMSGHg==,iv:Z9hZWBkBiXznC2M8C+XGkOlyDcKF+wbBEAUOu0qxQdk=,tag:+FZQpILxS3a0XQXYppd8eg==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:7b2X,iv:wyVoz51nXHJFh2hp+O7SK3KUMR5wARZ8iXk0EtziFtE=,tag:xMBBtD7LaLHAwM2hIvTViA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:Hfs2e9KZi/uP2F/uw86oU+p4m6N0,iv:Hn+BOht+HcbFGLCSoApyGfl0ZXPqcDyJe9KQWKig3x8=,tag:iicjmOZQTKmh/TZ5aY2iLw==,type:str]
    SMTP_SENDER_EMAIL: ENC[AES256_GCM,data:lrlh+E8hNU+apAP32qJijrjAoPP2,iv:tjndgVK8+jJ7H/dAp7bjxvw1JSdx2vvgSXf5xwbNiU0=,tag:rI3etLaiQrfeBaD86KyeIg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:lx+nkzkrtfS4f9je64/y5TmldNau0bjoIJLJRuIKWsAavV0vYVm+jA==,iv:zGJX9IHbkVlYPFZ2y/jcVeuMGmPhVyFlyl5nCbwI8nQ=,tag:Uiu18793hbi7XNADQ/buQA==,type:str]
    #ENC[AES256_GCM,data:RtapwQ==,iv:aWQtvV1/qrYEzbunooFOJdo9DHBiuWkg3uPSTcQ9CQM=,tag:t0kLlWR8NCl+oIn/EumULA==,type:comment]
    GENERIC_CLIENT_ID: ENC[AES256_GCM,data:EVxekRfmDoRW1aVMMJV0zEGsr6NvNf0b3cMLtjis41OiI4M0ZG51LQ==,iv:3wvNtMw5qr9qmfodqrTwfDu1Z29bcDbsviKLL05z9FA=,tag:Ur+Gy6/3XHqykJIUKxI65w==,type:str]
    GENERIC_CLIENT_SECRET: ENC[AES256_GCM,data:S0NqMFPROmsS79G7dfCpAWURL6gxg0aBN7Y8LIuHyX+HC3VU6OQ62EVWziwxSDjbWfQM7U+fCos8EYaxpkz6pwl2eZ+kqWhE6JJ7nboh8Wm4tpVxJ+gfXabS4vhEu22R2ZJevw47b+HssPC960yWLNdPc8AyHmvFEFx/5vWcuw8=,iv:WJ2i46KZvJz5HHWTt/kucZh82pDnszeOVigRh8eydag=,tag:DnQxhxgnoF+OJNdSWhanDg==,type:str]
    GENERIC_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:lFXrcXutDe7cbQFkPPBjSRMfmsyXLFYUN5g9ienmv2ehR44K2IF0vc2TjN4a7UP45g==,iv:6seB+1Ez6A7I2IUJnpGE6jk2qkdKrlgbra+OhHzHDl4=,tag:bR4FdB//fAudD9kFcRsGIQ==,type:str]
    GENERIC_TOKEN_ENDPOINT: ENC[AES256_GCM,data:TYH1grjPO7kS6g60SFz6WK7ipPIj231tcAoiZgDFGCmDH7Zucgtuf2vbi5sX,iv:Tuzv+U4oRO5tmzJqPXCWuCbMsCK+XopHcqrS3UGzOTc=,tag:FIjGAslQAAxdjc9cbufa6g==,type:str]
    GENERIC_USERINFO_ENDPOINT: ENC[AES256_GCM,data:3pe+RHMVgtBwoK6Uia85PowuqeIdDRBfDEQn9mK2+Yl3gzSQ7zEiHdQS2gW8KCja,iv:HncmFAKp51gEHgqST8bw9jN7qzl4R6btEXRrXOXRn/E=,tag:C300FRn2wNTzcrf4wGOQ6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVlVIZFNLSVF2VHBBbzh3
            eWtFeFJ6cmIxR09ISTQ0U1FEN3dsMDMwTG5vCnBhZWF0KzhLWXQ3djJpL2JkTGlh
            YksrMmJwYy9FbDBQWEtrVkVRZlZLaE0KLS0tIC9BdnR1cUNtU3RUWGppbkhGM3RM
            M2x3cTE5ZUJ1NDlvcy9lS2pkR1JnSlUKpC5D4TCYAPxjyd3zOxIY1gz/71fHMjdZ
            vP6z4WcPNkBUvj+pFrlruXGqAwgqWwEgLvat9jxkVdLflTQZVnSenA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T12:09:00Z"
    mac: ENC[AES256_GCM,data:1pjVsIIPBBBFAIgmyXB1ItEdGI7ju2MqWE07k7nXQ0TADYndUadE5QakUOAyhiVKmToExAwxYXiralaxlATPieNlI5IIp/mOJ8eEkSTsCjlmwqYV4ir7AOYMtC3XvZZyjqGGc6JHVpMD4ZlFhsT7n8p3RrkzKgSqwjzDa9YgbHA=,iv:5l9QVBgreg0WKuHczSdgJ0ecf8UIZIY60FZFTK077vI=,tag:hEZvMcV749fT5HZ0SVhorg==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
