apiVersion: v1
kind: Secret
metadata:
    name: litellm-masterkey
type: Opaque
stringData:
    #ENC[AES256_GCM,data:mLwzEEuY9h6RnvcUcZypoJQfnpN/KZZ3J87U7FEQ1dfk9QKs1uOQtnx4F0lu1Uv+9Y1dtfo99NwkLV2a09zC/Jg=,iv:3yvVYqOlt4x2lgJCM8Ti/dgWiVhfGmEmfmn0L/azhO0=,tag:wXiwtQl+Vk8aL7CTAKv9Og==,type:comment]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:y6pLXoKlzGh6yjudBx35h11/ccL+LBFVjWxmmSLlB/xdEYu25mKf6TmrA25fvr0BZ9SG,iv:CLm3z6n44FrT4I6ssRvxNxIsdlMfMgnsMX1g1WsYiG8=,tag:kYt5s7EMmmOpG58kBfe8Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVlVIZFNLSVF2VHBBbzh3
            eWtFeFJ6cmIxR09ISTQ0U1FEN3dsMDMwTG5vCnBhZWF0KzhLWXQ3djJpL2JkTGlh
            YksrMmJwYy9FbDBQWEtrVkVRZlZLaE0KLS0tIC9BdnR1cUNtU3RUWGppbkhGM3RM
            M2x3cTE5ZUJ1NDlvcy9lS2pkR1JnSlUKpC5D4TCYAPxjyd3zOxIY1gz/71fHMjdZ
            vP6z4WcPNkBUvj+pFrlruXGqAwgqWwEgLvat9jxkVdLflTQZVnSenA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T10:50:20Z"
    mac: ENC[AES256_GCM,data:svk0aN0cvaTsmhIbfho9w0eLcfOzr37eE1krJtpHrqCzNqUez+3TDx7YZ5vTuL50r/vtlYibYUU8Rpvjf2obuqNLLuZ0b3JiUCWQO7udtMm/E8/Yr7+H71XhUd0MGs7QHaRMYO0K3WLiU9C/8+zMCXPPvwGamlUI/aHdqKsS3hI=,iv:EVMW3rnsTDw9on8duQOkinoSVMEJ8CAU1Sk3ZpNiwcs=,tag:LOKrfEnp5B//jNkP3m4NMg==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
