apiVersion: v1
kind: Secret
metadata:
    name: litellm-env
type: Opaque
stringData:
    VLLM_KEY: ENC[AES256_GCM,data:UtSjw3Ov4LsXUHz3IA==,iv:blWOn1i33BZKBE4qWVsfSgTRp+V56eoEOYintkIVHOU=,tag:kHDT1rD2MU3pwObmze5/fA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVlVIZFNLSVF2VHBBbzh3
            eWtFeFJ6cmIxR09ISTQ0U1FEN3dsMDMwTG5vCnBhZWF0KzhLWXQ3djJpL2JkTGlh
            YksrMmJwYy9FbDBQWEtrVkVRZlZLaE0KLS0tIC9BdnR1cUNtU3RUWGppbkhGM3RM
            M2x3cTE5ZUJ1NDlvcy9lS2pkR1JnSlUKpC5D4TCYAPxjyd3zOxIY1gz/71fHMjdZ
            vP6z4WcPNkBUvj+pFrlruXGqAwgqWwEgLvat9jxkVdLflTQZVnSenA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T10:47:02Z"
    mac: ENC[AES256_GCM,data:JFrcXGK1DgTUthUloFeb2P7/Nd+WBaprDMJG8+Wu/GksuRqZlGCdsKrHcNEji4nJhwuxT0z1V/piokb9yXnUT+9WyuKGAN6Z2w3IRAuh34OUCwVrt5DoF0PJYPYRsV7CQ5iYtGrfrFVE+tZghPWY4/kd8K66VrDthjjzSgbvszo=,iv:PSshf5gMl2MiRSpLMMhy534ezGS5mZJv/a0TcP/z5xY=,tag:cZ80bs7WWeVkxh/VpUNzMA==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
