apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  dependsOn:
    - name: nextcloud-cluster-v00
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: '8.4.1'
      sourceRef:
        kind: HelmRepository
        name: nextcloud
      interval: 5m
  values: 
    ingress:
      enabled: true
      className: nginx
      tls:
        - secretName: almothana-xyz-tls
          hosts:
          - nextcloud.almothana.xyz
    nextcloud:
      host:  nextcloud.almothana.xyz
      trustedDomains: 
      - "nextcloud.almothana.xyz"
      - "nextcloud.cloudforest-sargas.ts.net"
      - "nextcloud"
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 8Gi
      nextcloudData:
        enabled: true
        accessMode: ReadWriteMany
        size: 8Gi  
    livenessProbe:
      initialDelaySeconds: 1800
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    dnsConfig:
      nameservers:
        - 192.168.0.2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      rules:
        enabled: true
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: "nextcloud-cluster-rw:5432"
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db-credentials
        usernameKey: username
        passwordKey: password