apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-tailscale
  namespace: nextcloud
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: nextcloud
      port:
        number: 8080
  tls:
    - hosts:
        - nextcloud