apiVersion: v1
kind: Service
metadata:
  name: onlyoffice
  namespace: nextcloud
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: onlyoffice
  type: ClusterIP