---
  apiVersion: kustomize.toolkit.fluxcd.io/v1
  kind: Kustomization
  metadata:
    name: metallb
    namespace: flux-system
  spec:
    force: false
    interval: 5m0s
    path: ./infrastructure/metallb-system
    prune: true
    sourceRef:
      kind: GitRepository
      name: flux-system
    targetNamespace: metallb-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  force: false
  interval: 5m0s
  path: ./infrastructure/tailscale
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: tailscale

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./infrastructure/external-snapshotter
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: external-snapshotter

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  force: false
  interval: 5m0s
  path: ./infrastructure/synology-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: synology-csi

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  force: false
  interval: 1m0s
  path: ./apps/nextcloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: nextcloud

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: speedtest-tracker
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  force: false
  interval: 5m0s
  path: ./apps/speedtest-tracker
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: speedtest-tracker

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  force: false
  interval: 1m0s
  path: ./apps/kubernetes-dashboard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kubernetes-dashboard

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./apps/plex
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: plex

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homarr
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./apps/homarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: plex

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./apps/qbittorrent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: plex

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lidarr
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./apps/lidarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: plex

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./apps/prowlarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: plex