apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-cluster
spec:
  dependsOn:
    - name: cloudnative-pg
  interval: 5m
  chart: 
    spec:
      chart: cluster
      version: '0.3.1'
      sourceRef:
        kind: HelmRepository
        name: cnpg
      interval: 5m
  values:
    type: postgresql
    mode: standalone
    version:
      postgresql: "16"
    cluster:
      instances: 2
      imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.1
      primaryUpdateStrategy: unsupervised
      storage:
        size: 5Gi
      initdb:
        shared_preload_libraries:
          - "vectors.so"
      postgresql:
        shared_preload_libraries:
          - "vectors.so"
      pg_hba:
        - host all xormon 10.244.0.0/16 md5
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
      roles:
        - name: xormon
          ensure: present
          comment: XORMON monitoring
          login: true
          superuser: false
          passwordSecret:
            name: xormon-auth
          inRoles:
            - pg_monitor
    backups:
      enabled: true
      provider: s3
      endpointURL: "http://192.168.0.109:9001"
      secret:
        create: false
        name: backup-s3-credentials
      s3:
        bucket: "db-backups"
        path: "/immich"
      scheduledBackups:
        - name: daily-backup
          schedule: "0 0 0 * * *" # Daily at midnight
          backupOwnerReference: self
      retentionPolicy: "5d"  