apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: '0.9.0'
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 5m
  values: 
    env:
      DB_HOSTNAME: "cluster-rw.cnpg-system"
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: postgres-auth
            key: password
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: postgres-auth
            key: database
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: postgres-auth
            key: username
    immich:
      persistence:
        library:
          existingClaim: immich-library
    postgresql:
      global:
        postgresql:
          auth:
            existingSecret: postgres-auth
    redis:
      enabled: true
    server:
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.almothana.xyz
              paths:
                - path: "/"
          tls:
            - secretName: almothana-xyz-tls
              hosts:
              - immich.almothana.xyz
    machine-learning:
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: pvc
          accessMode: ReadWriteMany