apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: '0.10.1'
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 5m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: "v1.132.3"
            env:
              DB_DATABASE_NAME: "app"
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-cluster-v01-superuser
                    key: host
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-cluster-v01-superuser
                    key: password
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-cluster-v01-superuser
                    key: username
              TZ: Asia/Riyadh
    immich:
      persistence:
        library:
          existingClaim: immich-library
    valkey:
      enabled: true
    server:
      persistence:
        extrapv:
          enabled: true
          type: persistentVolumeClaim
          existingClaim: "external-library"
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.almothana.xyz
              paths:
                - path: "/"
          tls:
            - secretName: almothana-xyz-tls
              hosts:
              - immich.almothana.xyz
    machine-learning:
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          accessMode: ReadWriteMany