apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: '0.9.3'
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 5m
  values: 
    env:
      DB_DATABASE_NAME:
        value: "app"
      DB_HOSTNAME:
        valueFrom:
          secretKeyRef:
            name: immich-cluster-superuser
            key: host
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-cluster-superuser
            key: password
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-cluster-superuser
            key: username
    immich:
      persistence:
        library:
          existingClaim: immich-library
    redis:
      enabled: true
    server:
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.almothana.xyz
              paths:
                - path: "/"
          tls:
            - secretName: almothana-xyz-tls
              hosts:
              - immich.almothana.xyz
    machine-learning:
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: pvc
          accessMode: ReadWriteMany