apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: '0.9.0'
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 5m
  values: 
    immich:
      persistence:
        library:
          existingClaim: immich-library
    machine-learning:
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: pvc
          accessMode: ReadWriteMany