apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 300Ti
  storageClassName: nfs
  nfs:
    server: 192.168.0.109
    path: "/volume1/pic-library"