apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: external-library
spec:
  volumeName: external-library
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Ti
