apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mailpit
  name: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - image: axllent/mailpit:v1.30
          name: mailpit
          resources: {}
          env:
            - name: "MP_DATABASE"
              value: "/data/mailpit.db"
            - name: "MP_MAX_MESSAGES"
              value: "0" # Unlimited
            - name: "MP_UI_AUTH_FILE"
              value: "/data/auth/passwd"
            - name: "MP_SMTP_AUTH_FILE"
              value: "/data/auth/smtp"
            - name: "MP_SMTP_TLS_CERT"
              value: "/data/tls/tls.crt"
            - name: "MP_SMTP_TLS_KEY"
              value: "/data/tls/tls.key"
          ports:
            - containerPort: 1025
              name: smtp
            - containerPort: 8025
              name: http
          volumeMounts:
            - mountPath: /data
              name: mailpit
            - mountPath: /data/auth
              name: auth
            - mountPath: /data/tls
              name: tls
      restartPolicy: Always
      volumes:
        - name: auth
          secret:
            secretName: mailpit-auth
        - name: tls
          secret:
            secretName: almothana-xyz-tls
        - name: mailpit
          persistentVolumeClaim:
            claimName: mailpit