apiVersion: v1
kind: Secret
metadata:
    name: mailpit-auth
type: Opaque
stringData:
    passwd: ENC[AES256_GCM,data:GcU+1nLr6bzIGm5iM2jSz76+8Bb1gplBNl53MeUL/fYSB60b8ogoWpA4iPvsZuCzCLxbF096PGZ5kDHjufbS2A==,iv:M0QLwGjzCn5UPXSbvshZvgVjHVyg36KchpnWZ0dHXaw=,tag:lM68IMl5pUQn3Y3/ASoXTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdFg4bStuRVhEZGhtWFU3
            dmxGVDZGN05Ba0R6TzVtSHZLZ2puVFJyc2p3CnVnTXlXL0tzZ0VPSUtoZG9MWnlK
            VmNrN0tXNU9EQTRldmVNRDVxRG1sNm8KLS0tIHpkcnN6ZndhYys3Yk9Tcml1M2JR
            K0tjNlp1elZibFh6VlVZenplQ0k1U1kKPeNMl3g6b+S0rixti28YiafcDA2+Pcc8
            TvYyC/Nfd3iqLlYBWCnsEfCpc29JVQOZYtG13dFmGLuQ1ZW5HDn3sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T15:52:15Z"
    mac: ENC[AES256_GCM,data:Nwb2UdXp9UFMfunYTzkT3tCoD0jq6sPuxiuX/2TQtRbfpY3KFJKM2Urytshz2/at7dRPt5uUESWJWrZHOlErRqP8hzgn9+xyhELcv/oiCI3khD2lmZVWJUhadKBSuanSM3r+fnemmzF+1Og4AtJWpeK9vMw2b/wdHCQjlbN4834=,iv:pTiZO1nJoRTGVUDN3xMpSvpHzIc7fCtY8I9xpzI3jXw=,tag:C/RnC6m/mSZpxkjVvy+Cbw==,type:str]
    pgp: []
    encrypted_regex: passwd
    version: 3.9.1
