apiVersion: v1
kind: Secret
metadata:
    name: mailpit-auth
type: Opaque
stringData:
    passwd: ENC[AES256_GCM,data:GcU+1nLr6bzIGm5iM2jSz76+8Bb1gplBNl53MeUL/fYSB60b8ogoWpA4iPvsZuCzCLxbF096PGZ5kDHjufbS2A==,iv:M0QLwGjzCn5UPXSbvshZvgVjHVyg36KchpnWZ0dHXaw=,tag:lM68IMl5pUQn3Y3/ASoXTw==,type:str]
    smtp: smtp-user:$2b$10$YRoTNDtpehaAgtKOCaCtLOWNs6A8JeSVUN7wBMG5ZGthyB8YYfVMW
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdFg4bStuRVhEZGhtWFU3
            dmxGVDZGN05Ba0R6TzVtSHZLZ2puVFJyc2p3CnVnTXlXL0tzZ0VPSUtoZG9MWnlK
            VmNrN0tXNU9EQTRldmVNRDVxRG1sNm8KLS0tIHpkcnN6ZndhYys3Yk9Tcml1M2JR
            K0tjNlp1elZibFh6VlVZenplQ0k1U1kKPeNMl3g6b+S0rixti28YiafcDA2+Pcc8
            TvYyC/Nfd3iqLlYBWCnsEfCpc29JVQOZYtG13dFmGLuQ1ZW5HDn3sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T14:24:23Z"
    mac: ENC[AES256_GCM,data:C4QbkqXsOjkPJRVfxdQ/lAP8Bew81A79YRVUYzHAEEPTdxgm11jhS+boyVBQj1yvyWSLw+IJEVa9k2IjnwOUswKnzKpDptytazca9cqmMkhm3UD22wn8n/u+F9gkgsBYvA3gPE8LWjGc5S8gmppW03PSTurRIp93b2arm86e2UY=,iv:5RIOz1rizX8L/0LRKiUs4fn5aT9+AvCLFqY2BqzWS1Y=,tag:SMHgD5uKBB4cumvqj73aSQ==,type:str]
    pgp: []
    encrypted_regex: passwd
    version: 3.9.1
