apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailpit
  name: mailpit
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8025
      targetPort: 8025
  selector:
    app: mailpit
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit-smtp
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mailpit-smtp.almothana.xyz
spec:
  type: LoadBalancer
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
  selector:
    app: mailpit