apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-searxng.yaml
  - deployment-searxng.yaml
  - service-searxng.yaml
  - ingress-searxng.yaml

configMapGenerator:
  - name: searxng-settings
    files:
      - settings.yml
    options:
      disableNameSuffixHash: true