apiVersion: v1
kind: Secret
metadata:
    name: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:egGRdBpEgYHMgVtQNzCdvZex3mDId+QBZSgbZH+0ulIa3hUCswYfmg==,iv:+sED8hgKQ27XifnXJhJT5QRYBFVbFBNVaFYKAonMSqA=,tag:FGABXJj3YDXDT4lzV5o93g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSGFLUW5mSTNqdFQ5bHZt
            R1ZzcStnWExEbFJ3ejZ0VVpOd0NBbkMvZEF3Cnh3TzNiOWE2QTg4N0pneFBBUkpS
            My9NMlVKcDBZRUJlQXF4NGxlUWJEUEUKLS0tIGhodGVDRjNuaWs4ODZKZk5Ybjd1
            NWN3ZzViRXBCcjdGT3RveE9iNUJQdU0KBTXkkBeNsxn6SJb9OWhS+dMwRH0+Wfgb
            Z0nOdvn1jOIRCn9LfAUoqJ/42isAyL/Y/9pb27ktji1/3WYdksR4hQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
    encrypted_regex: ^stringData$
    lastmodified: "2026-09-17T16:33:31Z"
    mac: ENC[AES256_GCM,data:zpEOUlraLn5G4iAgzJQDIoWGevSvQVD/VwohFTa837mnXbk2unaIHJ7sNqvcabXIHJd5Rg3IlcGwAQssAb+gEYU/UbVTpS7MDNBHWlNGgUGtVrpQ8b2kmU+v3NTMVrcStbgwdYo666J4Ppzkrqc/Vuy9/JfjixoawNIejznmbTw=,iv:8UYFfdVfgfg+yIXeR/VRfzlksq1DcHb/hKTKt0OcLGw=,tag:h2DZNabugy4pBVFW2xeJfw==,type:str]
    version: 3.13.3
