apiVersion: v1
kind: PersistentVolume
metadata:
  name: rom-library
spec:
  capacity:
    storage: 3Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.109
    path: "/volume1/library/games/"
