apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rom-library
  labels:
    app: romm
spec:
  volumeName: rom-library
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti