apiVersion: v1
kind: Secret
metadata:
    name: romm-oidc
type: Opaque
stringData:
    OIDC_ENABLED: ENC[AES256_GCM,data:FFnVuA==,iv:RIH8C1D+w/jqasMJmtO+PqS33xXQhbiM2v4OuWic0SU=,tag:HjqHzwkBfWW+yJKAOLyWUg==,type:str]
    OIDC_AUTOLOGIN: ENC[AES256_GCM,data:k30Ciw==,iv:4IypWWq6ZpppSyc9/8pnCZ9NajihQzRVu1HsbraiFso=,tag:zgV/2Z0j/nmsMXYsTB3iqQ==,type:str]
    OIDC_PROVIDER: ENC[AES256_GCM,data:N7YVjP3nkaHU,iv:Y8SDyxJSuJJxhFyVORrFazD11SgMu3/8AVhlccAvf/Y=,tag:FpMbdS337XI5LcELoD0mcA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:NU1k2l8LL/r1SwezNhgb6D+izRgc+fToBKyzjjFvXAXWOVMjqdjZdw==,iv:iSfQdXI9J0tCqUr7rI9WvF+t5rxqb1TPHiawDE6Aw4Y=,tag:Wcsm9dyC7eAZIwfLohf91A==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Ec7bLg6Kru57YIPzeqLmXXGRL0kVOWzRcg9cJTfkMP6YlU0ugvIh72cN7IVs9WtTsS3VdR/d4abiHuqudHBhLRchQpc0r5a/oxLYyNLF6Z54PosDp6+FBzHAzLeNLjr8M1XDMAZkyfhhVi+Q34a3TXTtJh9ZRekiW3NZsCnoBcA=,iv:hcNuoMF/HneMbcyK7D+TDdnmMVUtQyeElnZDLmQ72XY=,tag:3w55h2EpnGM4fuNSjkCHfA==,type:str]
    OIDC_REDIRECT_URI: ENC[AES256_GCM,data:8Slk1pvIFXKtdDAC0L7gipiTcgA55y6EDnRo84b6mm0DMHv5FO8VWEZDBw==,iv:UlBWb8E5swyGxyEAJHYlX2Xp+QyvVAiD1hXgrXQbhSs=,tag:oMbAZqxmjKzbitFoeNGZFQ==,type:str]
    OIDC_SERVER_APPLICATION_URL: ENC[AES256_GCM,data:f0W+1AqVw1DgWjkYFGVqrvIZd3xHogIL2bH6yP24chR9ANJVEbTdSoyvzQ==,iv:eYlPM2n0pzbO4ODAIlnaUAJLComD6d7l8h5cv+sDlDw=,tag:zz/wDqtikTPRavVuItdFMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRXFjUGVxVUkrMDUyR0Ni
            WWlBbHdYNlQ0M1J5azl4QUQ3Y0J5ZmFobWxVCmhvVDl3ZlpWbXdUdWJsbkZLOW9u
            L0p1VUNYTmp3MjJYc00rQWVQYlcyaVUKLS0tIGZCalI1M2VtNWxyd0w3bUZkTDJu
            WjVTclFydkt0QTY4bERLRWpuMUpTSVkKJZ6avEaqGgZFojKvPmpmpct8SVKXDfUD
            X0Pc8vs3+BJdszFl2IdVxyYgd0jIeDrzCIibRKvsEfVkAiw0l3e7IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T15:37:20Z"
    mac: ENC[AES256_GCM,data:Q5o//Xg9vTQZ/FPABhmhpbriFbK3m0aKYg/EEpvxeArhvNF0Y+mbYAs9d9MIGDso7SaCEa35trwCh/L1Ah5BbdwtkBHzX6Z5OokDNLxuIa0Hfg//JF/IgsbuwxzXIGJR7ybtsveIwBAfHuhgFYOWOl+P598UuGWZf57cogaTkEs=,iv:+BlrsoqSNya4NaTQIAVXJ49iJfbOciTrJz3uLzFoAik=,tag:g8ZH3Dz2D8v0Z6iRj4bCzw==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
