apiVersion: v1
kind: Secret
metadata:
    name: romm-oidc
type: Opaque
stringData:
    OIDC_ENABLED: ENC[AES256_GCM,data:FFnVuA==,iv:RIH8C1D+w/jqasMJmtO+PqS33xXQhbiM2v4OuWic0SU=,tag:HjqHzwkBfWW+yJKAOLyWUg==,type:str]
    OIDC_PROVIDER: ENC[AES256_GCM,data:N7YVjP3nkaHU,iv:Y8SDyxJSuJJxhFyVORrFazD11SgMu3/8AVhlccAvf/Y=,tag:FpMbdS337XI5LcELoD0mcA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:NU1k2l8LL/r1SwezNhgb6D+izRgc+fToBKyzjjFvXAXWOVMjqdjZdw==,iv:iSfQdXI9J0tCqUr7rI9WvF+t5rxqb1TPHiawDE6Aw4Y=,tag:Wcsm9dyC7eAZIwfLohf91A==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Ec7bLg6Kru57YIPzeqLmXXGRL0kVOWzRcg9cJTfkMP6YlU0ugvIh72cN7IVs9WtTsS3VdR/d4abiHuqudHBhLRchQpc0r5a/oxLYyNLF6Z54PosDp6+FBzHAzLeNLjr8M1XDMAZkyfhhVi+Q34a3TXTtJh9ZRekiW3NZsCnoBcA=,iv:hcNuoMF/HneMbcyK7D+TDdnmMVUtQyeElnZDLmQ72XY=,tag:3w55h2EpnGM4fuNSjkCHfA==,type:str]
    OIDC_REDIRECT_URI: ENC[AES256_GCM,data:8Slk1pvIFXKtdDAC0L7gipiTcgA55y6EDnRo84b6mm0DMHv5FO8VWEZDBw==,iv:UlBWb8E5swyGxyEAJHYlX2Xp+QyvVAiD1hXgrXQbhSs=,tag:oMbAZqxmjKzbitFoeNGZFQ==,type:str]
    OIDC_SERVER_APPLICATION_URL: ENC[AES256_GCM,data:WbluUOlgfP0isoU5COzMPyK7bljJtp1UkE6X6fURFbO7YkT+RvbhYs8S71qZTQ4CNc9mQA==,iv:PfIJbHvZSfRPqPKawj33vGea9JPlZJb5+Pge7hh+7pQ=,tag:JCY44qwg6nPhQuT9HWwOZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRXFjUGVxVUkrMDUyR0Ni
            WWlBbHdYNlQ0M1J5azl4QUQ3Y0J5ZmFobWxVCmhvVDl3ZlpWbXdUdWJsbkZLOW9u
            L0p1VUNYTmp3MjJYc00rQWVQYlcyaVUKLS0tIGZCalI1M2VtNWxyd0w3bUZkTDJu
            WjVTclFydkt0QTY4bERLRWpuMUpTSVkKJZ6avEaqGgZFojKvPmpmpct8SVKXDfUD
            X0Pc8vs3+BJdszFl2IdVxyYgd0jIeDrzCIibRKvsEfVkAiw0l3e7IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T18:01:19Z"
    mac: ENC[AES256_GCM,data:/kGC1v3H8apkmTznPeK+vE+j/Gi2jz3YaxOZJJiVU7kmycC9zfTk+F3Q/v0koswG17THz/obFzzeSq1hcjPFXtt2NjN5/byHPHfBk7rMpKAn2xLRAHL0UIYnqLeKpOjbKe2J5JFBECbxUlX7FW6Mc9v3RF5/aaecVqM2dvAmIkw=,iv:clgwkjpdUyriK4FP1X0DrcG8GoojWAnGbMj3OK4CAIs=,tag:D3zN/SKKmMG42kZlJm8CuQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
