apiVersion: v1
kind: Secret
metadata:
  name: romm-api
type: Opaque
stringData:
  ROMM_AUTH_SECRET_KEY: 38961b2cb3f1ec3907b976648ea9c03066bd1466275a35b9a021d051e4436800
  RETROACHIEVEMENTS_API_KEY: VXC3hoHEza4YcnTPesyTvA8q6O7QyP9I
  SCREENSCRAPER_USER: almothana1234
  SCREENSCRAPER_PASSWORD: 7uui74gD6NY
  STEAMGRIDDB_API_KEY: 2908294cc2b0000b1729f2205f5d1c29
  HASHEOUS_API_ENABLED: "true"
  HASHEOUS_API_KEY: ONSymwtuLulZx9O0-9NPTflSmmS6kXmGsEePpQpdlviytWXudboT6Ax-_7KQkGw5
  IGDB_API_KEY: 0yikebw6mt14l9hp99hwolfmz6vw8w
  IGDB_CLIENT_ID: gx911vffd9epqpe8zioj298dcef0ta