apiVersion: v1
kind: Secret
metadata:
  name: mariadb
type: Opaque
stringData:
  username: romm-user
  password: GASDtgwexid$ds1f
  host: romm-mariadb
  database: romm-database
  root-password: dfgdfhgwhm2F$ds1f