apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen38-flash-next-leader-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 160Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen38-flash-next-worker-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 160Gi
