apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transmission
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - image: lscr.io/linuxserver/transmission:4.1.1
          name: transmission
          resources: {}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Asia/Riyadh
          ports:
            - containerPort: 9091
              protocol: TCP
              name: webui
            - containerPort: 51413
              protocol: TCP
              name: torrent
            - containerPort: 51413
              protocol: UDP
              name: torrent-udp
          volumeMounts:
            - mountPath: /config
              name: transmission
            - mountPath: /data/downloads
              name: library
              subPath: "downloads"

        - image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.3
          name: oauth2-proxy
          args:
                - --provider=oidc
                - --provider-display-name=Authentik
                - --oidc-issuer-url=https://sso.almothana.sa/application/o/transmission/
                - --upstream=http://localhost:9091
                - --http-address=0.0.0.0:4180
                - --redirect-url=https://transmission.almothana.xyz/oauth2/callback
                - --email-domain=*
                - --insecure-oidc-allow-unverified-email=true
          resources: {}
          env:
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_COOKIE_SECRET
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_CLIENT_ID
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy
                  key: OAUTH2_PROXY_CLIENT_SECRET
          ports:
            - containerPort: 4180
              protocol: TCP
              name: oauth2-proxy

      restartPolicy: Always
      volumes:
        - name: transmission
          persistentVolumeClaim:
            claimName: transmission
        - name: library
          persistentVolumeClaim:
            claimName: plex-library