apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
type: Opaque
stringData:
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:ns6Grkgtm5gpkduVQuMtbLCnlk9jzoQX7YX1kDj8jwRr5jnG5P4WIhoK4AM=,iv:lq1o08ePmMJQFzbwZBWHj21OKtzG5qzd50zMyX0ByG0=,tag:GuBFXOPUuH3s1f3M9jH91g==,type:str]
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:xkchE+51tSZ7Gm3AN/oNZh3AGTqZWHzcVPeoAnJ011CW5jTS6khy1Q==,iv:+dJVa0GcEIL5wTkq295ocH3URyJcWjae/P40Ev/Sj+k=,tag:8oQSUvwUJtan8MfTQKUwQA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:gsE8wKRJJ3LwzTx9p+S9I89c9bft4rnOtaAgx5XMbGXqGiDN0OKahHC7PITB1ChNyo+Kr9O7IOrBwEyAJ2li8aklRA8hGklqZ2DzdqYWoJE61dSsDo8i1T+NyEB9kV8tJ1mTPeDZyjpItH++i8vPTGjzUyi8bS6vqq7lCCoKVGg=,iv:7/QyRvi5Qg24Wn++ms+X/PS+rQTYiv5/QLykoMZ0mzY=,tag:3CKnjUi9qblOaI/q+K/QTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WS9va25UZm53WXV2OWVE
            cXBaZXNONTNESFhxSjVTQmh6bDNTT1lRTGlNClBsOXd3aE15TTlZMUFxcFgzOUhp
            NnBYWHFZOG1zNEYyRzZOV0dzY1UrOHMKLS0tIElhUlhrZGQ4QjZTY2s5ei8yNVZ4
            ZksrR1hmZUdRdi91a3JUZXdmWFdQRU0K4KmQkRrgxxzZ+ukQgtlm8vhuWQ2rPJOz
            F6XuaxbADUJLVJxDw+oranZSgYwFqgiZPELYFLPWZ3Qv6vpvyfwWkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T05:06:22Z"
    mac: ENC[AES256_GCM,data:FHeO+2GutmwTRdeRGSw7HvnRRDe+eD7vZ/a/LRIQpOpVOv6eZI9dwbfbqj3seXauV1DD4eCtC0jEoZFVE8U6Bj9gkXp+4NIn+quFoyFU/K1b9Ejd5MmwhXD72Rizs3txj7av1tldR4cwIU+yIocMBIRuC6H42+8HmhZEE6cBnOQ=,iv:FDSoZ6wFWJodlpTZuCpyxcGw5LFD44q/NyzDpjxEP+Q=,tag:uggAFt5XMEZ3CaLtCIpzaA==,type:str]
    pgp: []
    encrypted_regex: OAUTH2_PROXY_.*
    version: 3.9.1
