apiVersion: v1
kind: Service
metadata:
  labels:
    app: transmission
  name: transmission
spec:
  ports:
    - name: oauth2-proxy
      port: 4180
      targetPort: 4180
    - name: webui
      port: 9091
      targetPort: 9091
  selector:
    app: transmission