apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: '0.15.3'
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 5m
  values: 
    speaker:
      # enable on master nodes
      ignoreExcludeLB: true