apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-tp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm-tp
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 4s
