apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kiwix
resources:
  - namespace.yaml
  - PV-kiwix-library.yaml
  - PVC-kiwix-library.yaml
  - deployment-kiwix.yaml
  - service-kiwix.yaml
  - ingress-kiwix.yaml
