apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-library
spec:
  volumeName: kiwix-library
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
