apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
stringData:
    token: ENC[AES256_GCM,data:7r1J9WaZfbWwCDY+DiqsyhVh3E63vi75TKtG5v4T3EyvqlBDYl1YBno22/2SM4hWl/UwMPWVnse+tU3z0Axqt5xsrRcWCxhyZbOvXMJI5L5a9wtBzY6Ffvr9BmgFC+asVXn27mTl1YY29zd17ZOJVdU428z2/aT/WXHAlYqFS+a4EH2oeGzrC59w5JuV45obeD6jc2gCtsEic4qlR432U5HioirGdV99ie5UFb9JiEhs2UyFkqxZeg==,iv:b37sAzsszbyCdHUerPsdGUHlLc5cBP62aFIYmHbGB88=,tag:+QRSR3043Ck/pEfXc7WT+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZEltQWt6OUtGMlV1WUJZ
            M2xzOS96TTFDYjFFT3pUSW5naVU1K1VPTEg4CmRMdFBmNVhIQ2doMStiQ1dWbFVR
            dGMva0tIUWZvam1FSWdGV3RUUjcxLzgKLS0tIExoS29wL1B6cCtzREVHTU5iTVhJ
            dmE0L0lNVWsrWjVHWGk1YjhLLzRaYk0KhV2jQyNXQimuT6/81uhURw/E8xxrD/dQ
            IEJY/Z4GmGlwKTkxxWrjsIVSFZDzLZ7rOcCG1OVXxfuXJjjb8Da2uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T15:30:53Z"
    mac: ENC[AES256_GCM,data:1Oq3uoTh1XmC4Aky9nXmDgC0TVQZGmbMDGQRgdPAl5/B4uwuYt8NRjahUnv9u3Aro4LTMF23qnrcxOXdUIw5CvT6y5CXhDsecW9UGN7TMoey8wD4NAmXtzhnBtM23ql03RYDDElem+cm2wvYFf+YDaWCED/X2HuGHdccIC9USyY=,iv:u9lDf+yql3qctpjt+0muIuZ6wZ46Shglrs++9lKbGoQ=,tag:RYDw3MnTZaMgIqAlhnAFAA==,type:str]
    pgp: []
    encrypted_regex: token
    version: 3.9.1
