apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-bifrost-keys.yaml
  - PVC-bifrost.yaml
  - deployment-bifrost.yaml
  - service-bifrost.yaml
  - ingress-bifrost.yaml
  - networkpolicy-bifrost.yaml
