apiVersion: v1
kind: Secret
metadata:
    name: bifrost-keys
type: Opaque
stringData:
    #ENC[AES256_GCM,data:87k5X8YtfJnllkXUvbRvXaMAc808yZ46XPGUMT92cZkeScLpAIwXNP7Qijh5MWeBlOilxhHlNnunoe2ksQDimMAt4m2ZyXk3GA==,iv:YTmcqWaCedSkJwf45xTSrvlvfV+49O3DkRjfjdJYZ6k=,tag:JH1JWK7dHwpjsFZ4Ev0f4A==,type:comment]
    BIFROST_ENCRYPTION_KEY: ENC[AES256_GCM,data:oGd6J5GbAHr2+u3YahkyU4XI/GV96TUZ3plor5vYXFfo1OzvgKHkhyxT1a62s8cyT/ISgeeYX/+hvItt5E44nA==,iv:zKfTczFsiUQTxpjHNVNJYuGYj0EIumJoRqqI7PqveEw=,tag:UHvnyB/Oe/JEJDe/QhDKow==,type:str]
    #ENC[AES256_GCM,data:8mcMmL5DBa2ADanGA9FhkbOwygSL534GS70rUu4WNy99cBGLhdtfVm/wWehzGUCJigyAB2Z4WOhmTk4x9uAtbj+Zsqar,iv:a2i0twY957qbEwLqp1/flteQKx+MIOk4Bg/cndnLLY4=,tag:aPhWaaXRUZQCQpu72kBT2Q==,type:comment]
    BIFROST_ADMIN_USERNAME: ENC[AES256_GCM,data:UN3al6Y=,iv:nvOQVKVwRVSBmN21bgsUDUa1N8MeR9Nt/fVWUT5CXL0=,tag:AirXYz/ta/wD2Yu4e/UjwA==,type:str]
    BIFROST_ADMIN_PASSWORD: ENC[AES256_GCM,data:3FN9WaLp3HN5PQi5pRjneMBUwPC/uu6/3pVzexDbDgo=,iv:gPz07rAcj0vUW9Vf/wOySIS1ZHzM0rd2Ge0s8HO15xQ=,tag:lTjikz4cPrHw9cSxtiSbGA==,type:str]
    #ENC[AES256_GCM,data:hEUVwAkpxRxyS70W6pLwINzHrSiP0R1M2GZPWSn54ofKgzLKy5u6b52Ks+sgoj5v92l81iyFJ74qAvCOoQQ=,iv:ADoztXTlKv4a5e1PKIDhIvv4rsxHh6VOzXT4y4rZqm8=,tag:PFtdv8gTd6Q+otbsxlZtuQ==,type:comment]
    BIFROST_VERIFY_KEY: ENC[AES256_GCM,data:X/ULny9vTDF58Nlw3AjFFDElm+oNTcTLcAGS19WZWF/aNMvxqAj4Bjpanuubayzz9clRMnw5,iv:Z5x42Mt+ontEIMJzzHT1xFfYwDL2Lmxm+DJau4lSkEA=,tag:oSR4BMR8D98h5Y18lA1jNw==,type:str]
    #ENC[AES256_GCM,data:adl8HYEukVi84IRmdEv4k6m2qoD+rQzVlvnuhler+XINVA03WzjKqYkkZ8YTquMunY5KSAwjDx0A0+eT3w==,iv:InoQWm7AMB5ZrC4XOpiDOR8CnNaENgoSjHR2Vd4+iTY=,tag:wlnG5zZ0AR7H47BHRiyMmA==,type:comment]
    BIFROST_PUBLIC_KEY: ENC[AES256_GCM,data:rWqZkb81mEc4VDDmZOBewhr03mhCOXD301K9RNuaL6uEgXNhc8g7xFnZbYk4UP7MREXHxHJK,iv:dF5IjLJTpj4TPbxllfE22tWYUphcGa//fjxft76b+hI=,tag:SCz5CQgFupFWA+dtzcTWpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUDN1aXRmYXJmWStCc2RW
            NjRMUzlWZUZWZDZLMjZGa29CaTZCaDlwUjBjCnY0aXZKWGU4WGxaTXZNMkJhWnhv
            a2RyeFdmZFJubWt4dk5HZUlWY1RKaVUKLS0tIDQ5Z29zbklvL3RtSDUwbVFPby9t
            QjY2L3B5aWhob0tqWnN6YWllMGZFbTgKAL2tRhSRxhsZ6LjwuSxG2M+u3RX7vxp8
            xzZIzjjB2mRHkU3p12Bl+22ZrQoMVtb5/hiEUrxGQK2DAoVqSYAqLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
    encrypted_regex: ^stringData$
    lastmodified: "2026-09-27T08:10:57Z"
    mac: ENC[AES256_GCM,data:gNCmqeJzRuhbT70gg9ekDzV4jfjsKKDwr8m4Gbv9YTjNMzJ/Y9axXiFzKKOmkVKcUUwla6gJ/DjETVRGshkQjhNNx+TtIsK85XStQdLqCM0yyJAr1WiZJDgmX4WFKGaRl0M+yt+PB55Hpor252RdrLQgyJRnB33Ilk17rmtCSmg=,iv:Qwz6IWK71PQZ5afgdt0xrJJf7BfSqjYde9kKbMTX6Ok=,tag:iCaVVAQqzD8we0398fUljw==,type:str]
    version: 3.13.3
