apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease-authentik-cluster.yaml
  - secret-authentik-secret.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - networkpolicy-authentik.yaml
  - ../cnpg/networkpolicy