apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:NjO86CqRmCiutdi39pk6zhtZmckU1inGrhOUvF4/w5h90lTFg5xLuOELPEPtJFbK59k=,iv:lLGQIn9TJ0Gjl9kvEKAcQ8KXgNhCSC6Rz7Ct6xVKmbE=,tag:uvI6kYE4Td1XovpZJihWkg==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:ClJBnI5owQYNkzYHofZn6YWq0LhDL/uS,iv:xlELRZaxHtKZkAEAjI8l1qiWSzliuJcYZFN2P7T6xl0=,tag:yuxJ6mADWGrsfBOSKITTgg==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:C8qdTM5/oStUfz7u9vS1pv9PTJcuXpGntdmDC3o7JoqolaqQ1u0rCg==,iv:4HmA3Z/hw9J9b5chVRgJ3XOtBaL6+ej+cViOuYFqvTE=,tag:RtC+j+69T4zrHmN+VBILDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcDY4RW5HV0tlNWZMaTE5
            djhqc3NZN3BhQkxBd2wzTFlCNDVoWkNEMG1ZCmNyTUFRV3JYUy9WcnBpaGRKT3Bk
            U1N1TGJMOC84Vndkc2JSWjJmZnE0M1UKLS0tIERaQmlHQmtYYzFxTUg2WWZQRVpq
            Z2NlQnFQVzA5MzZMZUF0WW9JSUI2aTgKiaxC4tTOzy1hlb1CAROhUj9F+nypBuLp
            QdxpUeJsUnlIkisUpRnyv+wj/fwE7zI6lVnHOpI2Of6Nuv1mK8Unpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T13:50:09Z"
    mac: ENC[AES256_GCM,data:KJh1TiG60WJoNkYURZwlaL8oVuTiem6ZwOR4hss+HAEh6XxEuToOAXywQuy7mwcL1HaRy7ZZzKjbRecVO+vHGdfY3Wwza1863VyoUQNcLXOM/x7oc/pPffLg1/A/+eu+gN6roNyPkhyYVqkyTY+S1nbDUQvXuCnM24hhOmfEvhE=,iv:ChvrmxMVsiqGdZisnYMeLfC4fWGuIKsLeqHlpsrfsHM=,tag:uQXy8vRocvY/uye2DHQx4w==,type:str]
    pgp: []
    encrypted_regex: AUTHENTIK_.*
    version: 3.9.1
