apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:NjO86CqRmCiutdi39pk6zhtZmckU1inGrhOUvF4/w5h90lTFg5xLuOELPEPtJFbK59k=,iv:lLGQIn9TJ0Gjl9kvEKAcQ8KXgNhCSC6Rz7Ct6xVKmbE=,tag:uvI6kYE4Td1XovpZJihWkg==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:ClJBnI5owQYNkzYHofZn6YWq0LhDL/uS,iv:xlELRZaxHtKZkAEAjI8l1qiWSzliuJcYZFN2P7T6xl0=,tag:yuxJ6mADWGrsfBOSKITTgg==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:YI/qFd86qEDiRNU86b+9,iv:byym6MjYMkEa7Eqtx1eC8ZU0q2rAqUrpN0ibATMMwjo=,tag:8lTjDx6ZuvbsRNWoC6k6Jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcDY4RW5HV0tlNWZMaTE5
            djhqc3NZN3BhQkxBd2wzTFlCNDVoWkNEMG1ZCmNyTUFRV3JYUy9WcnBpaGRKT3Bk
            U1N1TGJMOC84Vndkc2JSWjJmZnE0M1UKLS0tIERaQmlHQmtYYzFxTUg2WWZQRVpq
            Z2NlQnFQVzA5MzZMZUF0WW9JSUI2aTgKiaxC4tTOzy1hlb1CAROhUj9F+nypBuLp
            QdxpUeJsUnlIkisUpRnyv+wj/fwE7zI6lVnHOpI2Of6Nuv1mK8Unpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T07:18:44Z"
    mac: ENC[AES256_GCM,data:280Hck8ul5md9cYbiDJQEYuSlaCcYlJVmHyUZB/F8gN7SbDq5/ECRdiYemr9PVIC+3BxoqO45TKkwDw1+QAqfP9HcGiajs3c/YD0jofp189V5aKIO2KNZuxoje5hHjllO4rkatldSaLaSuxe7hp1mXe3sN1eWVlgCVwjWJy4JfI=,iv:007pJyTnz1U2xzkQFXns3jqCNR5jfJVDXh1xZki+9QA=,tag:2X2aqEKdrPUkdusQywwHbA==,type:str]
    pgp: []
    encrypted_regex: AUTHENTIK_.*
    version: 3.9.1
