apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:zFwt0fKYTDh3oQjXO6XvIl7a1YGfFr4+h9Z8feKsi+VeefbO0XB1gJDD1Ux66hHmn9E=,iv:JADxc7Gcc0PtnelsO9ybgiwUgLYoYB1bHM5m9jAkCgw=,tag:tm4Odp9A/6uvFk+aHawiCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZkd5T0QzcEU0UFpjQ0JK
            NTM2WGllRDg0bGtwWEZ3ZVQrQXBaOTJCYW5RCm9XelBuSVEvaUVWeDVEOXNxQ1pC
            NG9qcm4wS21iZVpYZWdQcFpLRzFRNGcKLS0tIHQ0Wk5rQUNVZ0FRRU9JaHQ2cTUw
            anlSRndOVnN6cm9qczd6S1cxUnM2eEUKbWRcv8RIrwRjsYCRTChXgI9OKmBt9Byg
            Y+eq05z0YEv+iUXoLbBr6uzxxNgy9WTaWlat92/03CNiLmIk9Tf2jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T15:07:25Z"
    mac: ENC[AES256_GCM,data:1lvs18HoAJo3I4+btoCYLBu8XrVga9iA4IsE2LuS9p5CO9o0XEu3Mcm8jnloqc8yG5QLWCEs9dT3jJy3eVFRBJHpSQKVZzISYrr4VUBoTrk6jWjkXxB3yVzwZxQxHlHi1zNd2IbhG5/86BpwYY0RjFci+WZlPRvLZtObVrO5B8A=,iv:xELJiDNlBIfGyu1ICTXW4SZUaKORg15/2qfXrFZ+zko=,tag:+iZPrTD0AZwH5A1Njp8Tag==,type:str]
    pgp: []
    encrypted_regex: AUTHENTIK_SECRET_KEY
    version: 3.9.1
