apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 5m
  chart:
    spec:
      chart: alloy
      version: '0.11.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  values: 
    alloy:
      configMap:
        content: |-
          loki.write "default" {
            endpoint {
              url = "http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push"
            }
          }
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: ["alloy.almothana.xyz"]
      tls:
        - secretName: almothana-xyz-tls
          hosts: ["alloy.almothana.xyz"]
