apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bazarr
  name: bazarr
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi