apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-orchestra-secrets-source.yaml
  - secret-ou-tls-certificate.yaml
  - helmrepo.yaml
  - helmrelease-operator.yaml
  - helmrelease-orchestra.yaml
  - helmrelease-login-portal.yaml
  - clusterrolebinding-cluster-admins.yaml

configMapGenerator:
  - name: openunison-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true