apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: orchestra-secrets-source
stringData:
    unisonKeystorePassword: ENC[AES256_GCM,data:3frZx6SvOSJB6id0Le7EBh5Rfg==,iv:eWHVzuQhZopL6/wTZgJ2ab/WRx620rVDxaz0D3PAsV4=,tag:OZ5K/ylEvaT3p2yGNGMh0g==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:mxp8swRqbHd7NP3NRY/j4ciVwm1BxK//cS9jARW7ZVOmhJbU77ovzA==,iv:LT7/ZQbVm9GlWD1glxj23WFEtDt36sImfvUBzLp4Bog=,tag:8PLHQuFcLMrGpaXXmfKBKQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:TOQJHyPOLHfSUoipbYKNjO/hGas3hNjq7IIuAkHRtVyL3MiIyJ0GodW2W3jh7ANf1zVRG5xXEaQk+Jug6t4c9Vh8tysCVQ6WBKBdzPGNmJPX/pDWQsmhTN9CDLb4yqwEQVvrcupvyDWUih/hlEyM76YF2emlBHQfZX2Pla79oBg=,iv:OgfspLokFh5s+FLw2y0do2SwPFRqfd78tnBAyKerSOM=,tag:uGH5ZHFl6QgWRFt2fjCOzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS1RRcnViNUdVRk9TRXNU
            SWl3a1MxTmdFTGgrMnRhQU9ackJsaHhzbEQwCjVsZjN0UCtveWttcS92OE9TR0Jy
            YVhXZmRISmNoR0YzVGJXYVlEVVhNM1kKLS0tIFFUcTZRZXBsTEhodEdzNmlKd2xX
            bzN5WGxSQjdmQTVjdTNJOHAwcU1TbTQKEm7B/l2ZCpbarBCvXetp2xr2MbioJzy/
            zdUR3z2kpyhjSb1aq5kv40QIjPLZ7a9sVNqUvEsL/rmB3TfFxRQuYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T15:02:16Z"
    mac: ENC[AES256_GCM,data:bWm9KUcV3lDeSpWFkE/3A1FXb0r56EJmwzdP9T4YRqFl+iRfRgIdd8OghzY8peYxmHr6rCk1CnS+5CwB2+wFgvh6ahg6r6OQLp5J/l/r9RS8Bh8PJK68nRA0/T7WrJ0AeB/1/4ul7jQqYjKgGeR3IVpxMQemq0cgAhs8SQ30iJU=,iv:jUWEM+BhKhopilGLDzZf6HufXgXCBKX2gR8s9t770Lc=,tag:I9io2mYyjj/2KyBtL17o0w==,type:str]
    pgp: []
    encrypted_regex: unisonKeystorePassword|OIDC_.*
    version: 3.9.1
