apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: orchestra-secrets-source
stringData:
    unisonKeystorePassword: ENC[AES256_GCM,data:3frZx6SvOSJB6id0Le7EBh5Rfg==,iv:eWHVzuQhZopL6/wTZgJ2ab/WRx620rVDxaz0D3PAsV4=,tag:OZ5K/ylEvaT3p2yGNGMh0g==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:mxp8swRqbHd7NP3NRY/j4ciVwm1BxK//cS9jARW7ZVOmhJbU77ovzA==,iv:LT7/ZQbVm9GlWD1glxj23WFEtDt36sImfvUBzLp4Bog=,tag:8PLHQuFcLMrGpaXXmfKBKQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:lgnQu24wmZBkvULNdKmf56A0k+13HGlf742YSxDMnyh2+t/LO/wwIQ==,iv:atlSYt6vl1nizhliYzTm67nvhcjCP9RA95S6dBqjmbE=,tag:FlnIO2d2MNSJOUKddFq5Zw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS1RRcnViNUdVRk9TRXNU
            SWl3a1MxTmdFTGgrMnRhQU9ackJsaHhzbEQwCjVsZjN0UCtveWttcS92OE9TR0Jy
            YVhXZmRISmNoR0YzVGJXYVlEVVhNM1kKLS0tIFFUcTZRZXBsTEhodEdzNmlKd2xX
            bzN5WGxSQjdmQTVjdTNJOHAwcU1TbTQKEm7B/l2ZCpbarBCvXetp2xr2MbioJzy/
            zdUR3z2kpyhjSb1aq5kv40QIjPLZ7a9sVNqUvEsL/rmB3TfFxRQuYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T14:59:17Z"
    mac: ENC[AES256_GCM,data:NXXZzcmnR4ppyjH6Z1hZkU7AcbIpP+d73SuLw8XqkP9iTjs2ZnR3B5jQtKTqMinfrloxkvIJGufRC5KXK5KWBKRbTKLebzInA5FdRYCKSbUtP3k5dYq3avNnUEQRLsewRDjgdmbbSwnCPXQ4U1TENhy0HY2ePg4nmEdKP0Gx1i8=,iv:rj43aKI6mRAorSkvqOSaBizi2/BJJkf60Q33Uvpq0Mc=,tag:m9GPjheJoajAI98SQnS93Q==,type:str]
    pgp: []
    encrypted_regex: unisonKeystorePassword|OIDC_.*
    version: 3.9.1
