apiVersion: v1
kind: Secret
metadata:
  name: ou-tls-certificate
  namespace: openunison
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "cert-manager/almothana-xyz-tls"
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""