network:
  openunison_host: "k8sou.almothana.xyz"
  api_server_host: "k8sapi.almothana.xyz"
  k8s_url: https://192.168.0.60:6443
  session_inactivity_timeout_seconds: 43200 # 12 hours
  createIngressCertificate: false
  ingress_certificate: "almothana-xyz-tls" # this key is in the docuementation but the chart doesn't use it...
  force_redirect_to_tls: false
  ingress_type: simple
  ingress_annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/ssl-services: openunison-orchestra

enable_impersonation: false

k8s_cluster_name: homelab

# Get the CA from kubeconfig/talosconfig
trusted_certs:
- name: k8s_master
  pem_b64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQU5KRnVSUUZDMUk3WUxNYVNMczI4amt3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakF6TURZeE9URTBOVGhhRncwek5qQXpNRE14T1RFMApOVGhhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVM4WmRyRkNFZ21LZktJZGRmY0VrUXBwb2Uxb05FbEo3MWplNFZUKzc1dXYxTFVJUlNEMlB0VDIrTGgKSmVrTHQ5cGx3a0cydlhsSllRb1p4MkppalZQM28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGTXB6ZWh1eVVnTXhaUkpFRkVtZURUVUFtZzAxTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDbjlRR0UKMmRxa1VhalZXYlRaZjdqOGZuL2lXZWN0VU5sdGplUURqYkIySUFJZ1dicWNnZU8rZnp2Uy9ta0tpY0Z4dlQyMQp2NU10bGY5NjhYRnlETExmWVVrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

oidc:
  client_id_is_secret: true # get the client ID from the secret
  issuer: https://authentik.almothana.cloud/application/o/openunison/
  user_in_idtoken: true
  domain: ""
  scopes: openid email profile groups
  claims:
    sub: sub
    email: email
    given_name: given_name
    family_name: family_name
    display_name: name
    groups: groups

openunison:
  # only users of these groups can login
  az_groups: 
  - k8s-admins 
  - k8s-users
  auto_timestamp: false
  force_update: initial-deployment-2

# disable the k8s dashboard. use Headlamp
dashboard:
  enabled: false
headlamp:
  enabled: true