apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale
      version: '1.78.3'
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 5m