apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    oauth-client-id: ENC[AES256_GCM,data:IOxUt/Tphs2MX3y1WCURLLY=,iv:9x6PdaEOVYUbO+9klw2vgYLe923UFhBbHVlwMT4UPSI=,tag:+w0sj9/zzh1JRKPBqf0bzg==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:O7j5nY1j2kvY52cgg0CorYMGR4gsMYrk37sAMyFoXCA5xMwKeIZzXD4/+2pyJQMS1rKy3cO5SEa7e1INTZ01,iv:r0MQFKQhnZwrvB6Nggl8rLw6sSNNlVrvLPO51Bc9iEI=,tag:aGP2FuYgxo4khUSC8jtzrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVlRSRFdwNlpUUW1tc0FL
            eFFLUDBOVmJ5aHJpWVJiNS9qRGhOREh6NzE4CmpYeEs2QW13RmtoTHczWG90RTdl
            YnNnOGptdHp1UlJvQWRyam9wSWZoZzQKLS0tIDFXVzZkREpaQnJweHVldDlzeEht
            d3FqWjIrT2J1dnorWkxUNkhUcFloTUkKb6HhbTS/hldpE0Mf+qJkRZnNaKlNvMX+
            GQsrMZ17ewY5xem8ogCKGYtz9k5WespGcxY7g7n2Vsc404E0jyJFTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T11:42:58Z"
    mac: ENC[AES256_GCM,data:z5Pw7qGuPSakPp9uqHuLnsC4Ug8tU0evIVyDsmtMvUSaD7yGW0OIbNO3SpXkenMwHsmmU1fsLaHYOVjD4tNsg3GYkeHVu6DKovuD+ZsNqV4HUMP53b5yGVlYd/F/SSFZ5Y0gVKIYRhXuh1f4tYHG3MOw8juqV4NHwb4/3+2xxDw=,iv:J1UNgerSrMrjxIhx+MxEIqP8B/wB7rTy6XW5hYl7+5Y=,tag:NbYKuFuBSi3YryE8kG7xnQ==,type:str]
    pgp: []
    encrypted_regex: oauth-client-id|oauth-client-secret
    version: 3.9.1
