apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: external-dns
  values: 
    provider: pihole
    pihole:
      server: "http://pihole-web.pihole.svc.cluster.local"
      secretName: "external-dns"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 50Mi
      limits:
        cpu: 150m
        memory: 192Mi
        ephemeral-storage: 2Gi
    extraArgs: 
      # Switch to pihole V6 API
      - --pihole-api-version=6
