apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: "8.6.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 5m
  values: 
    provider: pihole
    pihole:
      server: "http://pihole-web.pihole.svc.cluster.local"
      secretName: "external-dns"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 50Mi
      limits:
        cpu: 150m
        memory: 192Mi
        ephemeral-storage: 2Gi
