apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-dns
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
  ref:
    tag: "8.8.0"