apiVersion: v1
kind: Secret
metadata:
    name: adguard-configuration
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:bGa6CEg3SoUOTwuF9JHzX0fx,iv:A1qnqmWRvOCjci5pl0sqUIrbZmT+90vkJqi5vNmQtns=,tag:yTKSvY43AixTvK3GWPEJPA==,type:str]
    user: ENC[AES256_GCM,data:FOXzaxY=,iv:HqpQubFGJqMd25fC4HVxGkVgsW/tNdBBEV9AUpSQ04U=,tag:MqmIQzLPjkkIJlVOjmotdQ==,type:str]
    password: ENC[AES256_GCM,data:JG/e8p4rVjk9mgLwSOKV,iv:HI8p2ge2yP02DVnBYLp6IDq4liKg8t8JE4coZyI94Wk=,tag:jYlisS7CXXgSGe/hMUgthg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdm5DVE1Sb3hoVHVSbGJ5
            ZmowR2NYMXRzWVZkR0tSUnRvUFF2NHRpazJRCkNrcE1ha1dRTmZQU3ZOTEpkNkds
            ZVNlQXhUSFUyK3hMY0xlOFRUNkIvajAKLS0tIC80VEJUK25UL0l0YnVJTzd0RzQ1
            Z0VVMW5rY0J3YlRsZVNMN3E4VVdiNDQKN0EHkZ/vGU23V4R4cjr2ELe/QTUTsIl6
            K9i5LxGYGgJhuQ3l6ZVSdGgJbCrPJxGHXCJ7b7ocr1o+tPS4OvhEXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T13:37:29Z"
    mac: ENC[AES256_GCM,data:6dLpZbRcvoT1z1Rhfg5hAbnqaakg1HwMX6NAlXAd3+Vp3641gBJvu97FtSkxbJfaxurQxIUgNz4zZD4GozUNL3XzZxcHL+yEz2ILxFD4Ym9BD16FONXXxAljglUHnHx4Vxhk+XuhxIkb9M6PDHFUlJ0UA0y1dIG13VZ+XnQs/+M=,iv:QEPIWauk387KxC77WJhdYv7zMHxWN04oy3KZQKQTFoo=,tag:bt8Ol0v89WnQjOScH0ZIGQ==,type:str]
    pgp: []
    encrypted_regex: url|user|password
    version: 3.9.1
