apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pvc-usage
spec:
  groups:
  - name: pvc-usage.rules
    rules:
    - alert: PVCUsageHigh
      expr: |
        (kubelet_volume_stats_used_bytes{job="kubelet", namespace!=""}
         / kubelet_volume_stats_capacity_bytes{job="kubelet", namespace!=""}) * 100 > 80
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "PVC usage high ({{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }})"
        description: |
          PVC {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }}
          is using more than 80% of its capacity.

    - alert: PVCUsageCritical
      expr: |
        (kubelet_volume_stats_used_bytes{job="kubelet", namespace!=""}
         / kubelet_volume_stats_capacity_bytes{job="kubelet", namespace!=""}) * 100 > 90
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "PVC usage critical ({{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }})"
        description: |
          PVC {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }}
          is using more than 90% of its capacity