apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-cluster
spec:
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
  interval: 5m
  chart: 
    spec:
      chart: cluster
      version: '0.3.1'
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
      interval: 5m
  values:
    type: postgresql
    mode: standalone
    version:
      postgresql: "16"
    cluster:
      instances: 2
      primaryUpdateStrategy: unsupervised
      storage:
        size: 2Gi
      pg_hba:
        - host all xormon 10.244.0.0/16 md5
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
      roles:
        - name: xormon
          ensure: present
          comment: XORMON monitoring
          login: true
          superuser: false
          passwordSecret:
            name: xormon-auth
          inRoles:
            - pg_monitor
    backups:
      enabled: false