apiVersion: v1
kind: Secret
metadata:
    name: speedtest-db-credentials
    labels:
        cnpg.io/reload: "true"
stringData:
    password: ENC[AES256_GCM,data:r//87cp4B5mYY1c3QJWlPkvpK/fbZr0w9T+rSqSPDTvgFPwxLKb1Ba6hd+UzgkHcy7PKUHvfNH3o9Z3iY/6XFw==,iv:3pb15W0kEDUyUpfUTTO36gMWyhuJ8uIvzolb9pwv45Y=,tag:bY5+upeVMxMrepV8saV33g==,type:str]
    username: ENC[AES256_GCM,data:/Uhkm5Wk30w7,iv:wIWsPxZYDHsCI0trQl/yFxHnif3ixzipbUtKXk+lUAU=,tag:XmtpMAdBomNK6T0Wi7/2Hw==,type:str]
    dbname: app
    port: "5432"
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUjMzSTd2cTZhUTBGQkI2
            UGpzcm8xRG82V1E4UWI1YW5OSTdrVklPdVNvCnlrVmlud2oxQkNab2pKd3BRTEtG
            K2NRWVg4b2d4b3RINTlONU52am5SUjAKLS0tIHhsaGVGMXVnTnNHRmxmTW1POC83
            UHBlaVJZMzVSSjBaNWtBQkFEWG95cDAKjvskFUelHjHO7aE7wXhFmrpHJ4kIKoE/
            B/94ZmPngOqXcmrnjbMk4rQ5Ql1fby05jk2ZXLcJcdTGx+rO1QoSbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-18T03:50:43Z"
    mac: ENC[AES256_GCM,data:HktDTDSqMdmbj/EJnX+fovdBKE3W+k+bLIbrxgkDwYOL3X9Qp2nGTzgyvCOkAClIOE+xrlGgu9hURsqiaI2HK1uSb/3tplY/wz5AIh1dyOn6LmveBm6o1H/KdYEaIVq/2A2IZ3dt+l09pgicdVmA2HX4wMt0l1rlVKdDGftPtx0=,iv:GPFCdHLi9A4Oqc5kjaZpXkQi5bjiS7tUEwRwBfWKiSs=,tag:kA+aMyjXVKq2nnVKOcGVVQ==,type:str]
    pgp: []
    encrypted_regex: username|password
    version: 3.9.1
