apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamo-qwen3-06b-cache
  labels:
    app.kubernetes.io/name: dynamo-qwen3-06b
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
