apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/ocis
      sourceRef:
        kind: GitRepository
        name: ocis-charts
  values:
    image:
      tag: 8.0.4
    externalDomain: ocis.almothana.xyz
    ingress:
      enabled: true
      ingressClassName: cilium
      annotations:
        ingress.cilium.io/loadbalancer-mode: shared
      tls:
        - hosts:
            - ocis.almothana.xyz
          secretName: almothana-xyz-tls
    secretRefs:
      # @schema
      # type: [string, null]
      # required: false
      # @schema
      # -- Reference to an existing collaboration service WOPI secret (see ref:Secrets#secrets). Not used if `features.appsIntegration.enabled` equals `false`.
      collaborationWopiSecret: onlyoffice-wopi-secret
      ldapSecretRef: ocis-ldap-bind-password
    features:
      externalUserManagement:
        enabled: true
        oidc:
          issuerURI: "https://authentik.almothana.xyz/application/o/ocis/"
          userIDClaim: sub
          userIDClaimAttributeMapping: userid
          accessTokenVerifyMethod: jwt
          # map Authentik groups to oCIS roles
          roleAssignment:
            enabled: true
            claim: groups
            mapping:
              - role_name: admin
                claim_value: ocis-admins
              - role_name: spaceadmin
                claim_value: ocis-spaceadmins
              - role_name: user
                claim_value: ocis-users
              - role_name: user-light
                claim_value: ocis-guests
        ldap:
          writeable: false
          uri: "ldap://ldap.authentik.almothana.xyz:389"
          insecure: true
          bindDN: "cn=ocis-bind-sa,ou=service-accounts,DC=ldap,DC=goauthentik,DC=io"
          useServerUUID: false
          refintEnabled: false
          passwordModifyExOpEnabled: false
          user:
            baseDN: "ou=users,dc=ldap,dc=goauthentik,dc=io"
            scope: sub
            objectClass: user
            filter: "(|(memberOf=cn=ocis-users,ou=groups,dc=ldap,dc=goauthentik,dc=io)(memberOf=cn=ocis-admins,ou=groups,dc=ldap,dc=goauthentik,dc=io))"
            userNameMatch: none
            schema:
              id: uid
              idIsOctetString: false
              mail: mail
              displayName: displayName
              userName: cn
              userType: ownCloudUserType
          group:
            baseDN: "ou=groups,dc=ldap,dc=goauthentik,dc=io"
            scope: sub
            objectClass: group
            filter: "(cn=ocis-*)"
            schema:
              id: cn
              idIsOctetString: false
              mail: mail
              displayName: cn
              groupName: cn
              member: member
        autoprovisionAccounts:
          enabled: false
      appsIntegration:
        enabled: true
        wopiIntegration:
          officeSuites:
            - name: OnlyOffice
              product: OnlyOffice
              enabled: true
              uri: https://onlyoffice.almothana.xyz
              iconURI: http://onlyoffice.onlyoffice.svc.cluster.local/web-apps/apps/documenteditor/main/resources/img/favicon.ico
              insecure: false
              disableProof: false
              secureViewEnabled: false
              disableChat: false
              ingress:
                enabled: false
    services:
      authapp:
        persistence:
          enabled: true
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          size: 1Gi
      idm:
        persistence:
          enabled: true
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          size: 1Gi
      nats:
        persistence:
          enabled: true
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          size: 1Gi
      ocm:
        persistence:
          enabled: true
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          size: 1Gi
      search:
        persistence:
          enabled: true
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          size: 1Gi
      storagesystem:
        persistence:
          enabled: true
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          size: 1Gi
      storageusers:
        persistence:
          enabled: true
          existingClaim: storageusers-nfs
      # thumbnails:
      #   persistence:
      #     enabled: true
      #     storageClassName: openebs-hostpath
      #     size: 1Gi
      web:
        persistence:
          enabled: true
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          size: 1Gi
        config:
          oidc:
            webClientID: web
            webClientScope: openid profile email groups offline_access
    http:
      csp:
        directives:
          connectSrc:
            - "'self'"
            - "https://authentik.almothana.xyz"
          scriptSrc:
            - "'self'"
            - "'unsafe-inline'"
            - "'unsafe-eval'"
          fontSrc:
            - "'self'"
            - "data:"
          frameSrc:
            - "'self'"
            - "blob:"
            - "https://authentik.almothana.xyz"