apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storageusers-nfs
spec:
  volumeName: storageusers-nfs
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Ti
