apiVersion: v1
kind: Secret
metadata:
    name: ocis-ldap-bind-password
type: Opaque
stringData:
    reva-ldap-bind-password: ENC[AES256_GCM,data:n1ULnEpAyhy/O49N,iv:G3wpV6y2c7FJcxZdwpiHfLta3iE6KjLHYVsNTtalMNw=,tag:NcPR5RXDii2ga2YGbpFhpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdFM1Q0FLM0JkTkNFWVR0
            UzVreFBoUEIzUjFUMVdLZ1JEOWFTcHd4TWtRCkVMN1VybmFZZ01lcjE2TEFxa3JT
            cHJXYXFsVU4rNm1hd3AzT1VTS2sycFUKLS0tIGdNdTk3L1plVHZnaStERTh5OGty
            ZE5UL2JhOXN2Vm14c3ZPOXMwZmFmbDAKw8ZL74+fk/xDAVefDVUYJs+PAJHKKrnS
            Zvl6hbC4av0f8zYJEJP4X674ug2aeLvcwixJE9JqOE67IjLOFUmf/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T14:26:15Z"
    mac: ENC[AES256_GCM,data:PVVv8lO5FS3f4B5KzgfzEUnGkIGhZkQhUD880qDaRUZ0zWg6y5xWxjuhXkx3aawPgppZis8yULW8H9LduvHf0OOYltIB9Chkmu38HmG5Buj4VmHYg7sshR6I8L7QceCRcdeoPFzC0JgxVLAsG3KbPLBvMYkWg8J1W/SJaTO/c3s=,iv:BOe4BKz6x6icjqhdUFXxxHMBp2zil7T6EfAoh8skRkI=,tag:DxstQrccIAbjriX1cV5sXg==,type:str]
    pgp: []
    encrypted_regex: reva-ldap-bind-password
    version: 3.9.1
