apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - PVC-bulwark.yaml
  - configmap-bulwark-env.yaml
  - secret-bulwark-env.yaml
  - deployment-bulwark.yaml
  - service-bulwark.yaml
  - ingress-bulwark.yaml
  - namespace.yaml
  - volsync.yaml
