apiVersion: v1
kind: Secret
metadata:
    name: restic-config-tracktor-1
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:fbmQ7ihUiXuIbyRwXiGD6vHf+JMegwYh1pv/Xbnl9qKa+WJ7K0NtecgVdaOM3A==,iv:9wz4+nuREuy2MR3cYEWgKsz+6bIFi6DK7pGQ2cjg6zM=,tag:tEt4I0GA3jVRIHzp/VaIdA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:55dIlq5fYwIrPCW2BArBTGf9,iv:Lw+3s3cBmqM526oaZWG9LM9RVWLo6x/daZTeY5RGWfc=,tag:o3W2fqySDdGISzApetZD+w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zGFc5Vto,iv:SNeU/YXaxhe7UMn1ZHKPtGGMT5ntzj9WGa0Y3fTgXcE=,tag:soPSRmBkoA/glGho43gQ+A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mRaqw3Od9E1ExhbL,iv:C9+Z/1aj738HiG9A/9KOa24olrEpuwYhRMZ15f5hnSw=,tag:2o6S8TmThSlX11N7jnvIJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:44:28Z"
    mac: ENC[AES256_GCM,data:MUXKznd4mZcjre/OAdC1O3+DbYiEcI9Jl639L8XQ8eepIXdWwIN1Q238mtbyATFxICmXfpsVS9/IPlXinW0Zm2fpduSIfuZN4HLA30TBE+MjyecVueA2aK+FVwNGpViodPrzYSGOcFgvEGwZOs6q8seix68TIvJ85Grt3VUpTGw=,iv:5Wl1IdxVIv+WgpR7TVtwjWExLV6zQpzTmbf7s7jt2kQ=,tag:6EP/M50eFIQ4CgoaWb8+pQ==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
    name: tracktor-1
spec:
    sourcePVC: tracktor-1
    trigger:
        schedule: 0 22 * * *
    restic:
        pruneIntervalDays: 7
        repository: restic-config-tracktor-1
        cleanupTempPVC: true
        cleanupCachePVC: true
        retain:
            hourly: 1
            daily: 1
            weekly: 1
            monthly: 1
            yearly: 1
        copyMethod: Direct
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:44:28Z"
    mac: ENC[AES256_GCM,data:MUXKznd4mZcjre/OAdC1O3+DbYiEcI9Jl639L8XQ8eepIXdWwIN1Q238mtbyATFxICmXfpsVS9/IPlXinW0Zm2fpduSIfuZN4HLA30TBE+MjyecVueA2aK+FVwNGpViodPrzYSGOcFgvEGwZOs6q8seix68TIvJ85Grt3VUpTGw=,iv:5Wl1IdxVIv+WgpR7TVtwjWExLV6zQpzTmbf7s7jt2kQ=,tag:6EP/M50eFIQ4CgoaWb8+pQ==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
    name: tracktor-1
spec:
    trigger:
        manual: restore-once
    restic:
        repository: restic-config-tracktor-1
        destinationPVC: tracktor-1
        copyMethod: Direct
        cleanupCachePVC: true
        cleanupTempPVC: true
        moverSecurityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:44:28Z"
    mac: ENC[AES256_GCM,data:MUXKznd4mZcjre/OAdC1O3+DbYiEcI9Jl639L8XQ8eepIXdWwIN1Q238mtbyATFxICmXfpsVS9/IPlXinW0Zm2fpduSIfuZN4HLA30TBE+MjyecVueA2aK+FVwNGpViodPrzYSGOcFgvEGwZOs6q8seix68TIvJ85Grt3VUpTGw=,iv:5Wl1IdxVIv+WgpR7TVtwjWExLV6zQpzTmbf7s7jt2kQ=,tag:6EP/M50eFIQ4CgoaWb8+pQ==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
