name: Setup tools
description: Install tools for the project using Aqua
runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@v4.0.4
      with:
        aqua_version: v2.29.0
    - run: aqua i -l
      shell: bash