# yaml-language-server: $schema=./values.schema.json

replicaCount: 1

persistence:
  data:
    enabled: true
    size: 3Gi

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: lubelogger.almothana.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: almothana-xyz-tls
     hosts:
       - lubelogger.almothana.xyz

# not using a mail server
secret:
  create: false
  name: ""
  emailServer: ""
  emailFrom: ""
  port: 587
  username: ""
  password: ""