# yaml-language-server: $schema=./values.schema.json

replicaCount: 1

persistence:
  data:
    enabled: true
    size: 3Gi

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: lubelogger.almothana.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: almothana-xyz-tls
     hosts:
       - lubelogger.almothana.xyz

secret:
  create: true
  emailServer: "localhost"
  emailFrom: "blackhole@localhost"
  port: 587
  username: ""
  password: ""