apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - PVC-upsnap.yaml
  - deployment-upsnap.yaml
  - service-upsnap.yaml
  - ingress-upsnap.yaml
  - volsync.yaml
