---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 30Gi
  monitoring:
    enablePodMonitor: true