kind: ConfigMap
apiVersion: v1
metadata:
  name: xormon-privileges
data:
  xormon.sql: |
    GRANT SELECT ON pg_stat_bgwriter TO xormon;
    GRANT SELECT ON pg_stat_database TO xormon;
    GRANT SELECT ON pg_stat_activity TO xormon;
    GRANT SELECT ON pg_locks TO xormon;
    GRANT SELECT ON pg_cursors TO xormon;
    GRANT SELECT ON pg_stat_progress_vacuum TO xormon;
    GRANT SELECT ON pg_stat_replication TO xormon;
    GRANT SELECT ON pg_stat_wal_receiver TO xormon;