apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster
spec:
  dependsOn:
    - name: cloudnative-pg
  interval: 5m
  chart:
    spec:
      chart: cluster
      version: '0.2.0'
      sourceRef:
        kind: HelmRepository
        name: cnpg
      interval: 5m
  values:
    type: postgresql
    mode: standalone
    version:
      postgresql: "17"
    cluster:
      instances: 2
      imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:17.2
      primaryUpdateStrategy: unsupervised
      storage:
        size: 10Gi
    backups:
      enabled: false
    monitoring:
      enabled: true