apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  # must add the namespace for renovate to detect changes: https://docs.renovatebot.com/modules/manager/flux/#helmrelease-support
  namespace: cnpg-system 
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts