apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster
spec:
  dependsOn:
    - name: cloudnative-pg
  interval: 5m
  chart:
    spec:
      chart: cluster
      version: '0.2.0'
      sourceRef:
        kind: HelmRepository
        name: cnpg
      interval: 5m
  values:
    type: postgresql
    mode: standalone
    version:
      postgresql: "16"
    cluster:
      instances: 2
      imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.1
      primaryUpdateStrategy: unsupervised
      storage:
        size: 10Gi
      postgresql:
        shared_preload_libraries:
          - "vectors.so"
      pg_hba:
        - host all xormon 10.244.0.0/16 md5
      monitoring:
        enabled: true
      roles:
        - name: xormon
          ensure: present
          comment: XORMON Monitoring
          superuser: false
          inRoles:
            - pg_stat_bgwriter 
            - pg_stat_database 
            - pg_stat_activity 
            - pg_locks 
            - pg_cursors 
            - pg_stat_progress_vacuum 
            - pg_stat_replication 
            - pg_stat_wal_receiver 
          passwordSecret:
            name: xormon-auth
    backups:
      enabled: false