apiVersion: v1
data:
    username: ENC[AES256_GCM,data:D5UyO+YnCKAJ+mdR,iv:CvEM6UeuRRFACwyDiN8N5YKX840JnfwdtGz6TG8AGrU=,tag:0e9CmPhSUBF0bO1hkdYNWw==,type:str]
    password: ENC[AES256_GCM,data:h10u6YS/7fdnNgYBc3jKXA==,iv:oPxEVeVXdJU6SuVpZqTE9Uz3jpmtygtaZTs6lRPRaNk=,tag:M5Z9hFh55GmkaygKo6E91Q==,type:str]
kind: Secret
metadata:
    name: xormon-auth
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: speedtest-tracker,immich,media,nextcloud,authentik,lubelogger,stalwart,invidious,open-webui,litellm
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: speedtest-tracker,immich,media,nextcloud,authentik,lubelogger,stalwart,invidious,open-webui,litellm
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTm1PK3hZcUt1SlZQSkJt
            cjAxeDhlQ1hNNTVqdW9PUmJBNmlVd05LSXpVCnpFQ2FJdzB2bS9PS0FCWjNkOGtq
            bHlZMjJOK2tCb1ZLaWx4RVpJa0tIYTgKLS0tIDlUeXRMbWRvcVpLMG9udXVBbHBv
            NTEvUE41MW9acFA1UUlwaVBPdXZyUEUKXoy+0qPI4ifnWcy09J04VgDujcoihu+m
            vAIYGPwIYI0oxBNo+FEEZuln7IUGwTyd4ZMnjF/JF6Q/DCcWF8WAWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T10:00:21Z"
    mac: ENC[AES256_GCM,data:GPKN4Jvvo5dyPVXmAM4o+5ZwgL25lOE9blz6n57YRefyyv0UppKCM+COYS8SVeYusMrYzyrrfKCX/QlUkApWc7PY0c7rUlXSVtzQCzNmk6CKdSnVurUB9tg4kT+6QC+MBLh+QNKmVJqnrUux2zYaWiw/sAq/joQuEJmxcDuM73s=,iv:UoDENT3OvLEdvvQmcq3E7948Qb2axDHp/Zddr3mpaXc=,tag:8ppxYAwXG+Gx4Avwea/NWw==,type:str]
    pgp: []
    encrypted_regex: username|password
    version: 3.9.1
