apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-credentials
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: speedtest-tracker,immich,media,nextcloud,xormon,authentik,lubelogger,stalwart
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: speedtest-tracker,immich,media,nextcloud,xormon,authentik,lubelogger,stalwart
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:fHtPc9b2,iv:8apx+4zCgkDJv7137ntOYRtPtVOhvaDJ1ziHJDHEMaA=,tag:Op88QQ5lzFnhxt9lqSKE0A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:aHjzMAuNfGwfeZ2a,iv:T9qYvnj1GYIiBXitz+E6cSgZo+EN0DSLL494VkF5XKs=,tag:bkWE/BwqLcuadmT4vyst8g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRY1p3Z3JHRFFSS3JwdkVh
            RDRVZ2MwU3N0YWM3RTRpTlFtV3lzUUdaNW00CmpQZFI1cnE4YlFUZ2dEWWdHYVVH
            RWtXQU9kdzJJU0U3bUEwdXgyVkxmYUUKLS0tIFkyNGkxVkQwSENja3g0WjhyUURt
            ZVRkN1lMbDNHaitFdzBiZlhmV25MeGMKucm6I00YkCidHmCJn9jChaZJi4y2C2ck
            v89x1SjoTl8xttSvLHu8UTUzwGN3kxB6tf1tahVtt6Z/wiC5h9pE7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T16:21:32Z"
    mac: ENC[AES256_GCM,data:PTm0OZfkVBa6dcSdDBHzASisbgUSJNJyJCeZrRkDHnxYCaIhFP3pOfnEbJH9630CuFH4QBagyUn6Xo5Vsw29krAyPe4N1wuVJwRMu56nwC9vMeiEiT9AyoCOcT2cst8YtAJlqDv8q0JCOzyKLdh1MgTukSI92FOZuv7LbNTcs3k=,iv:lGa3rTZwPt8sa1E2LLU+PuL/oqxrSCK4hwn8lg/YKHM=,tag:axJfFFp+tkLrwRZv89sK1A==,type:str]
    pgp: []
    encrypted_regex: ACCESS_KEY_ID|ACCESS_SECRET_KEY
    version: 3.9.1
