apiVersion: v1
kind: Secret
metadata:
    name: backup-s3-credentials
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: speedtest-tracker,immich,media,nextcloud,xormon
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: speedtest-tracker,immich,media,nextcloud,xormon
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:fHtPc9b2,iv:8apx+4zCgkDJv7137ntOYRtPtVOhvaDJ1ziHJDHEMaA=,tag:Op88QQ5lzFnhxt9lqSKE0A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:aHjzMAuNfGwfeZ2a,iv:T9qYvnj1GYIiBXitz+E6cSgZo+EN0DSLL494VkF5XKs=,tag:bkWE/BwqLcuadmT4vyst8g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRY1p3Z3JHRFFSS3JwdkVh
            RDRVZ2MwU3N0YWM3RTRpTlFtV3lzUUdaNW00CmpQZFI1cnE4YlFUZ2dEWWdHYVVH
            RWtXQU9kdzJJU0U3bUEwdXgyVkxmYUUKLS0tIFkyNGkxVkQwSENja3g0WjhyUURt
            ZVRkN1lMbDNHaitFdzBiZlhmV25MeGMKucm6I00YkCidHmCJn9jChaZJi4y2C2ck
            v89x1SjoTl8xttSvLHu8UTUzwGN3kxB6tf1tahVtt6Z/wiC5h9pE7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T13:48:12Z"
    mac: ENC[AES256_GCM,data:WamcSLA/OiuYEC6ZBd0I5CuC6Z3fAtKyzJOAJOtJYEOTgf7Mc6OOOuypONDRYZbVYxFQ1UljUa5imUHJCxzYCqktTdJjQk7hwIdFnknpcvV7/vxa3el/sfYzsg2hORIB4lPjeQVNtBxLKsX8XAVLoejPF1C2Mhf4lh+N4kW343I=,iv:E3+urdmER7reqZ+18KLpNJL98HStqbwNnCZ/GMkv1GE=,tag:2jgLBLoPDslJdaa5JGwjvA==,type:str]
    pgp: []
    encrypted_regex: ACCESS_KEY_ID|ACCESS_SECRET_KEY
    version: 3.9.1
