apiVersion: v1
kind: Secret
metadata:
    name: convertx
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:VJACJqVXLPLVB2qtFDTaEd7eTNoQ2j0dchxzVPbC/c1cIFbHF6IM61zTh8B+ODFlZ8uQtqKj/MM9+a98,iv:Y1NC1HXRJV+dhG0Xae0nIFVCqRQ1ZyPbv7CvNu72+WI=,tag:3dZ7ZHcstawnKA6nMS6eNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aXZHQlRYSnhnZW55T3lJ
            bm1rMU9yWUVRZXNIdUVDYkRHcUY2WnllRkZZClpwK1lqcklFeUFxTXpSdFBVb01y
            eC9vY1NBNjlHQVRqQzNIa1hqelhTRkkKLS0tIEgwU1pNTnVsREhWT3FCZHlIb2Rw
            WlNLSzBQYWdCNmVuTkVRV3VBWXVrU0EKl9s+YhmP0kXtizpY8JixIEXn0m9VOF+0
            WhYGFrsMhf7xwjG8gLo7jv1mGKYxbmlO7XmSayMB+dDCOnS5I3unkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T17:07:40Z"
    mac: ENC[AES256_GCM,data:ejybiHOFH9d45bgA6B2jKgdLyCft6rI65E2sbctMiKHOi2N2umZkqpOUe1PrpdKd0NZXdxgQ1OSQE3TsNiCEwsP1cjFxqxA0MD7OufPtwvum+mofgre1LTMKeu3jRxsuA3rbmMjaaFxY+6cQpEnsGxvkINJN5XtecuGXKmbbbfk=,iv:ugsC5WCVcWomdD9CQYezqR0Sv7UKIa1txWqOOP0M0us=,tag:Lr5kcy50IORD594hFk6ymA==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
