apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-invidious.yaml
  - helmrelease-invidious-cluster.yaml
  - secret-invidious.yaml
  - deployment-invidious.yaml
  - deployment-invidious-companion.yaml
  - service-invidious.yaml
  - service-invidious-companion.yaml
  - ingress-invidious.yaml
  - networkpolicy-invidious.yaml
  - ../../infrastructure/cnpg/networkpolicy