apiVersion: v1
kind: Secret
metadata:
    name: invidious-secrets
type: Opaque
stringData:
    HMAC_KEY: ENC[AES256_GCM,data:Ok+VD515zJPvrVRO21kegA==,iv:BeLpsuspn2j2SONC7lZZNJGQlKEO+YuryQCLEu/oJ4o=,tag:zdf1dXTVC8Gh+Z4sP+HYuw==,type:str]
    COMPANION_KEY: ENC[AES256_GCM,data:+9J7sWopPEc7rJ2CEQ7ofQ==,iv:SxdULvVr7AoFWCzPV9rS1BJizOCZW29+fk+4gme0Rk8=,tag:fzdfqEB0sq9iFy4tF5QvvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaFVOSGxuQ3k5eGRBMlpR
            MkQxTkZQbW04c0RxeGJqcS9UVmNWelBLVXpJClBObDhMSVhUQVFwam02a0ZiV3Y0
            VkJpZUtPZmlmVkV5aEFVVmQwVHBLKzAKLS0tIFJXeGhXUUZXWmoxOS9Vb1lXd3Rz
            MlJ0VHg5N1BOWWxia2dScng0cSsyZVUKSbpqWfNuwz5w63ze2Ega8PdvGYqdn/AO
            BZ3huxX2QhKBtEIS6s2AQEQBSRVUr34H5HkPTEJgJGfgcf3eH0dlxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T08:37:56Z"
    mac: ENC[AES256_GCM,data:VpbVqSRUDjOuePpztAfX3UkVNdF53iMGj1Gv3v+nMjpz4T0uIadZvGFNtgF33Eue+KIMz4+MPd+rWtyQ4XRtYdnuDzDkKrjZU3JRdLgqa0ODdhinLvAdvlGZssmR1E+zdMzdres9NcZQOUF05d/jG+G6PpeQzTCW5dkNztfHHNU=,iv:7iQEtP3zIsmnXYiG8nbc00vqk5PEFhB5VmxLWbt27Ug=,tag:mDL91AbwRBY3kxFNq7gxuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
