apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen38-flash-next-llamacpp-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 150Gi
