apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qwen38-flash-next-llamacpp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qwen38-flash-next-llamacpp
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 4s
