apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-snapshotter
  namespace: external-snapshotter
spec:
  interval: 24h
  chart:
    spec:
      chart: snapshot-controller
      sourceRef:
        kind: HelmRepository
        name: external-snapshotter
        namespace: external-snapshotter
      interval: 24h