apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-openobserve-root.yaml
  - secret-openobserve-sre.yaml
  - secret-o2c-auth.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - helmrelease-collector.yaml
