apiVersion: v1
kind: Secret
metadata:
    name: openobserve-sre
stringData:
    ai-api-key: ENC[AES256_GCM,data:yap4PMufMfIRDOFzjzQINGTZzAfauJYfLK7QVrO3c21wC5E=,iv:JzkAUhCkyKhrlySIFMd7a/S61Jkh+wbcEFua8MDuWr0=,tag:9DlSY5oSqxifwVahOZZgQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y014eUFMU0xnSSt3dEpp
            d3FqRGdwa1hBemRoNDhYL0h4NzU0QlZTV0JrCnU1TktDN1AwalU0bGE5aGhKdkNU
            R1JzQmRBQndwU0VVaWpueTNXWnd6OWcKLS0tIGt6ZnNkKzlrdWl6NnFQTll3ZWxk
            K2p4aWtzaFQ5U3ZqTW9maGNtT3Evb0kK+IAoJYytW58oyPeVsiSM9RtS9daeQubH
            +K1jHU0Cbqv0uhKovI0oG+xrq5kWaFVqvPYMvAB0JL1RefiHfta/rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T08:17:47Z"
    mac: ENC[AES256_GCM,data:9SOc8g1VqTfnpog0CUJEYikHoCWeOhg0MsS1IPc7jCYv/wJ0DRYTDFKOJrvRXIdrJQHuxTvZv/olIzRF0w3Ce+1BC9KYYWCYH1sxiYbQt8xv4/bmodOmEobgVy6RG+OxHlB25wMnW8FBHWvXRfA7vPvQqeSEjsercfHfDOJqNsA=,iv:97/tJnbmFIlhpnH+j6IWiuTZpxQ5qniSbQkG4C2Lrsc=,tag:aVHYaYYOIXdyNFM1OwUryA==,type:str]
    pgp: []
    encrypted_regex: ai-api-key
    version: 3.9.1
