apiVersion: v1
kind: Secret
metadata:
    name: openobserve-sre
stringData:
    ai-api-key: ENC[AES256_GCM,data:0AcTmhOGow0IeWgckPMYaGfJUk3Pia/oCCRfWykbp9VMACEjunq9AVCTLf3POOhKl5YTxPQ=,iv:ZqVc2dqLX/IIDSEUWaXeO9lY8Hs9ZaMuLW5DdiXef6E=,tag:1u2FWmON0clyjBoLgH54qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y014eUFMU0xnSSt3dEpp
            d3FqRGdwa1hBemRoNDhYL0h4NzU0QlZTV0JrCnU1TktDN1AwalU0bGE5aGhKdkNU
            R1JzQmRBQndwU0VVaWpueTNXWnd6OWcKLS0tIGt6ZnNkKzlrdWl6NnFQTll3ZWxk
            K2p4aWtzaFQ5U3ZqTW9maGNtT3Evb0kK+IAoJYytW58oyPeVsiSM9RtS9daeQubH
            +K1jHU0Cbqv0uhKovI0oG+xrq5kWaFVqvPYMvAB0JL1RefiHfta/rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T08:08:30Z"
    mac: ENC[AES256_GCM,data:HbJwVHrj5L09LLFxU4vLzjOtcSaZKMnr15eRJc+x0l24i1K95zigB7zXkmBpeo90z7FeMaOZIM92I7MhJS9uAr0tXpaW1oXntOGh/FZ04fC3LOAvlvFG+SApLGMaqnWhvUumrAvqRJUpBW+knHIVsECdvqmUYIa20zTwvZN+5bU=,iv:kfp/PfD9gSPmXdgCIBrFi4d3eeE+RTV2itvFvvZUlME=,tag:STavEq9AjOYiD5z1WbGYEw==,type:str]
    pgp: []
    encrypted_regex: ai-api-key
    version: 3.9.1
