apiVersion: v1
kind: Secret
metadata:
    name: openobserve-smtp
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:m8J6qrycDLs+HK8+Eo2Yscqnd3vq,iv:Uqt8CGXyYoq9DhOavJ9Y0hNY/pcmJjACGaqaxo2SG14=,tag:Anu3u9MbxiPSNn5A1MLyMw==,type:str]
    password: ENC[AES256_GCM,data:HtEtF2+onQh9HY8stj0vXGgqP7VjETOjG+zX9I8ceGClQoMEhJCSUw==,iv:t6sjAP1NcoOI7Rv2BLKPKOtaneO0CSWceVJOcIu7/co=,tag:yi75iySftnzHY+f1Y7TfKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cFZ0OFBmdzNzVUYzWFVQ
            UjlQU0ZVd2Jsa2lHS0VGZXR5ZmV0Zk5EeVVzCmsxRTRUWHViOTg1cm9rdnA1NlA4
            ekZBQUVZMEc5Mkc5cDk1VmwxRGZTQ3cKLS0tIGtoQjQ3R2EvQ1Q2b2t6dDZZd2Q0
            STJNUG5VZkNDMmVRVWxGZVJyUFlORncKElQv0zGsG7TeYC/ksFg4xlujgyM2BSqR
            eVCAv7LiQCUAGsBDoqmN6FZQtRXhcslyUt2LHH20ddvJwcI5/FFuJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T09:17:31Z"
    mac: ENC[AES256_GCM,data:SwjuhE3L9N5uMsLURCPOd5JQDXsIq8aKgBjhme7XnIe3IZ9z1RtLjye0ivrgH3Nk9q096FTg0H3K/V9JXsFiZt99bR3AfiIyJrgpYnRlanvgIIcZB8PRovBKii72881FNfP3hcSJplfrReRHtvGq4OQE4x/LnbGIxODL228diHA=,iv:tJ2m6ok3HCypYdciwH76OBHinmKQuJpn2V7slnQlwbQ=,tag:ZlBoAPjQs+ZXiXjA30dA1g==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
