apiVersion: v1
kind: Secret
metadata:
    name: o2c-auth
type: Opaque
stringData:
    authorization: ENC[AES256_GCM,data:3cCwF+ljmsIvkSAnse6UkaKYGrIOleqCUB2HWrd4N58cMq3kVXwtnwU7OYvX7I2Y7rsCdyRpOIo6Eg==,iv:vSQkR2Mbqm6LariKfyX2EvXeIDmdVxJ6zJu1E+D1u1g=,tag:ZUBUMGbZMIdc5ebuj9oyQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMjQ0UjdFcTl5Qkw3WHRJ
            M0pzd09wSlFDYmo4RUJTVU01bEl2d1U5WENzCnFjK2VWTG5nMUhUV3piVzJHZS9m
            TWI4MWpjQ0VYa08xbjhwUGIzS2hMTlEKLS0tIEdiUVc2bzkyTVJyRU9kZ3dVS1Y4
            a2dtSXpJQ2JDNU5RL1ZEVHZucTdNNmsK/pYfuGjJaRVNiA7n75eayZb5y6NxkLmq
            ILn/09kqJKfb+f34KdpZYytHYjj4igqQGyfVnG7O2bWiP1WcEuPkcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T06:14:49Z"
    mac: ENC[AES256_GCM,data:yQa19GfpngX71K1wVFjjOWfgq8sPr1Lwx+CaXK/41Q75x1gDth4HHAt1j9s+ksxMA/y6w5sSfSanQ+GpxkD1pKpSoJDeB1oK7IM9xOQbYdLKAE2JDk20k1agiAsvqXFNATg3gWQzgzRaA1GQq07ssiezPyfbicmClu4qjdXSBjY=,iv:0amMWx46o3UDGMydB5xEQi/40Wy7o5lnPWBkWU/fE5s=,tag:wDd9aS6LB/Fhi398KteOvw==,type:str]
    pgp: []
    encrypted_regex: authorization
    version: 3.9.1
