apiVersion: v1
kind: Secret
metadata:
    name: openobserve-smtp
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:m8J6qrycDLs+HK8+Eo2Yscqnd3vq,iv:Uqt8CGXyYoq9DhOavJ9Y0hNY/pcmJjACGaqaxo2SG14=,tag:Anu3u9MbxiPSNn5A1MLyMw==,type:str]
    password: ENC[AES256_GCM,data:oCgG0u+DV0kSiHQOiVF79YdHO+pEOjsGiGdsYjnrYErYiUCZPzH1eg==,iv:wPWB2WLkMTKOcifw5FZSpJrcanq67fcgTmv7UHjaJkY=,tag:cL723YBBAAycaC043z3Uwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cFZ0OFBmdzNzVUYzWFVQ
            UjlQU0ZVd2Jsa2lHS0VGZXR5ZmV0Zk5EeVVzCmsxRTRUWHViOTg1cm9rdnA1NlA4
            ekZBQUVZMEc5Mkc5cDk1VmwxRGZTQ3cKLS0tIGtoQjQ3R2EvQ1Q2b2t6dDZZd2Q0
            STJNUG5VZkNDMmVRVWxGZVJyUFlORncKElQv0zGsG7TeYC/ksFg4xlujgyM2BSqR
            eVCAv7LiQCUAGsBDoqmN6FZQtRXhcslyUt2LHH20ddvJwcI5/FFuJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T08:29:55Z"
    mac: ENC[AES256_GCM,data:zXlzFuBRUpUQA7AEZNlgyaNLEe2hgkbTo3Z4KCClygVVoEYu9oNJiP/jKgAMpRZHbg6zm65ppN0XY/IVQzXnGXauM/n9I3yU+ExEpl310+3CvYOeKbwzg+m7S4gRxtQs/B+1NSjT7WngkP7ezQ5MsaPF3mkDh/iMHwE7t+UDzF4=,iv:FrT07qGPWsooOkatPsjjQLX+SuHeIHTv8fvE0tN76+U=,tag:B185Se/Vr5KMNnZc9aYJlg==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
