apiVersion: v1
kind: Secret
metadata:
    name: openobserve-sre
stringData:
    ai-api-key: ENC[AES256_GCM,data:pdtojKnoHL/71NdxNZUEMDhDjwiPxQowkhLFK820YagVmkXJIQHazxi/9fLvM0E1vw==,iv:qKJ0rSpXGZVAmsIOh8wYjw1IU2Vdwz4LvYQ1qUon980=,tag:tV3gq5uycZuPWZR8unSFZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y014eUFMU0xnSSt3dEpp
            d3FqRGdwa1hBemRoNDhYL0h4NzU0QlZTV0JrCnU1TktDN1AwalU0bGE5aGhKdkNU
            R1JzQmRBQndwU0VVaWpueTNXWnd6OWcKLS0tIGt6ZnNkKzlrdWl6NnFQTll3ZWxk
            K2p4aWtzaFQ5U3ZqTW9maGNtT3Evb0kK+IAoJYytW58oyPeVsiSM9RtS9daeQubH
            +K1jHU0Cbqv0uhKovI0oG+xrq5kWaFVqvPYMvAB0JL1RefiHfta/rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T07:42:09Z"
    mac: ENC[AES256_GCM,data:4e8/ReJ5JUm7fwRk9aFjcFfKwvOXw2zJzx+tMj3v9Gd4w6YnVaY2a/6+4BjAwppGaDQ2pIW90cpWeVBoxWNtCadaO1qn+vTpqeMfIcXBr1fv4Xu6Q7tf7M242MI7TNHt9B1PekOYgKZB1aADutD2rbEL2WzaeRUj4V8psHSIuz4=,iv:XdC3VfC4ofuGdWCzJyJCNNT3hS+rK/Q2sDgF8VQkgBs=,tag:/SV0gS8z92ecrR4O26CeXg==,type:str]
    pgp: []
    encrypted_regex: ai-api-key
    version: 3.9.1
