apiVersion: v1
kind: Secret
metadata:
    name: openobserve-root
type: Opaque
stringData:
    root-email: ENC[AES256_GCM,data:rfGfUROV+bQJNyU0h61vzw==,iv:9cU4M9O0XqlbJTOc5yxYkV57n+2MqR0ofY4QHpzNZ/Y=,tag:O+KkCE4e2KYZDcrsQwecqw==,type:str]
    root-password: ENC[AES256_GCM,data:mjABHZiVsG8fS3HSc0iYi9RlP02TCw==,iv:cfVspIHe/NXfQgB+gprSB+zVqZhpSLgidLJPF6fsgrs=,tag:nIeqUE+Wy6DAM6MuykQhYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaUhsSVR1bkR0ZkVJWVB1
            emhmV0RYOEVVaVBCdXRwemsvY2lId0hwUzJRCmR1dXlBdm9KUVZTYy94aW0wT0Nl
            cWFoN2huWEJ4bHViTGRkRHFXQ3p3aTQKLS0tIFpoKzROSWtpSVQ4QjFTQlNwVEsv
            SFg2aTBSbXY0ckVPSEd4d2VibStaRzAKj5ZD/1XKm7+ocP+mXuoBPBIjcfTAnzfu
            BNHCAHARavSbsO+0AIGWqj3sbsLAtWnCdkHQLCCdO/MNm5PkPZkKrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T06:15:07Z"
    mac: ENC[AES256_GCM,data:88sQKeC9m2ltSymVI54gTHjoVa7CcEPl904seaHVAzfTW195oJLlC1wzeKK0S01PFoyC2agVVCsO6vkHv0jF80AnTGzLhnyrs7xixA9OuFR9l6xYK6Lk9/BIYtLW3NWnL9RgKewaCZnuXz6gQM89VljwlUHqrV1nwFAsvEti2mk=,iv:DAzw9cBI+UROy7x0PhbQM+6CfQjn3u/CJAz1FJ/z5hQ=,tag:NGNIdUT2juN2vKKzYnkTIw==,type:str]
    pgp: []
    encrypted_regex: root-.*
    version: 3.9.1
