apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-ldap-bind-password.yaml
  - helmrelease-stalwart-cluster.yaml
  - gitrepo.yaml
  - helmrelease.yaml
  - tailscale.yaml