apiVersion: v1
kind: Secret
metadata:
    name: ldap-bind-password
type: Opaque
stringData:
    ldap-bind-password: ENC[AES256_GCM,data:QvXruI6iZGx5iZ0X6s63By9cK3yfJ1FE+An5jHj/23tvXmZS3qqhq9X/JBY/OpPUQ7rGcM/F0RuNDyeC,iv:ohxxD9TTHrEy947aX3YlymKzmAjytDpwyA+OfqzVt5Y=,tag:SQR5jrAjjMREOAlUA39acA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcXd3RitiMHY4cTRRVmEv
            RDVqYmhET2o4MjZQemU3WmFjbmIvQll4dFdZCmxNY2tEb2pxdFV0ZkZJcGcwUlpW
            N0llMzVaQ1BRYXVhSkhxNzY1azhqNk0KLS0tIHVzVjBrR1czMzJJcTQ4a2locFRu
            OHd2NjJ3RUs2dHJjN1ZnUHdDQ2psdlEKv2aT1GzJfHL3Q3/grg5tAkmGcGcTKSeR
            /gIHPY7437yuzMFXnaWhTa2kQUAvuqdqdP5KuTt8rLFbnJKJl72jmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T03:50:56Z"
    mac: ENC[AES256_GCM,data:KAwwb8qCvf4+tp4eF/sc3jzufJhIc5bfS9MMT91EF03OjAycM3uCyT/Ect9zeX6m9cFLmMrnlmxqaZAjJMXvmxpqTWkhQeTA7MYkjKt1rmZ7DBnN2PFr1VnVvys7/kvqGhMAuxe1NfW2qryU2an6fwrlnPdoXwf0dZ+kPXD34Mc=,iv:Qf644u0LOmSfRyOBNl2YP7NvkpE5eEHo538ctZGU96s=,tag:5bbgzVR2i9qmWwixxTWoew==,type:str]
    pgp: []
    encrypted_regex: ldap-bind-password
    version: 3.9.1
