---
apiVersion: v1
kind: Service
metadata:
  name: postfix
  annotations:
    tailscale.com/tailnet-fqdn: "ubuntu.cloudforest-sargas.ts.net"
    tailscale.com/proxy-group: "egress-proxies"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 25
      name: smtp
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: stalwart-inbound
  annotations:
    tailscale.com/tailnet-fqdn: "stalwart-inbound.cloudforest-sargas.ts.net"
    tailscale.com/proxy-group: "ingress-proxies"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: stalwart
  ports:
    - port: 25
      name: smtp
      targetPort: 25
      protocol: TCP