apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress-proxies
spec:
  type: egress
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: postfix
  annotations:
    tailscale.com/tailnet-fqdn: "ubuntu.cloudforest-sargas.ts.net"
    tailscale.com/proxy-group: "egress-proxies"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 25
      name: smtp
      protocol: TCP