apiVersion: v1
kind: Secret
metadata:
    name: holmes-secrets
type: Opaque
stringData:
    openai-api-key: ENC[AES256_GCM,data:bgqIIKPPKyNB3xkQSC+FBKPgMIUOIg9utjKMBjvU0ZdqidUpcM9eWCBBPZGvIZmS5ay0,iv:x0eLOUKvlIlgaFOopIL8VuEcrp2SuzD6yeaTrmTXTCk=,tag:RaUyBNhHI76vDouOpevD9g==,type:str]
    openai-api-base: https://api.xiaomimimo.com/v1
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVWlLWkE3Y3QrQlR2cHlj
            SVN3REdsZDlBOEk2Y2RxNDNGN1JVM1hZdmpjClRUK1h0U1RTN2NQSVh4WmpCT1J0
            amIxWFNSbzgweUFDTytEU0NCL2VRWlkKLS0tIDF0eS9icDZwY25VSmZRS1o0czEr
            a2JLMnpWd2tTUnJSMmJkZllzUisrdXMKAzWGCxLZOFzmLqC3HlP08VRjbVvAKh4t
            byrYpEYHZP9TaV8hkRGwVluHKpdXmgnjfkuJsfpkkJmoWZIPo3BNOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T13:23:15Z"
    mac: ENC[AES256_GCM,data:ATl34QPPNBgthAwchK5r1dojcHnPnpR7wlY24CxVyleM1Wcg76NIbYVDnonhskXXJts8k2Y16PMQC2B+Q6hOltk0h4qU0go8jFjyERn1G1nkUTagWK23F+zh7frPzpwI9Nqu9PsnqJnmJIEyX0GJILO1wS+2ctwVo8+560zfjTc=,iv:+2a+jWXL72xQmGh3I6lLoY9uvgVPW5/QG+YyqhTnDu0=,tag:BZv/XRXtbuWHaW978lYe0Q==,type:str]
    pgp: []
    encrypted_regex: openai-api-key
    version: 3.13.1
