apiVersion: v1
kind: Secret
metadata:
    name: holmes-secrets
type: Opaque
stringData:
    openai-api-key: ENC[AES256_GCM,data:P4ctnHRy9yYAgcQx36xcAOWu6m5jZzZOmzSxqVGCBHB6vzfMGLKu8dZpEGCuuqmDuQ27+sXmDBJ3/cuwBsTr8asJrUS0cw5C4xQ+8zlrZXJ7tqXkt/RqNiPCQL9plxOImFA25ovrY/gYdZYIlW4exUSBqxmGRVKy+L4a/n6u,iv:a0ML/idlVjCUNl8HuZOLIiHINeTIU7GJpEc9ozo7f9s=,tag:0nVuCP9eAWBVqLNV8pVZuQ==,type:str]
    openai-api-base: https://api.minimax.io/v1
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVWlLWkE3Y3QrQlR2cHlj
            SVN3REdsZDlBOEk2Y2RxNDNGN1JVM1hZdmpjClRUK1h0U1RTN2NQSVh4WmpCT1J0
            amIxWFNSbzgweUFDTytEU0NCL2VRWlkKLS0tIDF0eS9icDZwY25VSmZRS1o0czEr
            a2JLMnpWd2tTUnJSMmJkZllzUisrdXMKAzWGCxLZOFzmLqC3HlP08VRjbVvAKh4t
            byrYpEYHZP9TaV8hkRGwVluHKpdXmgnjfkuJsfpkkJmoWZIPo3BNOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T14:08:11Z"
    mac: ENC[AES256_GCM,data:qcSOPPWzbKz2VWWo7tRzzIvwoYsa2jyETlhIXSI/NUcSVkLklVxw5VBxyoALB2dH2AqJkNRlezdZX2QeP+eZof7kGHKHM8x1RYQr/Lq9WwvEwsvIUmD+iEZo+FdtkzjbaMrYY321fTbvY6ygmoyanSD3/y+VqpsGY3AK/e+3B/Y=,iv:PHexI7OdA5KvO0LR9t0jkcfgsC+pum2DTqr5RqGF434=,tag:q4C2v9LLMH7IRJHuUYbXDg==,type:str]
    pgp: []
    encrypted_regex: openai-api-key
    version: 3.13.1
