apiVersion: v1
kind: Secret
metadata:
    name: holmes-secrets
type: Opaque
stringData:
    openai-api-key: ENC[AES256_GCM,data:P4ctnHRy9yYAgcQx36xcAOWu6m5jZzZOmzSxqVGCBHB6vzfMGLKu8dZpEGCuuqmDuQ27+sXmDBJ3/cuwBsTr8asJrUS0cw5C4xQ+8zlrZXJ7tqXkt/RqNiPCQL9plxOImFA25ovrY/gYdZYIlW4exUSBqxmGRVKy+L4a/n6u,iv:a0ML/idlVjCUNl8HuZOLIiHINeTIU7GJpEc9ozo7f9s=,tag:0nVuCP9eAWBVqLNV8pVZuQ==,type:str]
    openai-api-base: https://api.xiaomimimo.com/v1
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVWlLWkE3Y3QrQlR2cHlj
            SVN3REdsZDlBOEk2Y2RxNDNGN1JVM1hZdmpjClRUK1h0U1RTN2NQSVh4WmpCT1J0
            amIxWFNSbzgweUFDTytEU0NCL2VRWlkKLS0tIDF0eS9icDZwY25VSmZRS1o0czEr
            a2JLMnpWd2tTUnJSMmJkZllzUisrdXMKAzWGCxLZOFzmLqC3HlP08VRjbVvAKh4t
            byrYpEYHZP9TaV8hkRGwVluHKpdXmgnjfkuJsfpkkJmoWZIPo3BNOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T13:52:28Z"
    mac: ENC[AES256_GCM,data:chTc3p6goLtNfpkxkW/YKZmYMDPHMwN43UvpvOkgx4/Gwz/+4afZAd2YGTi3JrEBdH5ZQ+EOsKAmPrnxL7HLkd1XdIfk2j2izKnKcrLiJ1KZeIuEQHBK7HFrhnsj1601K6flDsaMil8cbOHmSXZwdcfdE1/RvlHOgSnXvD+fiXU=,iv:q6U6k2fkar+coLSxm93FK5CkapjtKj2NvIBiTw/Rtyw=,tag:XwEP7oGCX7ESlsasrxnVlg==,type:str]
    pgp: []
    encrypted_regex: openai-api-key
    version: 3.13.1
