apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyseerr
  name: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - image: fallenbagel/jellyseerr:2.7.0
          name: jellyseerr
          resources: {}
          env:
            - name: LOG_LEVEL
              value: debug
            - name: PORT
              value: "5055"
            - name: TZ
              value: Asia/Riyadh
          ports:
            - containerPort: 5055
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config
              name: jellyseerr
      restartPolicy: Always
      volumes:
        - name: jellyseerr
          persistentVolumeClaim:
            claimName: jellyseerr