apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xormon
subjects:
- kind: ServiceAccount
  name: xormon
  namespace: xormon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xormon