apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xormon
  name: xormon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xormon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: xormon
    spec:
      containers:
        - image: xorux/xormon-ng:2.3.21
          name: xormon
          resources: {}
          env:
            - name: APP_DEBUG
              value: "false"
            - name: APP_PORT
              value: "8443"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: app
                  name: xormon
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: xormon-cluster-v00-app
                  key: dbname
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xormon-cluster-v00-app
                  key: password
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: xormon-cluster-v00-app
                  key: user
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: xormon-cluster-v00-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: xormon-cluster-v00-app
                  key: port
            - name: TZ
              value: Asia/Riyadh
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8162
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/src/app/server-nest/files
              name: xormon
            - mountPath: /app/server-nest/ssl/xormon.crt
              name: xormon-ssl
              subPath: tls.crt
            - mountPath: /app/server-nest/ssl/xormon.key
              name: xormon-ssl
              subPath: tls.key
      restartPolicy: Always
      volumes:
        - name: xormon
          persistentVolumeClaim:
            claimName: xormon
        - name: xormon-ssl
          secret:
            secretName: almothana-xyz-tls
