apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xormon
resources:
  - namespace.yaml
  - PVC-timescaledb.yaml
  - PVC-xormon.yaml
  - secret-timescaledb.yaml
  - secret-xormon.yaml
  - deployment-timescaledb.yaml
  - deployment-xormon.yaml
  - service-timescaledb.yaml
  - service-xormon.yaml
  - ingress-xormon.yaml