apiVersion: v1
kind: Secret
metadata:
    name: restic-config-xormon
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:DUDIPCum2q314CIztaC1lysxpeRKEpezdY9fGZ81XCXpW2ehpW+EO5GLW6L5m8lwbA==,iv:GYuhAFg6dQ9NN+D+8RSbnVGYVrtO8AApZvX9U3kPDaw=,tag:03+CysxjCgl6RH6cLjTp7w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:55dIlq5fYwIrPCW2BArBTGf9,iv:Lw+3s3cBmqM526oaZWG9LM9RVWLo6x/daZTeY5RGWfc=,tag:o3W2fqySDdGISzApetZD+w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zGFc5Vto,iv:SNeU/YXaxhe7UMn1ZHKPtGGMT5ntzj9WGa0Y3fTgXcE=,tag:soPSRmBkoA/glGho43gQ+A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mRaqw3Od9E1ExhbL,iv:C9+Z/1aj738HiG9A/9KOa24olrEpuwYhRMZ15f5hnSw=,tag:2o6S8TmThSlX11N7jnvIJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T14:44:23Z"
    mac: ENC[AES256_GCM,data:kN194+yhuLdKWLqkOLI/dCPux4dDHQjhK2migRkipkozwSwJeeatPXWTfAIVmbrAEq7xo5LfD3ewRFDc+BhLM93Okg2Tb58Ge4RH5PpS3X4lQRDgLXH0zSw8AWyH+Oh3aPkwOW0qI5oukdZnWGHIr7QIFKz93urTyNXBJwp9FaY=,iv:mR8AjkGvd+DfJN/G1zhuRcYLqOVOmFeImEqykNwpWJs=,tag:Gat53SwFdoaRgVxOsK83ow==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
    name: xormon
spec:
    sourcePVC: xormon
    trigger:
        schedule: 0 12 * * *
    restic:
        pruneIntervalDays: 7
        repository: restic-config-xormon
        retain:
            hourly: 1
            daily: 1
            weekly: 1
            monthly: 1
            yearly: 1
        copyMethod: Direct
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T14:44:23Z"
    mac: ENC[AES256_GCM,data:kN194+yhuLdKWLqkOLI/dCPux4dDHQjhK2migRkipkozwSwJeeatPXWTfAIVmbrAEq7xo5LfD3ewRFDc+BhLM93Okg2Tb58Ge4RH5PpS3X4lQRDgLXH0zSw8AWyH+Oh3aPkwOW0qI5oukdZnWGHIr7QIFKz93urTyNXBJwp9FaY=,iv:mR8AjkGvd+DfJN/G1zhuRcYLqOVOmFeImEqykNwpWJs=,tag:Gat53SwFdoaRgVxOsK83ow==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
    name: xormon
spec:
    trigger:
        manual: restore-once
    restic:
        repository: restic-config-xormon
        destinationPVC: xormon
        copyMethod: Direct
        cleanupCachePVC: true
        cleanupTempPVC: true
        moverSecurityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T14:44:23Z"
    mac: ENC[AES256_GCM,data:kN194+yhuLdKWLqkOLI/dCPux4dDHQjhK2migRkipkozwSwJeeatPXWTfAIVmbrAEq7xo5LfD3ewRFDc+BhLM93Okg2Tb58Ge4RH5PpS3X4lQRDgLXH0zSw8AWyH+Oh3aPkwOW0qI5oukdZnWGHIr7QIFKz93urTyNXBJwp9FaY=,iv:mR8AjkGvd+DfJN/G1zhuRcYLqOVOmFeImEqykNwpWJs=,tag:Gat53SwFdoaRgVxOsK83ow==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-timescaledb
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:PGmvkrKQ4Ag6Gqggb2tJmiNUAZGKYeVk6PjCGvHeLBGxPf7X52X0+V1ux/hoX8B4wCZ85dYR,iv:/f0fMyJgqM+97ZeG9TlHSL5MwIk+Nt2qWDOKzCM8vJo=,tag:HytChhpqXF163nK9H8sPiQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:55dIlq5fYwIrPCW2BArBTGf9,iv:Lw+3s3cBmqM526oaZWG9LM9RVWLo6x/daZTeY5RGWfc=,tag:o3W2fqySDdGISzApetZD+w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zGFc5Vto,iv:SNeU/YXaxhe7UMn1ZHKPtGGMT5ntzj9WGa0Y3fTgXcE=,tag:soPSRmBkoA/glGho43gQ+A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mRaqw3Od9E1ExhbL,iv:C9+Z/1aj738HiG9A/9KOa24olrEpuwYhRMZ15f5hnSw=,tag:2o6S8TmThSlX11N7jnvIJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T14:44:23Z"
    mac: ENC[AES256_GCM,data:kN194+yhuLdKWLqkOLI/dCPux4dDHQjhK2migRkipkozwSwJeeatPXWTfAIVmbrAEq7xo5LfD3ewRFDc+BhLM93Okg2Tb58Ge4RH5PpS3X4lQRDgLXH0zSw8AWyH+Oh3aPkwOW0qI5oukdZnWGHIr7QIFKz93urTyNXBJwp9FaY=,iv:mR8AjkGvd+DfJN/G1zhuRcYLqOVOmFeImEqykNwpWJs=,tag:Gat53SwFdoaRgVxOsK83ow==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
    name: timescaledb
spec:
    sourcePVC: timescaledb
    trigger:
        schedule: 0 12 * * *
    restic:
        pruneIntervalDays: 7
        repository: restic-config-timescaledb
        retain:
            hourly: 1
            daily: 1
            weekly: 1
            monthly: 1
            yearly: 1
        copyMethod: Direct
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T14:44:23Z"
    mac: ENC[AES256_GCM,data:kN194+yhuLdKWLqkOLI/dCPux4dDHQjhK2migRkipkozwSwJeeatPXWTfAIVmbrAEq7xo5LfD3ewRFDc+BhLM93Okg2Tb58Ge4RH5PpS3X4lQRDgLXH0zSw8AWyH+Oh3aPkwOW0qI5oukdZnWGHIr7QIFKz93urTyNXBJwp9FaY=,iv:mR8AjkGvd+DfJN/G1zhuRcYLqOVOmFeImEqykNwpWJs=,tag:Gat53SwFdoaRgVxOsK83ow==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
    name: timescaledb
spec:
    trigger:
        manual: restore-once
    restic:
        repository: restic-config-timescaledb
        destinationPVC: timescaledb
        copyMethod: Direct
        cleanupCachePVC: true
        cleanupTempPVC: true
        moverSecurityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T14:44:23Z"
    mac: ENC[AES256_GCM,data:kN194+yhuLdKWLqkOLI/dCPux4dDHQjhK2migRkipkozwSwJeeatPXWTfAIVmbrAEq7xo5LfD3ewRFDc+BhLM93Okg2Tb58Ge4RH5PpS3X4lQRDgLXH0zSw8AWyH+Oh3aPkwOW0qI5oukdZnWGHIr7QIFKz93urTyNXBJwp9FaY=,iv:mR8AjkGvd+DfJN/G1zhuRcYLqOVOmFeImEqykNwpWJs=,tag:Gat53SwFdoaRgVxOsK83ow==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
