apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  interval: 24h
  chart:
    spec:
      chart: synology-csi
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: synology-csi
      interval: 24h
  values:
    storageClasses:
      synology-iscsi:
        disabled: false
        isDefault: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          dsm: "192.168.8.109"
          fsType: ext4
          location: /volume1
          formatOptions: '-E nodiscard'
    volumeSnapshotClasses:
      synology-snapshotclass:
        disabled: false
        deletionPolicy: Delete
        isDefault: false
        parameters:
          description: "Kubernetes CSI"
          is_locked: "false"