apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bulkwark
spec:
  ingressClassName: cilium
  rules:
  - host: webmail.almothana.cloud
    http:
      paths:
      - backend:
          service:
            name: bulkwark
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
    - hosts:
        - webmail.almothana.cloud
      secretName: almothana-cloud-tls