apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - PVC-bulkwark.yaml
  - configmap-bulkwark-env.yaml
  - secret-bulkwark-env.yaml
  - deployment-bulkwark.yaml
  - service-bulkwark.yaml
  - ingress-bulkwark.yaml
  - namespace.yaml
