apiVersion: v1
kind: Secret
metadata:
    name: bulkwark-env
stringData:
    OAUTH_ENABLED: ENC[AES256_GCM,data:3mpzlg==,iv:VlkRtwiOfghzWh8qoqWWV+Mxe6MnIRXMZn4TU2RLxdw=,tag:OfNWJUKooWPW8WZyR4Zchg==,type:bool]
    OAUTH_ONLY: ENC[AES256_GCM,data:U+VNlQ==,iv:7wbhqVSyvS0lFc40o3Klf3fz724BKRDSwY6yeN78Ze4=,tag:M2o7yjFeh4rqkGoiXKri/Q==,type:bool]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:COYmz7sG/iRFRXABnUmevWBPJ8UXsw+WP/gC9z62wvTfr3+cWGdgTQ==,iv:FKqd7CC1rcHxOCYYez7Lwr4egIs3thrEUbyF+3As6hM=,tag:6dPKtBvtqT/d8pqAGaHc9Q==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:4S7IkPnwv8rdZCN1lG+6/C0fF5bZstg/yNVFp/Fih7ZqpmyDNv9hEo6xo1xyCc5attrLSKVNhy4k8CmIPiN1Xm0eGwRG4Vtbvowp8vHoezMH7kPEeHqAfZguxSB1IKpA29A0Yr7ek9CrNKcYKzUKZJ2Kqj+ABYyFhYEigZFOTSY=,iv:pi947fZ2vKIq4CZhR7UvU8UTp2ULXvv8XMAhaINUbAY=,tag:7zXwMEgKgpg2ZorxkEMfXA==,type:str]
    OAUTH_ISSUER_URL: ENC[AES256_GCM,data:gM1nOzlv6x7AwGBTEAIvoF+h3BmJLQekm4xuetynXpcr7VT68Wx/tDTgIuuMlZBamLsAQWQr,iv:uPJ+9Dfnu1Kza86cvlL4QmmP2oilPM3QIr142HtsLCw=,tag:upCgS7vQ4PgDeUSQsg7H4g==,type:str]
    OAUTH_ALLOW_PRIVATE_ENDPOINTS: ENC[AES256_GCM,data:qyGlpQ==,iv:QB+GpYdrHipOi0enUa60EUeDOJPhWgt1UzulcJonUjs=,tag:xACQgEr4XUY4duCG2eQF6w==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdlE1MzgydG5MWHJqQlpv
            L2N2MkRqUlJacEpMd3A2Rk5DM0lVT1Z0UVNFClZDK1ZIcUttOTR6NCtjNnBaaHdv
            ZjlOZ3R2VFdIRW5GVG1yTVNoZFA4T2cKLS0tIG9rOHR0VC9LbmhZZ1pIZTRFNXZk
            YnlpVGVZNVZxMmt5Z1pMaEVhQjc4WHMKtYU50/PBxdYxemhiH0QruYGUboZC9K/k
            cB8oyZnMwnf/v2r+dC8f0Mc9RZ6KqtYTLUxcFGV5se08P1IgUyA8iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T14:00:12Z"
    mac: ENC[AES256_GCM,data:Itdf/cyNK5XLQRTzjs4aqbYmB1XWasz9ILS5GCaZb0pe4//cXI644RpxNRrIwzLgaYEegsqyYk+9o3ZgYqA6OakhJB+pgqcnXv7Smjq6ugyDkQdctAkEhRp2eQ+kqJrNtlUQqWI3Sig1alo2dMMrWRH5YV43c2HL11FUdfNsD4g=,iv:PgUGLs8V3vXl9RwtAXNK9ZpT9MrlliTbJuRqZTfeOOs=,tag:kP2vlmiR5PWF2GTHdUUAYg==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.13.1
