apiVersion: v1
kind: Secret
metadata:
    name: bulkwark-env
stringData:
    OAUTH_ENABLED: ENC[AES256_GCM,data:cpEAQg==,iv:Gnqksab3PXyR8ZjdqLvA3vg3UTjO8hjtRGBaV+36OLI=,tag:vCSxQ0uBdu+l19GQcPeOIQ==,type:str]
    OAUTH_ONLY: ENC[AES256_GCM,data:HH3zjQ==,iv:Ef7nFW4Sk00qJkRJ/ZAbn8uuVBinWFJ0f6HOsuc4rfE=,tag:dTHIA8WYURNK4Y/Tfktxdw==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:hOodePLJeHHytCDQaYE=,iv:5FHtJGF4NCn/3svyfXnvaK9agfWvqAZdGas8C34I4Vw=,tag:syFWDyhqHZMXRsImOzwG7A==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:NDcSLjP3rUxd5dLJT+p98CqISkX35Czdl8kqxiXSc5zuzkp0jigBWZFUwP7zO4u2enhEafdor/X1IC+sYVYSU/oN8YttkzrMb5rBcJKJ6LpYW+Zs0JPwlqoNXaW3pOsmOTvQ77sWJKwP79KEQcxynYLIRQ8rK5RxQw5n4K7g9LDM8SHYlrThEQ4uNp/16xMgPQ==,iv:+LpwGdWSO5tEmmzfqFA7Isg4AA4LSODNk3Qo88nb13A=,tag:SLWHdSZUOnGhzTu/4DS1IQ==,type:str]
    OAUTH_ISSUER_URL: ENC[AES256_GCM,data:Mnh56gTKuYMJVbIa1CcYpvwLdJPcvavV6eLTKq7RxoYx6LkyOnynMgJKKUJOL+9s,iv:0bSGRY+B8mFQGtfVMB3UJI8KnWE/JvsKLutEN4c9Avk=,tag:ExLBBt63F469IjWoFoNQOw==,type:str]
    OAUTH_ALLOW_PRIVATE_ENDPOINTS: ENC[AES256_GCM,data:b0102g==,iv:AiuqhNthoh0SUMOpVIxTh/hQTSm96gkqtoIh6yqQPUA=,tag:Q847nelQf6mD4eIaqYHHeA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:71XfoVHI7DBS6WlwTGr2ja10XreIda4X+OnQSTIYrDH0Mb1HRo1M+U960zfqpWq3mWTlYSjeIIujhpp2BMrD,iv:N+VOJcR56paIYvbEJ0B8wqkrTcAk1s783RmRvdJkeCQ=,tag:IkXD1CTSTl6mGdy+K6WybA==,type:str]
    #ENC[AES256_GCM,data:PwtGQMkNTrxHVTnB7mXzSsfQ3Q9IhzRQniBlMO4ua5jj7fRi4JWU,iv:S5xOBORNa58oZEVx3QNkRKYpqLQPK+QEodwqdqkNFLQ=,tag:aamEEOrQMOc8cY+nwu5wdg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdlE1MzgydG5MWHJqQlpv
            L2N2MkRqUlJacEpMd3A2Rk5DM0lVT1Z0UVNFClZDK1ZIcUttOTR6NCtjNnBaaHdv
            ZjlOZ3R2VFdIRW5GVG1yTVNoZFA4T2cKLS0tIG9rOHR0VC9LbmhZZ1pIZTRFNXZk
            YnlpVGVZNVZxMmt5Z1pMaEVhQjc4WHMKtYU50/PBxdYxemhiH0QruYGUboZC9K/k
            cB8oyZnMwnf/v2r+dC8f0Mc9RZ6KqtYTLUxcFGV5se08P1IgUyA8iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T15:22:02Z"
    mac: ENC[AES256_GCM,data:Ke906Cfee5bVlul6u584TzzAzK5hIVByOfrrRi3n6uuh27CRgIM0+BfwbZXrkGhYPn3jxzUXn2AXGcwJrxIiT9AIbbSmjPmpEFVgpB8lDXLLUotIvm+VZmZfHgZCssc7OT4a0EEzugawP5GLS/3DCglfQ2nexYnYycHbgqkQ2gY=,iv:Ys1zUlEnj+BInR9SzGMskAqxrnEyAbsSMFhkpcu2I70=,tag:X5XQ9//5hIfx7e7rhij8ug==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.13.1
