apiVersion: v1
kind: Secret
metadata:
    name: restic-config-bulkwark
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:zdX5sbgCOCSO6EspcuP/LpsFAcVVlAa3PIrKmlxdGTi2pr2/lo+62/A1Ddw=,iv:024b7L1kMa+Lcu7h7wzB1CObgqrLmKy995hP6q81PC0=,tag:BaHrWM9shxLARxTlc3pXEg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:55dIlq5fYwIrPCW2BArBTGf9,iv:Lw+3s3cBmqM526oaZWG9LM9RVWLo6x/daZTeY5RGWfc=,tag:o3W2fqySDdGISzApetZD+w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zGFc5Vto,iv:SNeU/YXaxhe7UMn1ZHKPtGGMT5ntzj9WGa0Y3fTgXcE=,tag:soPSRmBkoA/glGho43gQ+A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mRaqw3Od9E1ExhbL,iv:C9+Z/1aj738HiG9A/9KOa24olrEpuwYhRMZ15f5hnSw=,tag:2o6S8TmThSlX11N7jnvIJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T16:48:59Z"
    mac: ENC[AES256_GCM,data:qDytloQHK7SqId1yWX4a97kwFB/m2uWX11yeSCAHDfe7CuKqRgmF1khT9dHyToBhje6OnTkXDKElUj3OHuzyjM9HL2UEfGc2QHxE4pVIdO44yACsVBQEB44a561IMOlIGzUb3N/pU6ckq+WpcgfV4CZOveLqfrR+mTFXEVWoPc8=,iv:6dmPA2O1xMX2r1gmCWd7ndvcxsZ7QwQVd5R1MprJpxY=,tag:SEbtNowST4Lfx9mxVCAD+A==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
    name: bulkwark
spec:
    sourcePVC: bulkwark
    trigger:
        schedule: 0 7 * * *
    restic:
        pruneIntervalDays: 7
        repository: restic-config-bulkwark
        retain:
            hourly: 1
            daily: 7
            weekly: 4
            monthly: 2
            yearly: 1
        copyMethod: Direct
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T16:48:59Z"
    mac: ENC[AES256_GCM,data:qDytloQHK7SqId1yWX4a97kwFB/m2uWX11yeSCAHDfe7CuKqRgmF1khT9dHyToBhje6OnTkXDKElUj3OHuzyjM9HL2UEfGc2QHxE4pVIdO44yACsVBQEB44a561IMOlIGzUb3N/pU6ckq+WpcgfV4CZOveLqfrR+mTFXEVWoPc8=,iv:6dmPA2O1xMX2r1gmCWd7ndvcxsZ7QwQVd5R1MprJpxY=,tag:SEbtNowST4Lfx9mxVCAD+A==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
    name: bulkwark
spec:
    trigger:
        manual: restore-once
    restic:
        repository: restic-config-bulkwark
        destinationPVC: bulkwark-restore
        copyMethod: Direct
        cleanupCachePVC: true
        cleanupTempPVC: true
        moverSecurityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aUJvZkczekdxWU9URHFI
            M3htdVcwNnRNSDZrclYwVTY2RDZ0cWlBWFE4CmFrMXdaQjNFb2lGMlpyRktUVWEw
            VzNBV2tPcG4yYU40RDdhR0NvTmRaUkEKLS0tIDFrQkw0NU4yVDloYU82TTFJTG9q
            Wk9wVHhSREczUmY3b254dEtVb0ZITkEKqT/D3ZX4zJ3+R/ghjZaDhkAP22CzgjR5
            9KOJb5NrKqXauTE2wbALoWlaGmXnoigP27azMzA+1/lGXjOz3E5lIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T16:48:59Z"
    mac: ENC[AES256_GCM,data:qDytloQHK7SqId1yWX4a97kwFB/m2uWX11yeSCAHDfe7CuKqRgmF1khT9dHyToBhje6OnTkXDKElUj3OHuzyjM9HL2UEfGc2QHxE4pVIdO44yACsVBQEB44a561IMOlIGzUb3N/pU6ckq+WpcgfV4CZOveLqfrR+mTFXEVWoPc8=,iv:6dmPA2O1xMX2r1gmCWd7ndvcxsZ7QwQVd5R1MprJpxY=,tag:SEbtNowST4Lfx9mxVCAD+A==,type:str]
    pgp: []
    encrypted_regex: RESTIC_REPOSITORY|RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY
    version: 3.9.1
