apiVersion: v1
kind: Secret
metadata:
    name: open-webui
type: Opaque
stringData:
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:6jy4jAA8Icp4MERLOISo++0lZuMIgyuUjA5TYq0OMSzN8iVvzpNT5tWsak1hVrTNq6WXerjPeuR3GPa3udAoag==,iv:rTfeSOYGDuxzlXmlIGaoZ4ct3qrI44o/VhavdZEbt2U=,tag:ydbobGHdOMYY9px4Fvsqww==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:1QxkzwT3Hx047phn+A3MXfCuOCEGnJ3nqE+WL99Z0X5EnkN2unte5Q==,iv:q9QWOFGsXUFtmSR1ToKU91AX2nn4hp775JyGVJ73BgY=,tag:9eIBj7EL0CVTiAeo0n8cGw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:kSuBYG4+QxeM5xBkQ0CgsRp4g5yjaAJpxdPGmomcjF8hPEdWe4+NUM1/xuLfT3wYrCH9gpvLiAFRZWLnLi433ZGk+kbpyZcW0AFuaceLx3rd9ZFWDtyrh5L9/3uj9sTdZVsFyCHjn7xEoG4UulvOi7NH/gdXsFe80rcI/B8AFP8=,iv:g20hLpJECzUJbFAbmDiV4GAzc78p1cm63sfqP6KVxZo=,tag:SKuXxDq75PrmS+lWUmHuyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSk9HMGhnR3BoOVRyTGow
            bkFTcEhSdlZVSWN2V0Q1RXRlWkQxWjhEZDM4ClpxZUtYRU9JUFNobzJJc3NoaVJU
            a1VCVVRITkdUNlc1ZWwweWlXU0ZiUE0KLS0tIGloZkgwVE1kSFlEaWptVnVpR2dG
            UldGdEp4VVIxTlZTU212UDZKOGkxV1kKzUU2AMNfzY++y6dgqXMT3uZ4EJo8ndLv
            a13GSEX3DVJO7aryeSqc2dL9S7oxYshjbW7tXf0jKGSuwfGUk6iUUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-12T16:07:44Z"
    mac: ENC[AES256_GCM,data:iAv0bRVDoW1a/xT+9LYojF8MXjHvK2cUQgLf9lWXeXeKolTv6zfWpj3opS2jOgzj1iijv42xobHwMpo9z1L3EcQPXx4TueFtvyWUAd6VNRQuIYWJzUxuZaf9gEM38+SByYlJaK/QTZd5/mi0txuVzUbtqFpeV9Bzz05BWsHowIc=,iv:RyNkcWI7It64zKtCYIXRdnek1HCyuZeN5nP6yyLTKAI=,tag:yha3ZRqtw4c4OOIv6GAyOQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
