apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-freshrss.yaml
  - networkpolicy-freshrss.yaml
  - PVC-freshrss.yaml
  - secret-freshrss.yaml
  - deployment-freshrss.yaml
  - service-freshrss.yaml
  - ingress-freshrss.yaml