apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: freshrss
spec:
  endpointSelector:
    matchLabels:
      app: freshrss
  ingress:
    # From Ingress
    - fromEntities:
        - ingress
    # From Cloudflared namespace
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: cloudflared
  egress:
    # To DNS
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    # To Authentik
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/component: server
            app.kubernetes.io/instance: authentik
            app.kubernetes.io/name: authentik
            io.kubernetes.pod.namespace: authentik
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    # To pods in the same namespace
    - toEndpoints:
        - {}
    # To the Internet (RSS feeds)
    - toEntities:
        - world