apiVersion: v1
kind: Secret
metadata:
    name: freshrss
type: Opaque
stringData:
    OIDC_ENABLED: ENC[AES256_GCM,data:TQ==,iv:jXqDK/liDmNFhkVke9IaWFJbIOWQuF35yt1YJIgAGts=,tag:hMmFdO/JLwd8v2iLfObwTg==,type:str]
    OIDC_PROVIDER_METADATA_URL: ENC[AES256_GCM,data:Ls6XSPeasyNtDXpI6i94ljFKiGWvXJjR0vvIj8uZNQbs/SrckNzXqnISwrhC+ABsECDQ7bQcWUMcl5985xnldSQeavpLmmtEyzF8YZWJofc=,iv:kTz6rAD3r4LiWTBuDxiicGdeW9LOi5F7+3vHyADBzqs=,tag:9Hkc12xdyVWi9P2nEuAAtQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:JEA00CQk1rc7nX3vrvQzXYtaDgGzJpa6X2SEekVuohsa3O+8O2Ak5A==,iv:6fV1f2bdS7n6qvHCCZwBFUj/pC+7m1TTzHteySgk9+g=,tag:wtrtec4CBOiXc32wx3SIKw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:D01kzNsWbwuhz0nb+5Tcbrm89pvy/aSxGemreCWPkMeIkOe+fRTL8fsK571wiSAAZm08aHLKoAkp+PEShhypMb6ArhvZurDr7upFwISyuIX8W0dQ1UOMxIaH6PQYCt38APG0+nKfXjDTf4s3FofaGnLT8a0E00kN2KzXT9KA24U=,iv:vBlRH5jZ4FYRNbnGQpRuUnsnER3abnhckg3OiCLUbGI=,tag:kFP768lBoWiNzsdqeJ6fZw==,type:str]
    OIDC_CLIENT_CRYPTO_KEY: ENC[AES256_GCM,data:W/ZFwpNYYZB+eyvQGCctiAvejv21TpHTkVRMHzBG4Rc6po4CoxZT5r8=,iv:d0KA/qSrIcDIOeaUDUzcUUdbQvtpBj3VffaTgHFD6UY=,tag:bxrrfaNCOlcUwURiwZZVVg==,type:str]
    OIDC_REMOTE_USER_CLAIM: ENC[AES256_GCM,data:VAd/5UH9OAsQ0zXafFt/ANV4,iv:CxQ/AZ0NGtwPMHxYuMbBwZB8cjeJbMeQs1+rk0yozA8=,tag:sJ+WxqT1oDWTKdB01tKQCA==,type:str]
    OIDC_X_FORWARDED_HEADERS: ENC[AES256_GCM,data:SSlwTw34fpc0Zir6tvIodMM=,iv:0ApnDd4O4V415EVYMtAqGn9I51QjMJJEZiu13Xts+ts=,tag:2dQWSC904zYdUBJuY5H0uw==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:imkRFOmj/ymPc+jLc5vC94dzvb0=,iv:Qj9gWSkK7hdZgVR7GP7BZ7NYEuJPmTiv/XVZjxuslD8=,tag:JX+rQRNgs2nfJHlLmVuxXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14cy4q3ul8qdg4sezqcv3kv8l6z2s20m4zthhux0l2pccmett2ecqnlz5g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHakc5KzJMQmJndXpwOUUx
            dlplSFBTUVFlekFpZ2o0dDIrUzQ5SkRzOEJRCkRONklWMXRyeDBiMXQyUHZFYUxV
            eW5xYld6dHZhRUYrc0lVSjFwZHllaUUKLS0tIGxTSTJDL1lOcG9vYjN0dVNwLzBN
            alljWnlRY2plbTdQdU1aOEY2SFlLMjgK/wl6XGtIMo3jKq7uPcDsLBBb0nBoVrpz
            cqx/OiDJDpVda27YvUN5Sxyr6VTKrSozq9l+4gHL58IzmdMNVdfDbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T03:55:37Z"
    mac: ENC[AES256_GCM,data:AmmJcHGYpq/VWKDxcHDWB0pWDtDOoxIYGHqi47fYbWRWqKpxWqYlpGbaonld0VKQoWDAiS/s+jny+O497eyY3T4edYPlSSFamD+Up7V+LOOya1buI8Vaqh2lLSit/YMCoZOE1f3NSCdPU68HFQwjUH8XL7ATh7nANPpm0pWOpsM=,iv:jmteD8NEpZWd4bCPqdWp3sFwVqwLF78F1Q4Zo49vuzU=,tag:bs29F/aYx8XTBhsRH2EElw==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.1
