---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jellystat-nas
  name: jellystat-nas-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
