apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.14.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 5m
  values: 
    controller:
      ingressClassResource:
        name: nginx
        enabled: true
        default: true